import type { Cert } from '../schema'

/**
 * DVA-C02 structure. Domain titles, task titles and every skill bullet are
 * verbatim from the official AWS exam guide. Note DVA states its content as
 * numbered *skills* rather than SAA's "Knowledge of / Skills in" split, so
 * `knowledge` is empty here by design and `skills` carries the outline.
 *
 * Source: https://docs.aws.amazon.com/aws-certification/latest/developer-associate-02/developer-associate-02.html
 */
export const dvaC02: Cert = {
  id: 'DVA-C02',
  family: 'dva',
  versionCode: 'C02',
  status: 'current',
  title: 'AWS Certified Developer – Associate',
  shortTitle: 'Developer',
  role: 'You write, ship, secure and debug the code that runs on AWS.',
  minutes: 130,
  questionCount: 65,
  scoredCount: 50,
  passScore: 720,
  passAccuracy: 0.72,
  scaleMin: 100,
  scaleMax: 1000,
  guideUrl:
    'https://docs.aws.amazon.com/aws-certification/latest/developer-associate-02/developer-associate-02.html',
  blurb:
    'Not an architecture exam — a build-and-debug exam. It wants the specific: which Lambda setting, which DynamoDB API call, which CodeDeploy strategy, which log query. Depth on Lambda, DynamoDB, API Gateway, IAM/Cognito and CI/CD carries the paper.',
  domains: [
    {
      id: 'dva-d1',
      certId: 'DVA-C02',
      index: 1,
      title: 'Development with AWS Services',
      weight: 32,
      blurb:
        'The largest domain. Lambda configuration and DynamoDB data modelling between them account for most of it — partition keys, consistency, query vs. scan, concurrency, event sources.',
      tasks: [
        {
          id: 'dva-1.1',
          domainId: 'dva-d1',
          code: '1.1',
          title: 'Develop code for applications hosted on AWS',
          knowledge: [],
          skills: [
            'Describe architectural patterns (for example, event-driven, microservices, monolithic, choreography, orchestration, fanout)',
            'Describe differences between stateful and stateless concepts',
            'Describe differences between tightly coupled and loosely coupled components',
            'Describe differences between synchronous and asynchronous patterns',
            'Create fault-tolerant and resilient applications in a programming language (for example, Java, C#, Python, JavaScript, TypeScript, Go)',
            'Create, extend, and maintain APIs (for example, response/request transformations, enforcing validation rules, overriding status codes)',
            'Write and run unit tests in development environments (for example, using AWS SAM)',
            'Write code to use messaging services',
            'Write code that interacts with AWS services by using APIs and AWS SDKs',
            'Handle streaming data using AWS services',
            'Use Amazon Q Developer to assist with development',
            'Use Amazon EventBridge to implement event-driven patterns',
            'Implement resilient application code for third-party service integrations (for example, retry logic, circuit breakers, error handling patterns)',
          ],
          serviceSlugs: [
            'api-gateway',
            'sqs',
            'sns',
            'eventbridge',
            'step-functions',
            'appsync',
            'kinesis-data-streams',
            'sam',
            'sdk',
            'q-developer',
            'cli',
          ],
        },
        {
          id: 'dva-1.2',
          domainId: 'dva-d1',
          code: '1.2',
          title: 'Develop code for AWS Lambda',
          knowledge: [],
          skills: [
            'Describe the access of private resources in VPCs from Lambda code',
            'Configure Lambda functions by defining environment variables and parameters (for example, memory, concurrency, timeout, runtime, handler, layers, extensions, triggers, destinations)',
            'Handle the event lifecycle and errors by using code (for example, Lambda Destinations, dead-letter queues)',
            'Write and run test code by using AWS services and tools',
            'Integrate Lambda functions with AWS services',
            'Tune Lambda functions for optimal performance',
            'Use Lambda functions to process and transform data in near real time',
          ],
          serviceSlugs: ['lambda', 'sqs', 'sns', 'eventbridge', 'vpc', 'cloudwatch', 'xray', 'sam'],
        },
        {
          id: 'dva-1.3',
          domainId: 'dva-d1',
          code: '1.3',
          title: 'Use data stores in application development',
          knowledge: [],
          skills: [
            'Describe high-cardinality partition keys for balanced partition access',
            'Describe database consistency models (for example, strongly consistent, eventually consistent)',
            'Describe differences between query and scan operations',
            'Define Amazon DynamoDB keys and indexing',
            'Serialize and deserialize data to provide persistence to a data store',
            'Use, manage, and maintain data stores',
            'Manage data lifecycles',
            'Use data caching services',
            'Use specialized data stores based on access patterns (for example, Amazon OpenSearch Service)',
          ],
          serviceSlugs: [
            'dynamodb',
            'rds',
            'aurora',
            'elasticache',
            's3',
            'opensearch',
            'ebs',
            'efs',
          ],
        },
      ],
    },
    {
      id: 'dva-d2',
      certId: 'DVA-C02',
      index: 2,
      title: 'Security',
      weight: 26,
      blurb:
        'Application-level security, not network security. Cognito user pools vs. identity pools, assuming roles with STS, KMS envelope encryption, and never putting a secret in an environment variable in plaintext.',
      tasks: [
        {
          id: 'dva-2.1',
          domainId: 'dva-d2',
          code: '2.1',
          title: 'Implement authentication and/or authorization for applications and AWS services',
          knowledge: [],
          skills: [
            'Use an identity provider to implement federated access (for example, Amazon Cognito, IAM)',
            'Secure applications by using bearer tokens',
            'Configure programmatic access to AWS',
            'Make authenticated calls to AWS services',
            'Assume an IAM role',
            'Define permissions for IAM principals',
            'Implement application-level authorization for fine-grained access control',
            'Handle cross-service authentication in microservice architectures',
          ],
          serviceSlugs: ['cognito', 'iam', 'sts', 'api-gateway', 'sdk', 'iam-identity-center'],
        },
        {
          id: 'dva-2.2',
          domainId: 'dva-d2',
          code: '2.2',
          title: 'Implement encryption by using AWS services',
          knowledge: [],
          skills: [
            'Define encryption at rest and in transit',
            'Describe certificate management (for example, AWS Private CA)',
            'Describe differences between client-side encryption and server-side encryption',
            'Use encryption keys to encrypt or decrypt data',
            'Generate certificates and SSH keys for development purposes',
            'Use encryption across account boundaries',
            'Enable and disable key rotation',
          ],
          serviceSlugs: ['kms', 'acm', 's3', 'cloudhsm'],
        },
        {
          id: 'dva-2.3',
          domainId: 'dva-d2',
          code: '2.3',
          title: 'Manage sensitive data in application code',
          knowledge: [],
          skills: [
            'Describe data classification (for example, personally identifiable information [PII], protected health information [PHI])',
            'Encrypt environment variables that contain sensitive data',
            'Use secret management services to secure sensitive data',
            'Sanitize sensitive data',
            'Implement application-level data masking and sanitization',
            'Implement data access patterns for multi-tenant applications',
          ],
          serviceSlugs: ['secrets-manager', 'systems-manager', 'kms', 'macie', 'lambda'],
        },
      ],
    },
    {
      id: 'dva-d3',
      certId: 'DVA-C02',
      index: 3,
      title: 'Deployment',
      weight: 24,
      blurb:
        'Artifacts, environments and release strategies. Know SAM and CloudFormation, know API Gateway stages and stage variables, and know blue/green vs. canary vs. rolling well enough to pick one from a risk requirement.',
      tasks: [
        {
          id: 'dva-3.1',
          domainId: 'dva-d3',
          code: '3.1',
          title: 'Prepare application artifacts to be deployed to AWS',
          knowledge: [],
          skills: [
            'Manage the dependencies of the code module (for example, environment variables, configuration files, container images) within the package',
            'Organize files and a directory structure for application deployment',
            'Use code repositories in deployment environments',
            'Apply application requirements for resources (for example, memory, cores)',
            'Prepare application configurations for specific environments (for example, by using AWS AppConfig)',
          ],
          serviceSlugs: ['appconfig', 'ecr', 'codeartifact', 'lambda', 'sam', 'systems-manager'],
        },
        {
          id: 'dva-3.2',
          domainId: 'dva-d3',
          code: '3.2',
          title: 'Test applications in development environments',
          knowledge: [],
          skills: [
            'Test deployed code by using AWS services and tools',
            'Write integration tests and mock APIs for external dependencies',
            'Test applications by using development endpoints (for example, configuring stages in Amazon API Gateway)',
            'Deploy application stack updates to existing environments (for example, deploying an AWS SAM template to a different staging environment)',
            'Test event-driven applications',
          ],
          serviceSlugs: ['sam', 'api-gateway', 'cloudformation', 'lambda', 'cloudshell'],
        },
        {
          id: 'dva-3.3',
          domainId: 'dva-d3',
          code: '3.3',
          title: 'Automate deployment testing',
          knowledge: [],
          skills: [
            'Create application test events (for example, JSON payloads for testing AWS Lambda, API Gateway, AWS SAM resources)',
            'Deploy API resources to various environments',
            'Create application environments that use approved versions for integration testing (for example, Lambda aliases, container image tags, AWS Amplify branches, AWS Copilot environments)',
            'Implement and deploy infrastructure as code (IaC) templates (for example, AWS SAM templates, AWS CloudFormation templates)',
            'Manage environments in individual AWS services (for example, differentiating between development, test, and production in API Gateway)',
            'Use Amazon Q Developer to generate automated tests',
          ],
          serviceSlugs: [
            'cloudformation',
            'sam',
            'cdk',
            'lambda',
            'api-gateway',
            'amplify',
            'q-developer',
          ],
        },
        {
          id: 'dva-3.4',
          domainId: 'dva-d3',
          code: '3.4',
          title:
            'Deploy code by using AWS Continuous Integration and Continuous Delivery (CI/CD) services',
          knowledge: [],
          skills: [
            'Describe Lambda deployment packaging options',
            'Describe API Gateway stages and custom domains',
            'Update existing IaC templates (for example, AWS SAM templates, CloudFormation templates)',
            'Manage application environments by using AWS services',
            'Deploy an application version by using deployment strategies',
            'Commit code to a repository to invoke build, test, and deployment actions',
            'Use orchestrated workflows to deploy code to different environments',
            'Perform application rollbacks by using existing deployment strategies',
            'Use labels and branches for version and release management',
            'Use existing runtime configurations to create dynamic deployments (for example, using staging variables from API Gateway in Lambda functions)',
            'Configure deployment strategies (for example, blue/green, canary, rolling) for application releases',
          ],
          serviceSlugs: [
            'codepipeline',
            'codebuild',
            'codedeploy',
            'codeartifact',
            'cloudformation',
            'sam',
            'lambda',
            'api-gateway',
            'ecs',
            'elastic-beanstalk',
          ],
        },
      ],
    },
    {
      id: 'dva-d4',
      certId: 'DVA-C02',
      index: 4,
      title: 'Troubleshooting and Optimization',
      weight: 18,
      blurb:
        'Reading the evidence. CloudWatch Logs Insights queries, X-Ray traces and annotations, custom metrics via EMF, and the specific throttling/concurrency errors that tell you which knob to turn.',
      tasks: [
        {
          id: 'dva-4.1',
          domainId: 'dva-d4',
          code: '4.1',
          title: 'Assist in a root cause analysis',
          knowledge: [],
          skills: [
            'Debug code to identify defects',
            'Interpret application metrics, logs, and traces',
            'Query logs to find relevant data',
            'Implement custom metrics (for example, Amazon CloudWatch embedded metric format [EMF])',
            'Review application health by using dashboards and insights',
            'Troubleshoot deployment failures by using service output logs',
            'Debug service integration issues in applications',
          ],
          serviceSlugs: ['cloudwatch', 'xray', 'cloudtrail', 'cloudformation', 'codebuild'],
        },
        {
          id: 'dva-4.2',
          domainId: 'dva-d4',
          code: '4.2',
          title: 'Instrument code for observability',
          knowledge: [],
          skills: [
            'Describe differences between logging, monitoring, and observability',
            'Implement an effective logging strategy to record application behavior and state',
            'Implement code that emits custom metrics',
            'Add annotations for tracing services',
            'Implement notification alerts for specific actions (for example, notifications about quota limits or deployment completions)',
            'Implement tracing by using AWS services and tools',
            'Implement structured logging for application events and user actions',
            'Configure application health checks and readiness probes',
          ],
          serviceSlugs: ['cloudwatch', 'xray', 'sns', 'elb', 'lambda'],
        },
        {
          id: 'dva-4.3',
          domainId: 'dva-d4',
          code: '4.3',
          title: 'Optimize applications by using AWS services and features',
          knowledge: [],
          skills: [
            'Define concurrency',
            'Profile application performance',
            'Determine minimum memory and compute power for an application',
            'Use subscription filter policies to optimize messaging',
            'Cache content based on request headers',
            'Implement application-level caching to improve performance',
            'Optimize application resource usage',
            'Analyze application performance issues',
            'Use application logs to identify performance bottlenecks',
          ],
          serviceSlugs: [
            'lambda',
            'elasticache',
            'cloudfront',
            'api-gateway',
            'sns',
            'dynamodb',
            'cloudwatch',
          ],
        },
      ],
    },
  ],
}
