import type { Cert } from '../schema'

/**
 * SAA-C03 structure. Domain titles, task-statement titles, and every
 * "Knowledge of" / "Skills in" bullet are verbatim from the official AWS exam
 * guide. `blurb` and `serviceSlugs` are ours — they turn the outline into a
 * roadmap.
 *
 * Source: https://docs.aws.amazon.com/aws-certification/latest/solutions-architect-associate-03/solutions-architect-associate-03.html
 */
export const saaC03: Cert = {
  id: 'SAA-C03',
  title: 'AWS Certified Solutions Architect – Associate',
  shortTitle: 'Solutions Architect',
  role: 'You are handed requirements and must choose the architecture.',
  minutes: 130,
  questionCount: 65,
  scoredCount: 50,
  passScore: 720,
  scaleMin: 100,
  scaleMax: 1000,
  guideUrl:
    'https://docs.aws.amazon.com/aws-certification/latest/solutions-architect-associate-03/solutions-architect-associate-03.html',
  blurb:
    'Four questions in one, over and over: is it secure, does it survive failure, is it fast enough, and what does it cost? Every scenario question is one of those four wearing a business costume.',
  domains: [
    {
      id: 'saa-d1',
      certId: 'SAA-C03',
      index: 1,
      title: 'Design Secure Architectures',
      weight: 30,
      blurb:
        'The biggest domain, and the one most people fail on. It is almost never "what is IAM" — it is "given these four policies, is this call allowed?" Learn policy evaluation order and network segmentation and you have banked 30%.',
      tasks: [
        {
          id: 'saa-1.1',
          domainId: 'saa-d1',
          code: '1.1',
          title: 'Design secure access to AWS resources',
          knowledge: [
            'Access controls and management across multiple accounts',
            'AWS federated access and identity services (for example, IAM, AWS IAM Identity Center)',
            'AWS global infrastructure (for example, Availability Zones, AWS Regions)',
            'AWS security best practices (for example, the principle of least privilege)',
            'The AWS shared responsibility model',
          ],
          skills: [
            'Applying AWS security best practices to IAM users and root users (for example, multi-factor authentication [MFA])',
            'Designing a flexible authorization model that includes IAM users, groups, roles, and policies',
            'Designing a role-based access control strategy (for example, AWS STS, role switching, cross-account access)',
            'Designing a security strategy for multiple AWS accounts (for example, AWS Control Tower, service control policies [SCPs])',
            'Determining the appropriate use of resource policies for AWS services',
            'Determining when to federate a directory service with IAM roles',
          ],
          serviceSlugs: [
            'iam',
            'sts',
            'iam-identity-center',
            'organizations',
            'control-tower',
            'ram',
            'directory-service',
            'global-infrastructure',
            'console',
            'service-catalog',
            'well-architected-tool',
          ],
        },
        {
          id: 'saa-1.2',
          domainId: 'saa-d1',
          code: '1.2',
          title: 'Design secure workloads and applications',
          knowledge: [
            'Application configuration and credentials security',
            'AWS service endpoints',
            'Control ports, protocols, and network traffic on AWS',
            'Secure application access',
            'Security services with appropriate use cases (for example, AWS Cognito, AWS GuardDuty, AWS Macie)',
            'Threat vectors external to AWS (for example, DDoS, SQL injection)',
          ],
          skills: [
            'Designing VPC architectures with security components (for example, security groups, route tables, network ACLs, NAT gateways)',
            'Determining network segmentation strategies (for example, using public subnets and private subnets)',
            'Integrating AWS services to secure applications (for example, AWS Shield, AWS WAF, IAM Identity Center, AWS Secrets Manager)',
            'Securing external network connections to and from the AWS Cloud (for example, VPN, AWS Direct Connect)',
          ],
          serviceSlugs: [
            'vpc',
            'security-group',
            'nacl',
            'nat-gateway',
            'privatelink',
            'waf',
            'shield',
            'guardduty',
            'macie',
            'cognito',
            'secrets-manager',
            'inspector',
            'network-firewall',
            'firewall-manager',
            'detective',
            'security-hub',
            'client-vpn',
          ],
        },
        {
          id: 'saa-1.3',
          domainId: 'saa-d1',
          code: '1.3',
          title: 'Determine appropriate data security controls',
          knowledge: [
            'Data access and governance',
            'Data recovery',
            'Data retention and classification',
            'Encryption and appropriate key management',
          ],
          skills: [
            'Aligning AWS technologies to meet compliance requirements',
            'Encrypting data at rest (for example, AWS KMS)',
            'Encrypting data in transit (for example, AWS Certificate Manager [ACM] using TLS)',
            'Implementing access policies for encryption keys',
            'Implementing data backups and replications',
            'Implementing policies for data access, lifecycle, and protection',
            'Rotating encryption keys and renewing certificates',
          ],
          serviceSlugs: [
            'kms',
            'cloudhsm',
            'acm',
            's3',
            'backup',
            'macie',
            'secrets-manager',
            'audit-manager',
            'artifact',
            'config',
            'security-hub',
          ],
        },
      ],
    },
    {
      id: 'saa-d2',
      certId: 'SAA-C03',
      index: 2,
      title: 'Design Resilient Architectures',
      weight: 26,
      blurb:
        'Decoupling and surviving failure. If a question mentions a spike, a lost message, an AZ going down, or an RPO/RTO number, you are in this domain. The answers are nearly always: put a queue in it, spread it across AZs, or pick the cheapest DR strategy that still meets the number.',
      tasks: [
        {
          id: 'saa-2.1',
          domainId: 'saa-d2',
          code: '2.1',
          title: 'Design scalable and loosely coupled architectures',
          knowledge: [
            'API creation and management (for example, Amazon API Gateway, REST API)',
            'AWS managed services with appropriate use cases (for example, AWS Transfer Family, Amazon SQS, AWS Secrets Manager)',
            'Caching strategies',
            'Design principles for microservices (for example, stateless workloads compared with stateful workloads)',
            'Event-driven architectures',
            'Horizontal scaling and vertical scaling',
            'How to appropriately use edge accelerators (for example, content delivery network [CDN])',
            'How to migrate applications into containers',
            'Load balancing concepts (for example, Application Load Balancer [ALB])',
            'Multi-tier architectures',
            'Queuing and messaging concepts (for example, publish/subscribe)',
            'Serverless technologies and patterns (for example, AWS Fargate, AWS Lambda)',
            'Storage types with associated characteristics (for example, object, file, block)',
            'The orchestration of containers (for example, Amazon ECS, Amazon EKS)',
            'When to use read replicas',
            'Workflow orchestration (for example, AWS Step Functions)',
          ],
          skills: [
            'Designing event-driven, microservice, and/or multi-tier architectures based on requirements',
            'Determining scaling strategies for components used in an architecture design',
            'Determining the AWS services required to achieve loose coupling based on requirements',
            'Determining when to use containers',
            'Determining when to use serverless technologies and patterns',
            'Recommending appropriate compute, storage, networking, and database technologies based on requirements',
            'Using purpose-built AWS services for workloads',
          ],
          serviceSlugs: [
            'sqs',
            'sns',
            'eventbridge',
            'step-functions',
            'api-gateway',
            'lambda',
            'fargate',
            'ecs',
            'eks',
            'elb',
            'ec2-auto-scaling',
            'cloudfront',
            'elasticache',
            'appsync',
            'mq',
            'appflow',
            'ecs-anywhere',
            'device-farm',
          ],
        },
        {
          id: 'saa-2.2',
          domainId: 'saa-d2',
          code: '2.2',
          title: 'Design highly available and/or fault-tolerant architectures',
          knowledge: [
            'AWS global infrastructure (for example, Availability Zones, AWS Regions, Amazon Route 53)',
            'AWS Managed Services (AMS) with appropriate use cases (for example, Amazon Comprehend, Amazon Polly)',
            'Basic networking concepts (for example, route tables)',
            'Disaster recovery (DR) strategies (for example, backup and restore, pilot light, warm standby, active-active failover, recovery point objective [RPO], recovery time objective [RTO])',
            'Distributed design patterns',
            'Failover strategies',
            'Immutable infrastructure',
            'Load balancing concepts (for example, ALB)',
            'Proxy concepts (for example, Amazon RDS Proxy)',
            'Service quotas and throttling (for example, how to configure the service quotas for a workload in a standby environment)',
            'Storage options and characteristics (for example, durability, replication)',
            'Workload visibility (for example, AWS X-Ray)',
          ],
          skills: [
            'Determining automation strategies to ensure infrastructure integrity',
            'Determining the AWS services required to provide a highly available and/or fault-tolerant architecture across AWS Regions or Availability Zones',
            'Identifying metrics based on business requirements to deliver a highly available solution',
            'Implementing designs to mitigate single points of failure',
            'Implementing strategies to ensure the durability and availability of data (for example, backups)',
            'Selecting an appropriate DR strategy to meet business requirements',
            'Using AWS services that improve the reliability of legacy applications and applications not built for the cloud (for example, when application changes are not possible)',
            'Using purpose-built AWS services for workloads',
          ],
          serviceSlugs: [
            'route53',
            'elb',
            'ec2-auto-scaling',
            'rds',
            'aurora',
            'rds-proxy',
            'dynamodb',
            's3',
            'efs',
            'backup',
            'cloudformation',
            'global-accelerator',
            'xray',
            'global-infrastructure',
            'comprehend',
            'polly',
            'rekognition',
            'textract',
            'transcribe',
            'translate',
            'kendra',
            'lex',
            'sagemaker',
            'managed-grafana',
            'managed-prometheus',
            'health-dashboard',
            'config',
          ],
        },
      ],
    },
    {
      id: 'saa-d3',
      certId: 'SAA-C03',
      index: 3,
      title: 'Design High-Performing Architectures',
      weight: 24,
      blurb:
        'Picking the right tool per layer: storage, compute, database, network, ingestion. This domain is won on elimination — knowing that EFS is not for block, that DynamoDB is not for joins, that a CDN fixes latency but not throughput.',
      tasks: [
        {
          id: 'saa-3.1',
          domainId: 'saa-d3',
          code: '3.1',
          title: 'Determine high-performing and/or scalable storage solutions',
          knowledge: [
            'Hybrid storage solutions to meet business requirements',
            'Storage services with appropriate use cases (for example, Amazon S3, Amazon EFS, Amazon EBS)',
            'Storage types with associated characteristics (for example, object, file, block)',
          ],
          skills: [
            'Determining storage services and configurations that meet performance demands',
            'Determining storage services that can scale to accommodate future needs',
          ],
          serviceSlugs: [
            's3',
            'ebs',
            'efs',
            'fsx',
            'storage-gateway',
            's3-glacier',
            'instance-store',
          ],
        },
        {
          id: 'saa-3.2',
          domainId: 'saa-d3',
          code: '3.2',
          title: 'Design high-performing and elastic compute solutions',
          knowledge: [
            'AWS compute services with appropriate use cases (for example, AWS Batch, Amazon EMR, AWS Fargate)',
            'Distributed computing concepts supported by AWS global infrastructure and edge services',
            'Queuing and messaging concepts (for example, publish/subscribe)',
            'Scalability capabilities with appropriate use cases (for example, Amazon EC2 Auto Scaling, AWS Auto Scaling)',
            'Serverless technologies and patterns (for example, AWS Lambda, Fargate)',
            'The orchestration of containers (for example, Amazon ECS, Amazon EKS)',
          ],
          skills: [
            'Decoupling workloads so that components can scale independently',
            'Identifying metrics and conditions to perform scaling actions',
            'Selecting the appropriate compute options and features (for example, EC2 instance types) to meet business requirements',
            'Selecting the appropriate resource type and size (for example, the amount of Lambda memory) to meet business requirements',
          ],
          serviceSlugs: [
            'ec2',
            'ec2-auto-scaling',
            'auto-scaling',
            'lambda',
            'fargate',
            'ecs',
            'eks',
            'batch',
            'emr',
            'elastic-beanstalk',
            'wavelength',
            'vmware-cloud',
            'serverless-application-repository',
            'eks-anywhere',
            'eks-distro',
          ],
        },
        {
          id: 'saa-3.3',
          domainId: 'saa-d3',
          code: '3.3',
          title: 'Determine high-performing database solutions',
          knowledge: [
            'AWS global infrastructure (for example, Availability Zones, AWS Regions)',
            'Caching strategies and services (for example, Amazon ElastiCache)',
            'Data access patterns (for example, read-intensive compared with write-intensive)',
            'Database capacity planning (for example, capacity units, instance types, Provisioned IOPS)',
            'Database connections and proxies',
            'Database engines with appropriate use cases (for example, heterogeneous migrations, homogeneous migrations)',
            'Database replication (for example, read replicas)',
            'Database types and services (for example, serverless, relational compared with non-relational, in-memory)',
          ],
          skills: [
            'Configuring read replicas to meet business requirements',
            'Designing database architectures',
            'Determining an appropriate database engine (for example, MySQL compared with PostgreSQL)',
            'Determining an appropriate database type (for example, Amazon Aurora, Amazon DynamoDB)',
            'Integrating caching to meet business requirements',
          ],
          serviceSlugs: [
            'rds',
            'aurora',
            'aurora-serverless',
            'dynamodb',
            'elasticache',
            'redshift',
            'documentdb',
            'neptune',
            'keyspaces',
            'rds-proxy',
            'dms',
            'timestream',
          ],
        },
        {
          id: 'saa-3.4',
          domainId: 'saa-d3',
          code: '3.4',
          title: 'Determine high-performing and/or scalable network architectures',
          knowledge: [
            'Edge networking services with appropriate use cases (for example, Amazon CloudFront, AWS Global Accelerator)',
            'How to design network architecture (for example, subnet tiers, routing, IP addressing)',
            'Load balancing concepts (for example, Application Load Balancer)',
            'Network connection options (for example, AWS VPN, AWS Direct Connect, AWS PrivateLink)',
          ],
          skills: [
            'Creating a network topology for various architectures (for example, global, hybrid, multi-tier)',
            'Determining network configurations that can scale to accommodate future needs',
            'Determining the appropriate placement of resources to meet business requirements',
            'Selecting the appropriate load balancing strategy',
          ],
          serviceSlugs: [
            'vpc',
            'cloudfront',
            'global-accelerator',
            'elb',
            'route53',
            'direct-connect',
            'site-to-site-vpn',
            'transit-gateway',
            'privatelink',
            'vpc-peering',
          ],
        },
        {
          id: 'saa-3.5',
          domainId: 'saa-d3',
          code: '3.5',
          title: 'Determine high-performing data ingestion and transformation solutions',
          knowledge: [
            'Data analytics and visualization services with appropriate use cases (for example, Amazon Athena, AWS Lake Formation, Amazon QuickSuite)',
            'Data ingestion patterns (for example, frequency)',
            'Data transfer services with appropriate use cases (for example, AWS DataSync, AWS Storage Gateway)',
            'Data transformation services with appropriate use cases (for example, AWS Glue)',
            'Secure access to ingestion access points',
            'Sizes and speeds needed to meet business requirements',
            'Streaming data services with appropriate use cases (for example, Amazon Kinesis)',
          ],
          skills: [
            'Building and securing data lakes',
            'Designing data streaming architectures',
            'Designing data transfer solutions',
            'Implementing visualization strategies',
            'Selecting appropriate compute options for data processing (for example, Amazon EMR)',
            'Selecting appropriate configurations for ingestion',
            'Transforming data between formats (for example, .csv to .parquet)',
          ],
          serviceSlugs: [
            'kinesis-data-streams',
            'data-firehose',
            'msk',
            'glue',
            'athena',
            'emr',
            'lake-formation',
            'redshift',
            'quick-suite',
            'datasync',
            'storage-gateway',
            'transfer-family',
            'snow-family',
            'opensearch',
            'data-exchange',
            'kinesis-video-streams',
            'elastic-transcoder',
            'application-migration-service',
          ],
        },
      ],
    },
    {
      id: 'saa-d4',
      certId: 'SAA-C03',
      index: 4,
      title: 'Design Cost-Optimized Architectures',
      weight: 20,
      blurb:
        'The same services again, judged only on price. Two ideas carry most of the marks: data transfer is where the bill hides (NAT gateways, cross-AZ, egress), and commitment beats on-demand when the load is predictable.',
      tasks: [
        {
          id: 'saa-4.1',
          domainId: 'saa-d4',
          code: '4.1',
          title: 'Design cost-optimized storage solutions',
          knowledge: [
            'Access options (for example, an S3 bucket with Requester Pays object storage)',
            'AWS cost management service features (for example, cost allocation tags, multi-account billing)',
            'AWS cost management tools with appropriate use cases (for example, AWS Cost Explorer, AWS Budgets, AWS Cost and Usage Report)',
            'AWS storage services with appropriate use cases (for example, Amazon FSx, Amazon EFS, Amazon S3, Amazon EBS)',
            'Backup strategies',
            'Block storage options (for example, hard disk drive [HDD] volume types, solid state drive [SSD] volume types)',
            'Data lifecycles',
            'Hybrid storage options (for example, AWS DataSync, AWS Transfer Family, AWS Storage Gateway)',
            'Storage access patterns',
            'Storage tiering (for example, cold tiering for object storage)',
            'Storage types with associated characteristics (for example, object, file, block)',
          ],
          skills: [
            'Designing appropriate storage strategies (for example, batch uploads to Amazon S3 compared with individual uploads)',
            'Determining the correct storage size for a workload',
            'Determining the lowest cost method of transferring data for a workload to AWS storage',
            'Determining when storage auto scaling is required',
            'Managing S3 object lifecycles',
            'Selecting the appropriate backup and/or archival solution',
            'Selecting the appropriate service for data migration to storage services',
            'Selecting the appropriate storage tier',
            'Selecting the correct data lifecycle for storage',
            'Selecting the most cost-effective storage service for a workload',
          ],
          serviceSlugs: [
            's3',
            's3-glacier',
            'ebs',
            'efs',
            'fsx',
            'backup',
            'storage-gateway',
            'datasync',
            'snow-family',
            'cost-explorer',
            'budgets',
            'cost-and-usage-report',
          ],
        },
        {
          id: 'saa-4.2',
          domainId: 'saa-d4',
          code: '4.2',
          title: 'Design cost-optimized compute solutions',
          knowledge: [
            'AWS cost management service features (for example, cost allocation tags, multi-account billing)',
            'AWS cost management tools with appropriate use cases (for example, AWS Cost Explorer, AWS Budgets, AWS Cost and Usage Report)',
            'AWS global infrastructure (for example, Availability Zones, AWS Regions)',
            'AWS purchasing options (for example, Spot Instances, Reserved Instances, Savings Plans)',
            'Distributed compute strategies (for example, edge processing)',
            'Hybrid compute options (for example, AWS Outposts)',
            'Instance types, families, and sizes (for example, memory optimized, compute optimized, virtualization)',
            'Optimization of compute utilization (for example, containers, serverless computing, microservices)',
            'Scaling strategies (for example, auto scaling, hibernation)',
          ],
          skills: [
            'Determining an appropriate load balancing strategy (for example, Application Load Balancer [Layer 7] compared with Network Load Balancer [Layer 4] compared with Gateway Load Balancer)',
            'Determining appropriate scaling methods and strategies for elastic workloads (for example, horizontal compared with vertical, EC2 hibernation)',
            'Determining cost-effective AWS compute services with appropriate use cases (for example, AWS Lambda, Amazon EC2, AWS Fargate)',
            'Determining the required availability for different classes of workloads (for example, production workloads, non-production workloads)',
            'Selecting the appropriate instance family for a workload',
            'Selecting the appropriate instance size for a workload',
          ],
          serviceSlugs: [
            'ec2',
            'savings-plans',
            'spot',
            'lambda',
            'fargate',
            'ec2-auto-scaling',
            'compute-optimizer',
            'outposts',
            'elb',
            'cost-explorer',
            'trusted-advisor',
            'license-manager',
            'cost-and-usage-report',
          ],
        },
        {
          id: 'saa-4.3',
          domainId: 'saa-d4',
          code: '4.3',
          title: 'Design cost-optimized database solutions',
          knowledge: [
            'AWS cost management service features (for example, cost allocation tags, multi-account billing)',
            'AWS cost management tools with appropriate use cases (for example, AWS Cost Explorer, AWS Budgets, AWS Cost and Usage Report)',
            'Caching strategies',
            'Data retention policies',
            'Database capacity planning (for example, capacity units)',
            'Database connections and proxies',
            'Database engines with appropriate use cases (for example, heterogeneous migrations, homogeneous migrations)',
            'Database replication (for example, read replicas)',
            'Database types and services (for example, relational compared with non-relational, Amazon Aurora, Amazon DynamoDB)',
          ],
          skills: [
            'Designing appropriate backup and retention policies (for example, snapshot frequency)',
            'Determining an appropriate database engine (for example, MySQL compared with PostgreSQL)',
            'Determining cost-effective AWS database services with appropriate use cases (for example, DynamoDB compared with Amazon RDS, serverless)',
            'Determining cost-effective AWS database types (for example, time series format, columnar format)',
            'Migrating database schemas and data to different locations and/or different database engines',
          ],
          serviceSlugs: [
            'rds',
            'aurora',
            'aurora-serverless',
            'dynamodb',
            'elasticache',
            'redshift',
            'dms',
            'rds-proxy',
            'backup',
          ],
        },
        {
          id: 'saa-4.4',
          domainId: 'saa-d4',
          code: '4.4',
          title: 'Design cost-optimized network architectures',
          knowledge: [
            'AWS cost management service features (for example, cost allocation tags, multi-account billing)',
            'AWS cost management tools with appropriate use cases (for example, AWS Cost Explorer, AWS Budgets, AWS Cost and Usage Report)',
            'Load balancing concepts (for example, Application Load Balancer)',
            'NAT gateways (for example, NAT instance costs compared with NAT gateway costs)',
            'Network connectivity (for example, private lines, dedicated lines, VPNs)',
            'Network routing, topology, and peering (for example, AWS Transit Gateway, VPC peering)',
            'Network services with appropriate use cases (for example, DNS)',
          ],
          skills: [
            'Configuring appropriate NAT gateway types for a network (for example, a single shared NAT gateway compared with NAT gateways for each Availability Zone)',
            'Configuring appropriate network connections (for example, AWS Direct Connect compared with VPN compared with internet)',
            'Configuring appropriate network routes to minimize network transfer costs (for example, Region to Region, Availability Zone to Availability Zone, private to public, AWS Global Accelerator, VPC endpoints)',
            'Determining strategic needs for content delivery networks (CDNs) and edge caching',
            'Reviewing existing workloads for network optimizations',
            'Selecting an appropriate throttling strategy',
            'Selecting the appropriate bandwidth allocation for a network device (for example, a single VPN compared with multiple VPNs, Direct Connect speed)',
          ],
          serviceSlugs: [
            'vpc',
            'nat-gateway',
            'privatelink',
            'vpc-peering',
            'transit-gateway',
            'direct-connect',
            'site-to-site-vpn',
            'cloudfront',
            'route53',
            'global-accelerator',
            'elb',
          ],
        },
      ],
    },
  ],
}
