import type { Question } from '../schema'

/**
 * Domain 2: Security — 26% of DVA-C02. Where SAA asks which service enforces a
 * boundary, DVA asks which call retrieves the secret, which role the code is
 * running as, and what the error says when it is the wrong one.
 */
export const dvaD2Questions: Question[] = [
  /* ── Domain 2: Security (26%) ─────────────────────────────────────────── */
  {
    id: 'dva-d2-001',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cognito'],
    stem: 'A mobile app must let users sign in with email and password, then upload files directly to S3 using scoped AWS credentials. Which Cognito components are needed?',
    options: [
      { id: 'A', text: 'A user pool for authentication and an identity pool to exchange the resulting token for temporary AWS credentials.', correct: true, why: 'The user pool is the directory that authenticates; the identity pool calls STS to convert that token into scoped AWS credentials the client can use against S3.' },
      { id: 'B', text: 'A user pool only — its tokens can be used directly as AWS credentials.', correct: false, why: 'A user pool issues JWTs for your application, not SigV4 credentials for AWS APIs.' },
      { id: 'C', text: 'An identity pool only, with users created inside it.', correct: false, why: 'Identity pools do not store users or handle sign-in; they federate an existing identity.' },
      { id: 'D', text: 'A user pool plus an IAM user per application user.', correct: false, why: 'IAM users are for AWS principals, never for application customers.' },
    ],
    explanation:
      'User pool = who you are. Identity pool = what AWS credentials you get. Questions needing both sign-in and direct AWS access need both.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html',
  },
  {
    id: 'dva-d2-002',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kms'],
    stem: 'An application must encrypt 50 MB files before storing them in S3, using a key managed in KMS. What is the correct approach?',
    options: [
      { id: 'A', text: 'Envelope encryption: call GenerateDataKey, encrypt the file locally with the plaintext data key, and store the encrypted data key alongside the ciphertext.', correct: true, why: 'KMS can only encrypt up to 4 KB directly. Envelope encryption is the designed pattern, and KMS never sees the bulk data.' },
      { id: 'B', text: 'Call kms:Encrypt with the file contents as the plaintext parameter.', correct: false, why: 'The Encrypt API rejects payloads over 4 KB, so a 50 MB file cannot be passed to it.' },
      { id: 'C', text: 'Split the file into 4 KB chunks and call kms:Encrypt on each.', correct: false, why: 'Technically possible and completely impractical — 12,800 API calls per file, and reassembly complexity for no benefit.' },
      { id: 'D', text: 'Store the KMS key material in the application and encrypt locally.', correct: false, why: 'KMS key material never leaves KMS. That is the security property the service exists to provide.' },
    ],
    explanation:
      'The 4 KB limit is why envelope encryption exists. SSE-KMS on S3 does this for you; client-side encryption means doing it explicitly.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html',
  },
  {
    id: 'dva-d2-003',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['secrets-manager', 'lambda'],
    stem: 'A Lambda function currently reads a database password from a plaintext environment variable. Security requires that the credential be encrypted at rest, rotated automatically, and not visible to anyone who can view the function configuration. What should be used?',
    options: [
      { id: 'A', text: 'Store the credential in AWS Secrets Manager with rotation enabled, and retrieve it at run time using the execution role.', correct: true, why: 'It is encrypted with KMS, rotated on a schedule, and never appears in the function configuration where anyone with lambda:GetFunction could read it.' },
      { id: 'B', text: 'Encrypt the environment variable with a KMS key and decrypt it in the handler.', correct: false, why: 'Better than plaintext, but there is still no rotation, and the ciphertext remains in the function configuration.' },
      { id: 'C', text: 'Store it in an SSM Parameter Store String parameter.', correct: false, why: 'A String parameter is not encrypted at all. SecureString would encrypt but still would not rotate.' },
      { id: 'D', text: 'Pass the credential in the event payload from the caller.', correct: false, why: 'It moves the secret into logs and traces, which is considerably worse.' },
    ],
    explanation:
      'Rotation is the discriminator. Cache the retrieved secret outside the handler so you are not calling the API on every invocation.',
    source: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html',
  },
  {
    id: 'dva-d2-004',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'cognito', 'lambda'],
    stem: 'An API must be authorised using a third-party OIDC provider\'s JWTs, with custom logic that checks a claim against a DynamoDB allow-list. Which API Gateway authoriser fits?',
    options: [
      { id: 'A', text: 'A Lambda authoriser, which can validate the token and run arbitrary authorisation logic.', correct: true, why: 'Custom logic beyond token validation — such as a database lookup — is precisely what a Lambda authoriser is for, and its result can be cached.' },
      { id: 'B', text: 'A Cognito user pool authoriser.', correct: false, why: 'That validates tokens issued by a Cognito user pool, not a third-party provider, and cannot run custom logic.' },
      { id: 'C', text: 'IAM authorisation with SigV4 signing.', correct: false, why: 'That authenticates AWS principals, not application users holding OIDC tokens.' },
      { id: 'D', text: 'A resource policy on the API restricting source IPs.', correct: false, why: 'Network-level restriction, unrelated to token-based authorisation.' },
    ],
    explanation:
      'Cognito token → Cognito authoriser. Third-party token or custom logic → Lambda authoriser. AWS principal → IAM.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html',
  },
  {
    id: 'dva-d2-005',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kms', 's3'],
    stem: 'Account A must let a role in Account B decrypt objects in an S3 bucket encrypted with a customer managed KMS key in Account A. What must be configured?',
    options: [
      { id: 'A', text: 'The bucket policy must allow the Account B role, the KMS key policy must allow it kms:Decrypt, and Account B\'s identity policy must allow both actions.', correct: true, why: 'Three policies must all agree: the resource policy, the key policy, and the caller\'s identity policy. Missing the key policy is the usual failure.' },
      { id: 'B', text: 'Only the bucket policy needs to allow the Account B role.', correct: false, why: 'The object cannot be decrypted without the key policy also permitting the role.' },
      { id: 'C', text: 'Only Account B\'s identity policy needs s3:GetObject and kms:Decrypt.', correct: false, why: 'Cross-account access needs the resource side to allow it too — an identity policy alone cannot reach into another account.' },
      { id: 'D', text: 'The key must be converted to an AWS managed key so it can be shared.', correct: false, why: 'AWS managed keys cannot be shared cross-account at all. Only customer managed keys can.' },
    ],
    explanation:
      'Cross-account plus SSE-KMS means three policies. The key policy is authoritative and is the one people forget.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html',
  },
  {
    id: 'dva-d2-006',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sts', 'iam'],
    stem: 'An application running on ECS Fargate must call an API in another AWS account. What is the correct approach?',
    options: [
      { id: 'A', text: 'Have the task role call sts:AssumeRole on a role in the target account whose trust policy allows the task role.', correct: true, why: 'Role assumption yields temporary credentials scoped to the target account, with both sides explicitly configured.' },
      { id: 'B', text: 'Store an IAM user\'s access keys for the target account in the task definition environment variables.', correct: false, why: 'Long-lived credentials visible to anyone who can describe the task definition.' },
      { id: 'C', text: 'Add the target account to the task execution role\'s policy.', correct: false, why: 'The execution role pulls images and writes logs; it is not the application\'s identity, and cross-account needs the target side too.' },
      { id: 'D', text: 'Enable cross-account access in the ECS cluster settings.', correct: false, why: 'No such setting exists.' },
    ],
    explanation:
      'Also worth knowing the ECS pair: the *execution* role pulls the image and writes logs; the *task* role is what your code uses.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html',
  },

  {
    id: 'dva-d2-007',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['iam', 's3', 'lambda'],
    stem: 'A Lambda execution role grants s3:GetObject on arn:aws:s3:::reports/*. The bucket policy contains an explicit Deny for that action unless aws:SourceVpce matches a specific VPC endpoint. The function is not in a VPC. What happens?',
    options: [
      { id: 'A', text: 'The call is denied, because an explicit Deny in any applicable policy overrides every Allow.', correct: true, why: 'Evaluation order is: explicit Deny wins, then an Allow is required from somewhere. The condition is unmet, so the Deny applies and nothing can override it.' },
      { id: 'B', text: 'The call succeeds, because the identity policy grants the action.', correct: false, why: 'For same-account access an Allow in either policy is sufficient — but only in the absence of an explicit Deny, which this bucket policy supplies.' },
      { id: 'C', text: 'The call succeeds, because a resource policy cannot restrict a service role.', correct: false, why: 'Bucket policies apply to every principal, including service-assumed roles.' },
      { id: 'D', text: 'The call is denied only if the role also lacks s3:ListBucket.', correct: false, why: 'ListBucket governs listing keys. It is irrelevant to a GetObject decision.' },
    ],
    explanation:
      'Memorise the order: explicit Deny, then SCP boundary, then permissions boundary, then session policy, then Allow. An exam question that mentions a Deny anywhere has already told you the answer.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_evaluation-logic.html',
  },
  {
    id: 'dva-d2-008',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cognito'],
    stem: 'A single-page web application signs users in through the Cognito hosted UI. Security review rejects the current implicit-grant configuration because the access token appears in the browser URL. Which flow should replace it?',
    options: [
      { id: 'A', text: 'Authorization code grant with PKCE, exchanging the code for tokens from the app.', correct: true, why: 'The code grant keeps tokens out of the redirect URL, and PKCE lets a public client complete the exchange safely without a client secret.' },
      { id: 'B', text: 'Authorization code grant with a client secret embedded in the JavaScript bundle.', correct: false, why: 'A secret shipped to the browser is not a secret. Public clients must use PKCE instead.' },
      { id: 'C', text: 'Client credentials grant.', correct: false, why: 'That flow is for machine-to-machine access with no user, so it cannot authenticate a person.' },
      { id: 'D', text: 'Resource owner password grant, collecting credentials in the app\'s own form.', correct: false, why: 'It puts the user password through your application and loses hosted-UI features such as MFA and federation.' },
    ],
    explanation:
      'Public clients — browsers and mobile apps — use the authorization code grant with PKCE. Confidential server-side clients may use a client secret. Implicit grant is deprecated.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/federation-endpoints-oauth-grants.html',
  },
  {
    id: 'dva-d2-009',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'multi',
    difficulty: 3,
    serviceSlugs: ['ecs', 'ecr', 'iam'],
    stem: 'An ECS task on Fargate must pull its image from a private ECR repository and, once running, write to a DynamoDB table. Which two role assignments are required? (Choose two.)',
    options: [
      { id: 'A', text: 'A task execution role with permission to pull from ECR and write task logs.', correct: true, why: 'The execution role is used by the ECS agent — the infrastructure — to pull images and create log streams before the container starts.' },
      { id: 'B', text: 'A task role with permission to write to the DynamoDB table.', correct: true, why: 'The task role is what the application code inside the container assumes, so it carries the permissions the code needs at runtime.' },
      { id: 'C', text: 'An EC2 instance profile with both sets of permissions.', correct: false, why: 'Fargate has no instance you own, so there is no instance profile to attach.' },
      { id: 'D', text: 'Access keys for an IAM user, injected as container environment variables.', correct: false, why: 'Long-lived keys in environment variables are exactly what task roles exist to eliminate.' },
      { id: 'E', text: 'A service-linked role for Amazon ECS granting DynamoDB access.', correct: false, why: 'The service-linked role lets ECS manage load balancers and network interfaces on your behalf. It is not a place to grant application permissions.' },
    ],
    explanation:
      'Two roles, two audiences: execution role for the platform (pull image, ship logs, read secrets for injection), task role for your code. Mixing them up is a standard DVA distractor.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html',
  },
  {
    id: 'dva-d2-010',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'kms', 'cloudtrail'],
    stem: 'A compliance rule requires that every decryption of objects in an S3 bucket be attributable to a principal in an audit log, and that the key be rotatable on the team\'s own schedule. Which server-side encryption option meets both requirements?',
    options: [
      { id: 'A', text: 'SSE-KMS with a customer managed key.', correct: true, why: 'Every Decrypt call against the key is a CloudTrail event naming the principal, and a customer managed key can be rotated on demand or annually.' },
      { id: 'B', text: 'SSE-S3 with the Amazon S3 managed key.', correct: false, why: 'It encrypts at rest with no configuration, but there is no per-request audit trail and no key you can rotate.' },
      { id: 'C', text: 'SSE-KMS with an AWS managed key (aws/s3).', correct: false, why: 'It produces CloudTrail events but the rotation schedule is fixed by AWS and the key policy cannot be edited.' },
      { id: 'D', text: 'SSE-C, with the application supplying the key on every request.', correct: false, why: 'You keep full control but also full responsibility for storage and rotation, and KMS logs nothing because KMS is not involved.' },
    ],
    explanation:
      '"Who decrypted what, and when" plus "we control rotation" means a customer managed KMS key. Consider S3 Bucket Keys alongside it to cut KMS request costs on high-volume buckets.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html',
  },
  {
    id: 'dva-d2-011',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['kms', 'lambda'],
    stem: 'A batch job running under a role in another account needs to decrypt with a customer managed KMS key for the duration of one nightly run, and the key policy must not be edited for every such job. What should be used?',
    options: [
      { id: 'A', text: 'A KMS grant scoped to the grantee principal and the kms:Decrypt operation, retired when the job finishes.', correct: true, why: 'Grants are the programmatic, temporary alternative to editing a key policy, and they can be retired or revoked when no longer needed.' },
      { id: 'B', text: 'A new key policy statement naming the external role, removed the next morning.', correct: false, why: 'It works but is exactly the churn the question rules out, and a forgotten statement is a standing grant of decrypt.' },
      { id: 'C', text: 'A key alias pointing at the key, shared with the other account.', correct: false, why: 'An alias is a friendly name. It conveys no permission at all.' },
      { id: 'D', text: 'Enabling automatic key rotation.', correct: false, why: 'Rotation changes the backing key material. It is unrelated to who may use the key.' },
    ],
    explanation:
      'Key policy for durable access, grants for temporary and programmatic access. Grants also underpin how AWS services obtain permission for encryption on your behalf.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/grants.html',
  },
  {
    id: 'dva-d2-012',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['rds', 'acm'],
    stem: 'An auditor finds that some application instances connect to Amazon RDS for PostgreSQL without TLS. The team wants connections without TLS to be impossible, not merely discouraged. What should be done?',
    options: [
      { id: 'A', text: 'Set rds.force_ssl to 1 in the DB parameter group and have clients trust the Amazon RDS certificate authority bundle.', correct: true, why: 'Forcing SSL at the engine level makes the server reject plaintext connections, so client misconfiguration fails loudly instead of silently downgrading.' },
      { id: 'B', text: 'Enable encryption at rest with KMS on the instance.', correct: false, why: 'At-rest encryption protects stored data. It has no effect on the wire protocol.' },
      { id: 'C', text: 'Move the database into a private subnet with a restrictive security group.', correct: false, why: 'Network isolation limits who can connect, not whether the connection is encrypted.' },
      { id: 'D', text: 'Issue a certificate from AWS Certificate Manager and install it on the database.', correct: false, why: 'RDS supplies and rotates its own server certificate; you cannot install an ACM public certificate on it.' },
    ],
    explanation:
      'In transit and at rest are separate controls with separate switches. For RDS, the in-transit control is the engine parameter — rds.force_ssl for PostgreSQL, require_secure_transport for MySQL.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html',
  },
  {
    id: 'dva-d2-013',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['systems-manager', 'secrets-manager'],
    stem: 'A team must store about 4,000 non-secret configuration values — feature flags, endpoint URLs, timeouts — with version history and hierarchical paths, at the lowest possible cost. What should they use?',
    options: [
      { id: 'A', text: 'Systems Manager Parameter Store standard parameters.', correct: true, why: 'Standard parameters are free, versioned, support hierarchical paths and GetParametersByPath, and allow 10,000 per account per Region — comfortably covering 4,000 values.' },
      { id: 'B', text: 'AWS Secrets Manager, one secret per value.', correct: false, why: 'It would work, but it charges per secret per month plus API calls for data that is not secret and needs no rotation.' },
      { id: 'C', text: 'Lambda environment variables on each consuming function.', correct: false, why: 'Configuration is then duplicated per function, requires a deployment to change, and hits the 4 KB total environment variable limit.' },
      { id: 'D', text: 'A DynamoDB table read at start-up.', correct: false, why: 'It is buildable but you are re-implementing versioning, hierarchy and access control that Parameter Store already provides.' },
    ],
    explanation:
      'Parameter Store for configuration, including secrets you rotate yourself with SecureString. Secrets Manager when you want managed rotation, cross-account resource policies, or generated passwords — and you accept the per-secret charge.',
    source: 'https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html',
  },
  {
    id: 'dva-d2-014',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['sdk', 'iam', 'ec2'],
    stem: 'An application on EC2 currently loads access keys from a config file committed to the repository. What is the correct replacement?',
    options: [
      { id: 'A', text: 'Attach an instance profile with the needed permissions and let the SDK default credential provider chain retrieve temporary credentials from the instance metadata service.', correct: true, why: 'Role-based temporary credentials are rotated automatically and never appear in source, and the SDK finds them with no code change.' },
      { id: 'B', text: 'Move the keys into an encrypted environment variable on the instance.', correct: false, why: 'It hides the keys from the repository but they remain long-lived credentials that someone must rotate and that leak with any process dump.' },
      { id: 'C', text: 'Store the keys in Secrets Manager and fetch them at start-up.', correct: false, why: 'Better than a config file, but a role removes the credential entirely rather than relocating it — and fetching the secret itself needs credentials.' },
      { id: 'D', text: 'Add the config file to .gitignore and rotate the keys quarterly.', correct: false, why: 'It reduces exposure without changing the fact that a static key exists to be stolen.' },
    ],
    explanation:
      'The credential provider chain order — environment, shared config, container credentials, then IMDS — is worth knowing. The principle behind it is the exam answer: roles, never keys.',
    source: 'https://docs.aws.amazon.com/sdkref/latest/guide/standardized-credentials.html',
  },
  {
    id: 'dva-d2-015',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'iam'],
    stem: 'An internal REST API must be callable only by two specific IAM roles in the same organisation, with no user-facing sign-in. Which combination is correct?',
    options: [
      { id: 'A', text: 'IAM authorisation on the method, callers signing requests with SigV4, plus a resource policy restricting the allowed principals.', correct: true, why: 'IAM auth validates the signature and identity, and the resource policy pins access to the two roles — defence in depth with no user pool involved.' },
      { id: 'B', text: 'An API key per calling service, distributed with the client configuration.', correct: false, why: 'API keys identify a caller for usage plans and throttling. AWS documentation is explicit that they are not an authentication mechanism.' },
      { id: 'C', text: 'A Cognito user pool authoriser with a machine user in the pool.', correct: false, why: 'It introduces a user directory for callers that already have IAM identities.' },
      { id: 'D', text: 'A Lambda authoriser that checks a shared bearer token from Secrets Manager.', correct: false, why: 'It works but re-implements authentication, adds latency and creates a shared secret where SigV4 needs none.' },
    ],
    explanation:
      'Service-to-service inside AWS means SigV4 with IAM authorisation. API keys are for metering, not identity — that distinction is tested directly.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html',
  },
  {
    id: 'dva-d2-016',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb', 'kms'],
    stem: 'A table stores customer records. Regulation requires that a national identifier field be unreadable to anyone with only DynamoDB read permission, including database administrators, while other attributes stay queryable. What should be implemented?',
    options: [
      { id: 'A', text: 'Client-side encryption of that attribute with the AWS Database Encryption SDK for DynamoDB, so the ciphertext is what the table stores.', correct: true, why: 'Encrypting in the application means a reader with only table access sees ciphertext — separating data access from key access, which is the requirement.' },
      { id: 'B', text: 'Rely on DynamoDB encryption at rest with a customer managed key.', correct: false, why: 'At-rest encryption is transparent: any principal allowed to read the table gets plaintext back. It protects the storage medium, not the reader.' },
      { id: 'C', text: 'Move the field to a separate table with a restrictive resource policy.', correct: false, why: 'It narrows who can read the field, but the value is still stored and returned in plaintext to whoever can read that table.' },
      { id: 'D', text: 'Use a fine-grained access policy with dynamodb:Attributes to hide the field.', correct: false, why: 'That condition key can restrict which attributes a request may touch, but it does not protect the value from a principal whose policy permits it.' },
    ],
    explanation:
      'At-rest encryption defends against someone stealing the disk. Client-side encryption defends against someone with legitimate database access. When a question says "including administrators", it is asking for client-side.',
    source: 'https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/what-is-database-encryption-sdk.html',
  },
  {
    id: 'dva-d2-017',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cognito', 'api-gateway'],
    stem: 'An API authorises requests from the tenant_id claim in a Cognito ID token. The value lives in a DynamoDB profile table, not in the user pool. The team wants it present in every issued token without changing the API. What should be configured?',
    options: [
      { id: 'A', text: 'A pre token generation Lambda trigger on the user pool that adds tenant_id as a custom claim.', correct: true, why: 'That trigger runs during token issuance and exists precisely to add, modify or suppress claims, so every token carries the value.' },
      { id: 'B', text: 'A post authentication Lambda trigger that writes tenant_id back to the user pool.', correct: false, why: 'It fires after the token has already been issued, so the current token still lacks the claim.' },
      { id: 'C', text: 'A custom attribute on the user pool, populated at sign-up.', correct: false, why: 'It would appear in the token but duplicates data that lives in DynamoDB and goes stale when tenancy changes.' },
      { id: 'D', text: 'A Lambda authoriser on API Gateway that looks up tenant_id per request.', correct: false, why: 'It resolves the value but adds a lookup to every call and changes the API configuration, which the question rules out.' },
    ],
    explanation:
      'Know the Cognito triggers by when they fire: pre sign-up, pre authentication, post authentication, pre token generation, migrate user, custom message. Claim shaping is always pre token generation.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html',
  },
  {
    id: 'dva-d2-018',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cognito', 's3'],
    stem: 'A photo app must let visitors browse a public gallery in S3 without signing in, then upload only after signing in. Both paths need AWS credentials scoped differently.',
    options: [
      { id: 'A', text: 'A Cognito identity pool with unauthenticated identities enabled, mapping the guest role to read-only and the authenticated role to read and write.', correct: true, why: 'Identity pools vend temporary AWS credentials for both guests and signed-in users, with a separate IAM role for each — exactly two scopes from one mechanism.' },
      { id: 'B', text: 'A public bucket policy for browsing and a Cognito user pool for uploads.', correct: false, why: 'It makes the gallery world-readable outside any policy you control, and mixes two unrelated access models.' },
      { id: 'C', text: 'A user pool with a guest user account whose credentials ship in the app.', correct: false, why: 'A shared credential in a distributed app is a leaked credential, and it cannot be revoked per user.' },
      { id: 'D', text: 'An IAM user with read-only keys embedded in the client.', correct: false, why: 'Long-lived keys in a client application, which identity pools exist to avoid.' },
    ],
    explanation:
      'User pool authenticates people and issues JWTs. Identity pool exchanges an identity — including no identity at all — for temporary AWS credentials tied to an IAM role. Guest access is an identity pool feature.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html',
  },
  {
    id: 'dva-d2-019',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cognito'],
    stem: 'Mobile users are forced to sign in again every hour, which the product team considers unacceptable. The app currently stores only the ID and access tokens.',
    options: [
      { id: 'A', text: 'Store the refresh token securely and exchange it for new ID and access tokens — refresh token validity is configurable from an hour up to 10 years.', correct: true, why: 'ID and access tokens default to one hour; the refresh token is what maintains a long session, so discarding it forces re-authentication as soon as they expire.' },
      { id: 'B', text: 'Increase the ID token validity to 24 hours in the app client settings.', correct: false, why: 'Access and ID token validity is configurable between 5 minutes and 24 hours in current Cognito, but relying on long-lived bearer tokens weakens revocation — the refresh token is the intended mechanism.' },
      { id: 'C', text: 'Cache the user\'s password in the device keychain and re-authenticate silently.', correct: false, why: 'Storing a password to replay it is precisely what token-based authentication removes.' },
      { id: 'D', text: 'Switch the app client to the client credentials flow.', correct: false, why: 'That flow has no user identity, so it cannot represent a signed-in person.' },
    ],
    explanation:
      'Three Cognito tokens: ID (who the user is, for your app), access (what they may call, for APIs and scopes), refresh (to get new ones). Session length is a refresh-token question.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html',
  },
  {
    id: 'dva-d2-020',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['sts', 'iam'],
    stem: 'A batch process assumes a role and runs for up to four hours. It fails after one hour with an expired-credentials error, even though the code requests DurationSeconds of 14400.',
    options: [
      { id: 'A', text: 'The role\'s MaxSessionDuration is one hour, which caps the requested duration — raise it, or refresh the credentials before expiry.', correct: true, why: 'AssumeRole cannot exceed the role\'s MaxSessionDuration setting, which defaults to one hour, so the request is silently capped or rejected.' },
      { id: 'B', text: 'Temporary credentials from STS can never exceed one hour.', correct: false, why: 'AssumeRole supports up to 12 hours subject to MaxSessionDuration; the one-hour ceiling applies to role chaining and to GetFederationToken differently.' },
      { id: 'C', text: 'The session policy must grant sts:AssumeRole to itself.', correct: false, why: 'That is unrelated to session lifetime.' },
      { id: 'D', text: 'The instance profile must be replaced with an IAM user for long-running jobs.', correct: false, why: 'Long-lived keys as a workaround for credential refresh is a step backwards; SDKs refresh role credentials automatically.' },
    ],
    explanation:
      'Two limits to remember: MaxSessionDuration on the role (up to 12 hours) caps what AssumeRole grants, and role chaining is always capped at one hour regardless.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html',
  },
  {
    id: 'dva-d2-021',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cognito', 's3', 'iam'],
    stem: 'Users of a mobile app receive credentials from a Cognito identity pool and must be able to read and write only under their own prefix in a shared bucket, without a policy per user.',
    options: [
      { id: 'A', text: 'One IAM role whose policy uses the ${cognito-identity.amazonaws.com:sub} policy variable in the resource ARN.', correct: true, why: 'The policy variable is substituted with the caller\'s identity id at evaluation time, so a single policy isolates every user.' },
      { id: 'B', text: 'A role per user, created at sign-up by a Lambda trigger.', correct: false, why: 'IAM roles per user hits account quotas quickly and creates an unmanageable estate.' },
      { id: 'C', text: 'A bucket policy listing each user\'s prefix.', correct: false, why: 'It grows with every sign-up and bucket policies have a 20 KB size limit.' },
      { id: 'D', text: 'A Lambda function that proxies every read and write after checking the prefix.', correct: false, why: 'It enforces the rule and puts every byte through a function, which is what direct credentials avoid.' },
    ],
    explanation:
      'Policy variables — ${aws:userid}, ${aws:username}, ${cognito-identity.amazonaws.com:sub} — turn one policy into per-principal isolation. Whenever a question says "without a policy per user", look for them.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_variables.html',
  },
  {
    id: 'dva-d2-022',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda', 'iam', 's3'],
    stem: 'A function is invoked by S3 event notifications from a bucket in the same account. A security review asks that no other bucket, and no other account, be able to invoke it.',
    options: [
      { id: 'A', text: 'A resource-based policy on the function allowing s3.amazonaws.com with a SourceArn condition for that bucket and a SourceAccount condition for the account id.', correct: true, why: 'Both conditions together close the confused-deputy gap: SourceArn pins the specific bucket and SourceAccount pins ownership, since bucket names are global.' },
      { id: 'B', text: 'An execution role trust policy naming the bucket.', correct: false, why: 'The execution role governs what the function may do, not who may invoke it.' },
      { id: 'C', text: 'A bucket policy allowing lambda:InvokeFunction.', correct: false, why: 'Invoke permission is granted on the function, not on the bucket.' },
      { id: 'D', text: 'Enabling Block Public Access on the bucket.', correct: false, why: 'It hardens the bucket and does nothing about who can invoke the function.' },
    ],
    explanation:
      'Two policies per function: the execution role (what it can do) and the resource-based policy (who can invoke it). SourceArn plus SourceAccount is the standard confused-deputy defence for any service principal.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html',
  },
  {
    id: 'dva-d2-023',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda'],
    stem: 'A Lambda authoriser adds 120 ms to every request, and traces show it is called for each of the many requests a client makes with the same bearer token.',
    options: [
      { id: 'A', text: 'Enable authoriser result caching with a TTL, and set the identity source to the token header so the cache key is the token.', correct: true, why: 'Caching keyed on the identity source reuses the policy for repeat requests with the same token, removing the authoriser call for the TTL window.' },
      { id: 'B', text: 'Increase the authoriser function memory to reduce its duration.', correct: false, why: 'It shaves some milliseconds and still runs the function on every request.' },
      { id: 'C', text: 'Switch to a request-parameter authoriser with no identity source.', correct: false, why: 'Without an identity source there is no cache key, so caching is disabled — the opposite of what is needed.' },
      { id: 'D', text: 'Move the authorisation check into the backend function.', correct: false, why: 'It removes one hop by pushing authorisation into business logic, losing the separation and the reusable policy.' },
    ],
    explanation:
      'Authoriser caching is TTL-based and keyed on the identity source, up to one hour. If the identity source is missing or too variable, the cache never hits — that is the usual reason it appears not to work.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html',
  },
  {
    id: 'dva-d2-024',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cognito', 'api-gateway'],
    stem: 'A partner\'s backend service — not a person — must call two of the six operations on an API. The team wants scoped, expiring tokens issued by their existing Cognito user pool.',
    options: [
      { id: 'A', text: 'Define a resource server with custom scopes, give the partner an app client using the client credentials flow, and check the scopes with a Cognito authoriser.', correct: true, why: 'Client credentials is the machine-to-machine flow, and resource server scopes are how a Cognito access token is limited to specific operations.' },
      { id: 'B', text: 'Create a Cognito user representing the partner and use the password flow.', correct: false, why: 'Modelling a service as a person means a password to rotate and no scope mechanism.' },
      { id: 'C', text: 'Issue the partner an API key with a usage plan.', correct: false, why: 'API keys meter and throttle; they are not authorisation and carry no scopes or expiry.' },
      { id: 'D', text: 'Give the partner an IAM role to assume and use SigV4.', correct: false, why: 'A legitimate alternative that abandons the existing user pool the question says to use, and requires the partner to hold AWS credentials.' },
    ],
    explanation:
      'Client credentials plus resource server scopes is the Cognito answer for service-to-service. Scopes appear in the access token and can be enforced per method.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-define-resource-servers.html',
  },
  {
    id: 'dva-d2-025',
    families: ['dva'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['iam', 'cloudtrail'],
    stem: 'A service role was granted broad permissions during development. The team must reduce it to only what the application actually used over the last 90 days, with the least guesswork.',
    options: [
      { id: 'A', text: 'Generate a policy from CloudTrail activity with IAM Access Analyzer, then review and apply it.', correct: true, why: 'Access Analyzer reads the trail for that principal and proposes a policy containing only observed actions, which is evidence rather than guesswork.' },
      { id: 'B', text: 'Remove permissions one at a time and wait for something to break.', correct: false, why: 'It discovers requirements through production incidents.' },
      { id: 'C', text: 'Attach a permissions boundary allowing read-only actions.', correct: false, why: 'A boundary caps the role without telling you what it needs, and read-only would break any write path.' },
      { id: 'D', text: 'Read the Last Accessed information for the role\'s services.', correct: false, why: 'A genuinely useful signal that stops at service level, not the specific actions and resources a policy needs.' },
    ],
    explanation:
      'Three least-privilege tools: Access Analyzer policy generation (build a policy from observed activity), Last Accessed data (find unused services), and unused-access findings (surface stale roles and permissions).',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-policy-generation.html',
  },
  {
    id: 'dva-d2-026',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['kms'],
    stem: 'A team enables automatic annual rotation on a customer managed key. A developer asks whether objects encrypted before rotation must be re-encrypted.',
    options: [
      { id: 'A', text: 'No — KMS retains all previous key material and selects the right version by the metadata in the ciphertext, so old data decrypts unchanged.', correct: true, why: 'Rotation adds new backing material for new encrypt operations while keeping older material for decryption, and the key id and ARN do not change.' },
      { id: 'B', text: 'Yes — data must be re-encrypted with the new material or it becomes unreadable.', correct: false, why: 'That would make rotation unusable, which is why KMS keeps prior material.' },
      { id: 'C', text: 'Yes, and the ReEncrypt API must be called on every object.', correct: false, why: 'ReEncrypt exists for moving ciphertext to a different key, not for rotation of the same key.' },
      { id: 'D', text: 'No, because automatic rotation only changes the key alias.', correct: false, why: 'Aliases are unaffected; what rotates is the backing cryptographic material.' },
    ],
    explanation:
      'Automatic rotation: customer managed keys, yearly by default and configurable, transparent to callers, same key ARN. Manual rotation means a new key plus an alias update — and then old ciphertext genuinely does need ReEncrypt.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html',
  },
  {
    id: 'dva-d2-027',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['sns', 'sqs', 'kms'],
    stem: 'An SQS queue is encrypted with a customer managed KMS key. After enabling it, messages published through the subscribed SNS topic stop arriving, and no error is visible in the application.',
    options: [
      { id: 'A', text: 'The key policy must allow the SNS service principal kms:GenerateDataKey* and kms:Decrypt, because SNS encrypts the message on the queue\'s behalf.', correct: true, why: 'A service writing to an encrypted resource needs key permissions of its own, and without them the delivery fails outside the application\'s view.' },
      { id: 'B', text: 'The queue access policy must allow sns.amazonaws.com to send messages, which encryption reset.', correct: false, why: 'Enabling encryption does not alter the queue access policy, and that permission was already working before.' },
      { id: 'C', text: 'SQS queues encrypted with a customer managed key cannot receive SNS deliveries.', correct: false, why: 'They can; the key policy simply has to permit it.' },
      { id: 'D', text: 'The topic must also be encrypted with the same key.', correct: false, why: 'Topic encryption is independent and does not grant the topic access to the queue\'s key.' },
    ],
    explanation:
      'Whenever an AWS service writes to an encrypted resource on your behalf — SNS to SQS, EventBridge to SQS, S3 to an encrypted bucket — the key policy must name that service principal. It is a very common silent failure.',
    source: 'https://docs.aws.amazon.com/sns/latest/dg/sns-key-management.html',
  },
  {
    id: 'dva-d2-028',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'acm'],
    stem: 'A team is configuring a custom domain for an edge-optimised REST API in ap-southeast-1. The ACM certificate they issued in ap-southeast-1 does not appear in the selector.',
    options: [
      { id: 'A', text: 'An edge-optimised custom domain requires the certificate in us-east-1, because it is fronted by CloudFront; a regional custom domain uses a certificate in the API\'s own Region.', correct: true, why: 'Edge-optimised endpoints are CloudFront distributions, and CloudFront reads certificates only from us-east-1.' },
      { id: 'B', text: 'ACM certificates must be imported rather than issued to be used with API Gateway.', correct: false, why: 'ACM-issued certificates are fully supported and renew automatically.' },
      { id: 'C', text: 'The certificate must cover the domain with a wildcard to be selectable.', correct: false, why: 'An exact-name certificate is fine; the Region is the problem.' },
      { id: 'D', text: 'Custom domains require the certificate to be stored in IAM.', correct: false, why: 'That is a legacy path for CloudFront and not required here.' },
    ],
    explanation:
      'The us-east-1 certificate rule follows CloudFront everywhere it appears: CloudFront distributions and edge-optimised API Gateway domains. ALBs, NLBs and regional API domains use their own Region.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html',
  },
  {
    id: 'dva-d2-029',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'kms'],
    stem: 'An application writes millions of small objects a day to a bucket using SSE-KMS. KMS request charges have become a significant line on the bill, and the requirement to use a customer managed key stands.',
    options: [
      { id: 'A', text: 'Enable S3 Bucket Keys on the bucket, which lets S3 use a bucket-level key to reduce KMS requests substantially.', correct: true, why: 'Bucket Keys cut KMS request traffic by up to 99% while keeping the customer managed key as the root of trust.' },
      { id: 'B', text: 'Switch the bucket to SSE-S3.', correct: false, why: 'It removes the KMS charge and abandons the customer managed key requirement.' },
      { id: 'C', text: 'Batch the objects into larger archives before writing.', correct: false, why: 'It genuinely reduces requests and changes the data model, which the question does not invite.' },
      { id: 'D', text: 'Request a KMS request quota increase.', correct: false, why: 'A quota increase raises the ceiling and not the cost, which is the actual problem.' },
    ],
    explanation:
      'SSE-KMS charges a KMS request per object operation. S3 Bucket Keys amortise that across the bucket and are the standard fix for high-volume small-object workloads.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html',
  },
  {
    id: 'dva-d2-030',
    families: ['dva'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'kms'],
    stem: 'Application logs contain regulated data. Policy requires that the log data at rest be encrypted with a key the security team controls and can revoke.',
    options: [
      { id: 'A', text: 'Associate a customer managed KMS key with the log group, with a key policy allowing the logs service principal for that Region.', correct: true, why: 'Log groups support a customer managed key, and revoking the key\'s permissions renders the data unreadable — which is the control being asked for.' },
      { id: 'B', text: 'Rely on the default encryption CloudWatch Logs applies at rest.', correct: false, why: 'Logs are encrypted at rest by default with a service-managed key that the security team neither controls nor can revoke.' },
      { id: 'C', text: 'Export the logs to an encrypted S3 bucket and reduce log retention.', correct: false, why: 'It protects the archive and leaves the live log group under the default key.' },
      { id: 'D', text: 'Encrypt each log line in the application before writing it.', correct: false, why: 'It defeats Logs Insights, metric filters and subscription filters — the reasons for using the service.' },
    ],
    explanation:
      'The pattern repeats across services: default encryption with an AWS-owned key, optional customer managed key for control, audit and revocation. When a question stresses control or revocation, it wants the customer managed key.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html',
  },
  {
    id: 'dva-d2-031',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['secrets-manager', 'lambda'],
    stem: 'A high-traffic function fetches a database secret from Secrets Manager on every invocation. The team sees added latency and Secrets Manager API charges, but the secret must still rotate every 30 days.',
    options: [
      { id: 'A', text: 'Use the Secrets Manager caching library or the Parameters and Secrets Lambda extension, which cache the value in the execution environment with a configurable TTL.', correct: true, why: 'Caching removes the per-invocation call while the TTL bounds how long a rotated secret takes to be picked up, so rotation still works.' },
      { id: 'B', text: 'Copy the secret into an environment variable at deploy time.', correct: false, why: 'It removes the call and breaks rotation — the function keeps the value until the next deployment.' },
      { id: 'C', text: 'Fetch the secret outside the handler with no expiry.', correct: false, why: 'Better than per-invocation and a warm environment can then hold a rotated-out credential indefinitely.' },
      { id: 'D', text: 'Disable rotation and use a long-lived password.', correct: false, why: 'It trades the security requirement for latency, which is not the team\'s call to make.' },
    ],
    explanation:
      'Cache with a TTL, and handle an authentication failure by invalidating the cache and retrying once. That combination survives rotation without a call per invocation.',
    source: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache.html',
  },
  {
    id: 'dva-d2-032',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['ecs', 'secrets-manager', 'iam'],
    stem: 'An ECS task definition must supply a database password as an environment variable to the container, sourced from Secrets Manager and never visible in the task definition or the console.',
    options: [
      { id: 'A', text: 'Use the secrets block in the container definition with the secret ARN as valueFrom, and grant the task execution role secretsmanager:GetSecretValue.', correct: true, why: 'ECS resolves the secret at task start and injects it into the container environment, so only the ARN appears in the definition. The retrieval is done by the execution role.' },
      { id: 'B', text: 'Put the secret in the environment block and rely on the task definition being private.', correct: false, why: 'Values in the environment block are stored in plaintext in the task definition and shown in the console.' },
      { id: 'C', text: 'Grant the task role access and have the application fetch the secret at start-up.', correct: false, why: 'A perfectly valid alternative, and it is the application doing the work rather than the injection the question describes.' },
      { id: 'D', text: 'Bake the secret into the container image as a build argument.', correct: false, why: 'Build arguments and image layers are readable by anyone who can pull the image.' },
    ],
    explanation:
      'Secret injection is done by the task execution role, not the task role — that is the detail most often missed. It works with Secrets Manager ARNs and SSM Parameter Store parameters alike.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html',
  },
  {
    id: 'dva-d2-033',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'xray'],
    stem: 'A review finds that debug logging writes full request bodies, including card numbers and email addresses, to CloudWatch Logs. The team needs the logs for troubleshooting.',
    options: [
      { id: 'A', text: 'Redact sensitive fields before logging, and add a CloudWatch Logs data protection policy to mask any that slip through.', correct: true, why: 'Redacting at the source is the fix, and a data protection policy audits and masks known sensitive patterns as a safety net rather than a substitute.' },
      { id: 'B', text: 'Reduce the log retention period to seven days.', correct: false, why: 'Sensitive data exposed for seven days is still exposed.' },
      { id: 'C', text: 'Restrict who can read the log group with an IAM policy.', correct: false, why: 'A necessary control that does not stop the data being collected where it should not be.' },
      { id: 'D', text: 'Move the logging to X-Ray annotations instead.', correct: false, why: 'That relocates the same sensitive values into traces, where they are indexed and searchable.' },
    ],
    explanation:
      'Managing sensitive data in application code is an explicit DVA task statement. The answer is always "do not emit it", with platform masking as defence in depth.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/mask-sensitive-log-data.html',
  },
  {
    id: 'dva-d2-034',
    families: ['dva'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda', 'kms'],
    stem: 'A function stores an API token in an environment variable. The team enables the console encryption helper with a customer managed key and asks what has actually changed.',
    options: [
      { id: 'A', text: 'The value is now ciphertext at rest and in the console, and the function must call kms:Decrypt itself at initialisation to use it.', correct: true, why: 'The encryption helper encrypts the value client-side, so the runtime receives ciphertext and the code — with kms:Decrypt permission — is responsible for decrypting it.' },
      { id: 'B', text: 'Nothing changes in the code; Lambda decrypts the variable before the handler runs.', correct: false, why: 'That describes encryption at rest with the default key, where the plaintext is transparently available. The helper is explicitly client-side.' },
      { id: 'C', text: 'The variable is now stored in Secrets Manager automatically.', correct: false, why: 'No secret is created; the value stays an environment variable.' },
      { id: 'D', text: 'The variable becomes readable only by the execution role, with no code change.', correct: false, why: 'Environment variable visibility is governed by lambda:GetFunctionConfiguration permission, which the helper does not alter.' },
    ],
    explanation:
      'Lambda encrypts environment variables at rest by default. The encryption helper adds encryption in transit and in the console, at the cost of a decrypt call in your initialisation code. Parameter Store or Secrets Manager is usually cleaner.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html',
  },
]
