import type { Question } from '../schema'

/**
 * Domain 4: Troubleshooting and Optimization — 18% of DVA-C02, and the domain
 * that reads like a support ticket. X-Ray, CloudWatch Logs Insights and the
 * capacity-unit arithmetic are what close these questions.
 */
export const dvaD4Questions: Question[] = [
  /* ── Domain 4: Troubleshooting & Optimization (18%) ───────────────────── */
  {
    id: 'dva-d4-001',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['xray'],
    stem: 'A developer needs to search X-Ray traces for a specific customer id to investigate one customer\'s slow requests. How should the id be attached to the trace?',
    options: [
      { id: 'A', text: 'As an annotation, because annotations are indexed and can be used in filter expressions.', correct: true, why: 'Annotations are indexed key–value pairs and are the only thing X-Ray can filter on. This distinction is examined directly.' },
      { id: 'B', text: 'As metadata, which stores arbitrary data on the segment.', correct: false, why: 'Metadata is attached and visible but not indexed, so it cannot be searched or filtered.' },
      { id: 'C', text: 'In the segment name.', correct: false, why: 'Segment names identify the service, and a high-cardinality name would fragment the service map.' },
      { id: 'D', text: 'In a CloudWatch Logs entry correlated by timestamp.', correct: false, why: 'That is manual correlation, not trace filtering, and timestamps are unreliable as a join key.' },
    ],
    explanation:
      'Annotations are indexed and filterable; metadata is not. If a question says "filter traces by X", the answer is an annotation.',
    source: 'https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html',
  },
  {
    id: 'dva-d4-002',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'lambda'],
    stem: 'A Lambda function must emit a custom business metric on every invocation with minimal latency and cost. What is the recommended approach?',
    options: [
      { id: 'A', text: 'Write structured logs in the CloudWatch embedded metric format, letting CloudWatch extract the metrics asynchronously.', correct: true, why: 'EMF turns a log line into a metric with no extra API call, so there is no PutMetricData latency on the invocation path and no per-call charge.' },
      { id: 'B', text: 'Call PutMetricData synchronously at the end of the handler.', correct: false, why: 'It adds an API call and its latency to every invocation, and PutMetricData is charged per call.' },
      { id: 'C', text: 'Write the metric to DynamoDB and aggregate it later with a scheduled job.', correct: false, why: 'Reinvents metric collection, with more cost, more code and more delay.' },
      { id: 'D', text: 'Enable Lambda Insights and derive the business metric from it.', correct: false, why: 'Lambda Insights provides system-level telemetry, not your application\'s business metrics.' },
    ],
    explanation:
      'EMF is the intended answer for custom metrics from Lambda: log once, get a metric, pay no per-call API cost.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format.html',
  },
  {
    id: 'dva-d4-003',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A user-facing Lambda function behind API Gateway shows p99 latency of 3 seconds due to cold starts, while p50 is 80 ms. Traffic is steady during business hours. What should be configured?',
    options: [
      { id: 'A', text: 'Provisioned concurrency sized to the business-hours baseline, optionally on a schedule.', correct: true, why: 'Provisioned concurrency keeps environments initialised so requests skip the cold start. Scheduling it to business hours avoids paying for it overnight.' },
      { id: 'B', text: 'Reserved concurrency set to the expected peak.', correct: false, why: 'Reserved concurrency guarantees and caps capacity. It does not pre-warm anything, so cold starts remain.' },
      { id: 'C', text: 'A scheduled EventBridge rule pinging the function every minute to keep it warm.', correct: false, why: 'The old workaround: it warms one environment, not the many needed under concurrency, and it is superseded by provisioned concurrency.' },
      { id: 'D', text: 'Increase the memory allocation to reduce initialisation time.', correct: false, why: 'More memory speeds initialisation somewhat but does not remove the cold start.' },
    ],
    explanation:
      'Cold starts are provisioned concurrency. Concurrency limits are reserved concurrency. The names are similar and the exam exploits that.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html',
  },
  {
    id: 'dva-d4-004',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch'],
    stem: 'An operations team must be alerted whenever the text "OutOfMemoryError" appears in an application\'s CloudWatch log group. What should be configured?',
    options: [
      { id: 'A', text: 'A metric filter on the log group that increments a custom metric, with a CloudWatch alarm on that metric.', correct: true, why: 'Metric filters turn a log pattern into a metric, and alarms act on metrics. This is the standard log-to-alert path.' },
      { id: 'B', text: 'A CloudWatch alarm directly on the log group.', correct: false, why: 'Alarms evaluate metrics, not log content. A metric filter is the required intermediate step.' },
      { id: 'C', text: 'A Logs Insights query on a schedule, emailing the results.', correct: false, why: 'Possible with extra machinery, but it polls rather than reacting and there is a native mechanism.' },
      { id: 'D', text: 'A CloudTrail trail filtered for the error string.', correct: false, why: 'CloudTrail records API calls, not application log output.' },
    ],
    explanation:
      'Log pattern → metric filter → alarm → SNS. This chain appears repeatedly, in both DVA and SAA framing.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html',
  },
  {
    id: 'dva-d4-005',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sns', 'sqs'],
    stem: 'Four SQS queues subscribe to an SNS topic, but each consumer only cares about a subset of message types. Currently every consumer reads and discards most messages. What reduces waste?',
    options: [
      { id: 'A', text: 'Subscription filter policies on each SNS subscription, so only relevant messages reach each queue.', correct: true, why: 'Filtering happens in SNS before delivery, so each queue receives only what it needs — fewer requests, less compute, less cost.' },
      { id: 'B', text: 'A separate SNS topic per message type.', correct: false, why: 'It works but multiplies topics and forces publishers to know the routing, which is what filter policies avoid.' },
      { id: 'C', text: 'A Lambda function between the topic and the queues that routes messages.', correct: false, why: 'Adds a component and its cost to do what SNS does natively.' },
      { id: 'D', text: 'Longer polling intervals on each consumer.', correct: false, why: 'It changes when messages are read, not how many irrelevant ones arrive.' },
    ],
    explanation:
      'DVA names "subscription filter policies to optimize messaging" as a skill. Filter at the source, not in the consumer.',
    source: 'https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html',
  },
  {
    id: 'dva-d4-006',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudfront', 'api-gateway'],
    stem: 'An API returns different responses depending on the Accept-Language header. Behind CloudFront, users are receiving responses in the wrong language. What should be changed?',
    options: [
      { id: 'A', text: 'Include Accept-Language in the CloudFront cache key so responses are cached per language.', correct: true, why: 'A header that changes the response must be part of the cache key, or one language\'s response is served to everyone.' },
      { id: 'B', text: 'Disable caching on the distribution entirely.', correct: false, why: 'It fixes correctness by giving up all caching benefit — an over-correction.' },
      { id: 'C', text: 'Forward all headers to the origin.', correct: false, why: 'It fixes correctness but makes almost every request a cache miss, since the key then includes highly variable headers.' },
      { id: 'D', text: 'Add a Lambda@Edge function to rewrite the response.', correct: false, why: 'Far more machinery than needed for something the cache-key policy expresses directly.' },
    ],
    explanation:
      'Anything that varies the response must be in the cache key — and nothing else should be. That balance is the whole art of CDN caching.',
    source: 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/controlling-the-cache-key.html',
  },
  {
    id: 'dva-d4-007',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway'],
    stem: 'During a marketing campaign, clients of a REST API begin receiving HTTP 429 with the message "Too Many Requests". Backend Lambda metrics show no errors and low duration. What is the cause?',
    options: [
      { id: 'A', text: 'API Gateway request throttling — the stage, method or usage plan rate and burst limits are being exceeded.', correct: true, why: '429 is the throttling response. With a healthy backend, the limit being hit is in front of it: account, stage, method or usage plan.' },
      { id: 'B', text: 'The Lambda function has reached its reserved concurrency limit.', correct: false, why: 'That also produces throttling, but it surfaces as Lambda Throttles and typically a 500-class response from the integration, and the function metrics here are clean.' },
      { id: 'C', text: 'The integration timeout of 29 seconds is being exceeded.', correct: false, why: 'That returns 504 Gateway Timeout, and duration is reported as low.' },
      { id: 'D', text: 'The Lambda response exceeds the payload limit.', correct: false, why: 'That returns 502 Bad Gateway from a malformed or oversized response.' },
    ],
    explanation:
      'Learn the API Gateway status codes as a diagnostic table: 429 throttling, 502 bad integration response, 504 integration timeout or 29-second limit, 403 authorisation or WAF, 401 missing authentication token.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html',
  },
  {
    id: 'dva-d4-008',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['xray'],
    stem: 'X-Ray costs on a high-traffic API have grown beyond budget, but the team must keep tracing every request to the /checkout path. What should be changed?',
    options: [
      { id: 'A', text: 'Add a custom sampling rule matching the checkout path at a high rate, and lower the default rule\'s reservoir and fixed rate.', correct: true, why: 'Sampling rules are evaluated by priority and match on service, method, URL path and host, so one path can be traced heavily while everything else is sampled sparsely.' },
      { id: 'B', text: 'Disable active tracing on all functions except the checkout function.', correct: false, why: 'It cuts cost but loses the surrounding trace segments, so a checkout trace no longer shows the services it called.' },
      { id: 'C', text: 'Reduce the trace retention period.', correct: false, why: 'X-Ray retains traces for 30 days and this is not configurable, so there is no such lever.' },
      { id: 'D', text: 'Send traces to CloudWatch Logs instead and query them with Logs Insights.', correct: false, why: 'Logs are not traces — you lose the service map and segment timings that made X-Ray useful here.' },
    ],
    explanation:
      'The default sampling rule is one request per second plus 5% of the remainder. Custom rules with a lower priority number win, which is how you trace a critical path heavily and the rest cheaply.',
    source: 'https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html',
  },
  {
    id: 'dva-d4-009',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'lambda'],
    stem: 'An investigation needs the p95 duration of one downstream call, broken down by customer tier, across a week of Lambda logs. The team controls the logging code. What is the most effective preparation?',
    options: [
      { id: 'A', text: 'Emit one structured JSON log line per call with duration and tier as fields, and query it with CloudWatch Logs Insights using filter, stats and pct.', correct: true, why: 'Logs Insights discovers fields in JSON automatically, so structured logging turns an ad-hoc text search into an aggregation query with percentiles and grouping.' },
      { id: 'B', text: 'Log a human-readable sentence per call and grep the exported log files.', correct: false, why: 'Unstructured text has to be re-parsed for every new question, and exporting a week of logs to work on them locally is slow and error-prone.' },
      { id: 'C', text: 'Publish a custom CloudWatch metric per customer, dimensioned by customer id.', correct: false, why: 'It gives fast percentiles but a unique dimension value per customer creates a custom metric per customer, which is expensive and hits cardinality limits.' },
      { id: 'D', text: 'Enable X-Ray active tracing and read the durations from the service map.', correct: false, why: 'Tracing is excellent for one slow request, but sampled traces cannot give a reliable p95 over a week, and the service map does not group by a business attribute.' },
    ],
    explanation:
      'Structured logs are queryable data. The rule of thumb: metrics for known questions at low cardinality, logs for unknown questions at high cardinality, traces for one request end to end.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html',
  },
  {
    id: 'dva-d4-010',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb', 'elasticache'],
    stem: 'A read-heavy DynamoDB workload needs microsecond response times for repeated reads of the same items, with the smallest possible change to application code. What should be added?',
    options: [
      { id: 'A', text: 'DynamoDB Accelerator (DAX), which the existing DynamoDB API calls can use through the DAX client.', correct: true, why: 'DAX is a write-through cache purpose-built for DynamoDB, delivers microsecond reads and is API-compatible, so the change is the client and endpoint rather than the data-access logic.' },
      { id: 'B', text: 'ElastiCache for Redis in front of the table.', correct: false, why: 'It reaches similar latency but you must write and maintain all the cache-aside and invalidation logic yourself, which is the code change being avoided.' },
      { id: 'C', text: 'Global tables in a second Region.', correct: false, why: 'Global tables address geographic latency and regional resilience, not repeated reads of hot items.' },
      { id: 'D', text: 'Switching every read to eventually consistent.', correct: false, why: 'It halves read cost and helps a little with latency, but single-digit milliseconds is not microseconds.' },
    ],
    explanation:
      'DAX for DynamoDB-only caching with no code rewrite — note it does not accelerate strongly consistent reads. ElastiCache when you need to cache anything else, or need data structures Redis provides.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html',
  },
  {
    id: 'dva-d4-011',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudtrail', 's3'],
    stem: 'An object disappeared from an S3 bucket overnight and the team must identify which principal deleted it. CloudTrail is enabled with default settings. What is true?',
    options: [
      { id: 'A', text: 'The DeleteObject call will not be in the trail — object-level activity requires data events, which are not logged by default.', correct: true, why: 'Management events are logged by default; S3 object-level calls are data events and must be enabled explicitly, at additional cost.' },
      { id: 'B', text: 'The call is in the default management event history and can be found by filtering on DeleteObject.', correct: false, why: 'Management events cover control-plane actions such as PutBucketPolicy, not per-object reads and writes.' },
      { id: 'C', text: 'S3 server access logs are enabled by default and will name the principal.', correct: false, why: 'Server access logging is off until configured, and it is a separate feature from CloudTrail.' },
      { id: 'D', text: 'The information is available from the bucket\'s CloudWatch metrics.', correct: false, why: 'Metrics give counts and volumes. They never identify a caller.' },
    ],
    explanation:
      'Management events versus data events is a recurring exam distinction. If a question needs per-object or per-item attribution — S3 objects, Lambda invocations, DynamoDB items — data events must have been switched on beforehand.',
    source: 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html',
  },
  {
    id: 'dva-d4-012',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda', 'cloudwatch'],
    stem: 'A CPU-bound Lambda function is configured with 512 MB and runs for 8 seconds. A developer proposes raising memory to 2,048 MB to cut cost. Is that plausible, and how should it be decided?',
    options: [
      { id: 'A', text: 'Yes — CPU scales with the memory setting, so a faster run can cost less despite the higher per-millisecond price. Measure across memory settings and compare cost, rather than assuming.', correct: true, why: 'Lambda allocates CPU proportionally to memory, so a CPU-bound function can finish more than four times faster at four times the memory and end up cheaper. Only measurement tells you where the curve bottoms out.' },
      { id: 'B', text: 'No — cost is duration multiplied by memory, so more memory is always more expensive.', correct: false, why: 'That is true only when duration does not improve, which is exactly what does not hold for CPU-bound work.' },
      { id: 'C', text: 'Yes, and 10,240 MB will always be cheapest for CPU-bound functions.', correct: false, why: 'Speed-up flattens once the function stops being CPU-starved, and beyond that point the extra memory is pure cost. There is no universal setting.' },
      { id: 'D', text: 'It cannot be evaluated without moving the workload to Fargate for comparison.', correct: false, why: 'The comparison is a handful of invocations per memory setting, measured from the billed duration in the logs.' },
    ],
    explanation:
      'One vCPU arrives at about 1,769 MB. Right-sizing is an empirical exercise — AWS Lambda Power Tuning is the standard tool, and the answer is often more memory for less money.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html',
  },
  {
    id: 'dva-d4-013',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['xray', 'lambda'],
    stem: 'An X-Ray service map shows the API Gateway and Lambda nodes but nothing beyond them, even though the function calls DynamoDB and an external HTTP API. Active tracing is enabled on the function.',
    options: [
      { id: 'A', text: 'The function code must be instrumented with the X-Ray SDK or ADOT so outbound SDK and HTTP calls create subsegments.', correct: true, why: 'Active tracing produces the function segment; downstream calls only appear when the client libraries are wrapped by the tracing SDK.' },
      { id: 'B', text: 'The execution role needs dynamodb:DescribeTable so X-Ray can discover the dependency.', correct: false, why: 'X-Ray does not discover dependencies by inspection — it records what the instrumented code reports.' },
      { id: 'C', text: 'DynamoDB does not support X-Ray tracing.', correct: false, why: 'DynamoDB calls appear as subsegments whenever the SDK client is instrumented.' },
      { id: 'D', text: 'The sampling rate is too low to include downstream calls.', correct: false, why: 'Sampling decides whether a whole trace is recorded, not which parts of it.' },
    ],
    explanation:
      'Tracing has two halves: the service enables the segment, your code creates the subsegments. A service map that stops at your function almost always means uninstrumented clients.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html',
  },
  {
    id: 'dva-d4-014',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'cloudwatch'],
    stem: 'A function\'s logs end with "Task timed out after 30.00 seconds" for about 2% of invocations. Duration for the rest averages 900 ms. What is the most useful next diagnostic step?',
    options: [
      { id: 'A', text: 'Instrument the downstream calls with X-Ray subsegments to find which dependency is hanging on those invocations.', correct: true, why: 'A bimodal duration distribution points at a dependency that occasionally stalls, and subsegment timings identify which one — raising the timeout would only lengthen the hang.' },
      { id: 'B', text: 'Increase the timeout to 90 seconds.', correct: false, why: 'It converts a timeout into a very slow success and hides the cause while costing three times the duration.' },
      { id: 'C', text: 'Increase the memory setting.', correct: false, why: 'Worth trying for CPU-bound work; a 2% tail against a 900 ms average is not a CPU shortage.' },
      { id: 'D', text: 'Add a retry in the caller.', correct: false, why: 'Retrying a request that hangs for 30 seconds multiplies the latency and the cost.' },
    ],
    explanation:
      'Read the REPORT line: Duration, Billed Duration, Memory Size, Max Memory Used and Init Duration. A tail that differs sharply from the median is a dependency problem, not a sizing problem.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics.html',
  },
  {
    id: 'dva-d4-015',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'A function processing large images fails intermittently with "Runtime exited with error: signal: killed" and no application stack trace. What does this indicate and how is it confirmed?',
    options: [
      { id: 'A', text: 'The function exceeded its memory allocation and was killed — compare Max Memory Used in the REPORT line with Memory Size.', correct: true, why: 'An out-of-memory kill terminates the process before any handler can log, and the REPORT line is where the evidence sits.' },
      { id: 'B', text: 'The function timed out, which is always logged this way.', correct: false, why: 'A timeout logs "Task timed out after N seconds" explicitly.' },
      { id: 'C', text: 'The execution role lacks permission for a downstream call.', correct: false, why: 'An authorisation failure raises AccessDenied inside the code, with a stack trace.' },
      { id: 'D', text: 'The deployment package exceeds the unzipped size limit.', correct: false, why: 'That fails at deployment or on cold start with a size error, not mid-invocation.' },
    ],
    explanation:
      'Three failure signatures worth recognising instantly: "Task timed out" (timeout), "signal: killed" (out of memory), and a handler exception with a stack trace (your code). They lead to three different fixes.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/troubleshooting-invocation.html',
  },
  {
    id: 'dva-d4-016',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb', 'cloudwatch'],
    stem: 'Users report intermittent errors from a service backed by DynamoDB. The team must determine whether the table is throttling and, if so, whether the base table or an index is responsible.',
    options: [
      { id: 'A', text: 'Compare ThrottledRequests and ReadThrottleEvents or WriteThrottleEvents with ConsumedCapacity, dimensioned by table and by GlobalSecondaryIndexName.', correct: true, why: 'The throttle metrics confirm throttling and the index dimension attributes it, which is exactly the two-part question asked.' },
      { id: 'B', text: 'Enable DynamoDB Streams and inspect the records.', correct: false, why: 'Streams show data changes, not rejected requests.' },
      { id: 'C', text: 'Turn on CloudTrail data events for the table.', correct: false, why: 'Data events record successful and denied API calls for audit; they are an expensive and indirect way to see capacity problems.' },
      { id: 'D', text: 'Read the SuccessfulRequestLatency metric.', correct: false, why: 'Latency describes served requests; a throttled request was not served.' },
    ],
    explanation:
      'DynamoDB metrics in diagnostic order: ThrottledRequests and the throttle-event metrics, ConsumedCapacity against provisioned, then SuccessfulRequestLatency. The GSI dimension is what stops you tuning the wrong thing.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/metrics-dimensions.html',
  },
  {
    id: 'dva-d4-017',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'cloudwatch'],
    stem: 'An operations team needs an alarm that fires when a queue\'s consumers are falling behind, rather than one that fires on any temporary spike in queue depth.',
    options: [
      { id: 'A', text: 'Alarm on ApproximateAgeOfOldestMessage, which measures how long the oldest unprocessed message has waited.', correct: true, why: 'Age captures whether the backlog is being worked through — a deep queue drained quickly is fine, an old message is not.' },
      { id: 'B', text: 'Alarm on ApproximateNumberOfMessagesVisible above a fixed threshold.', correct: false, why: 'Depth alone fires on healthy bursts and stays quiet when a slow trickle is never consumed at all.' },
      { id: 'C', text: 'Alarm on NumberOfMessagesSent.', correct: false, why: 'That measures producer activity and says nothing about consumption.' },
      { id: 'D', text: 'Alarm on NumberOfEmptyReceives.', correct: false, why: 'Empty receives indicate polling on an idle queue — the opposite condition.' },
    ],
    explanation:
      'For any queue or stream, the health signal is age, not depth: ApproximateAgeOfOldestMessage for SQS, GetRecords.IteratorAgeMilliseconds for Kinesis, IteratorAge for a Lambda event source mapping.',
    source: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-available-cloudwatch-metrics.html',
  },
  {
    id: 'dva-d4-018',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cloudwatch'],
    stem: 'An on-call rota is being paged by an error-rate alarm that fires whenever a single deployment restarts the fleet, even though the service stays healthy. The team wants a page only when errors are high and latency is also degraded.',
    options: [
      { id: 'A', text: 'A composite alarm that fires when both the error-rate and the latency alarms are in ALARM.', correct: true, why: 'Composite alarms combine child alarms with a rule expression, which is how you express "both conditions" without inventing a metric.' },
      { id: 'B', text: 'Raise the error-rate threshold until deployments stop triggering it.', correct: false, why: 'It suppresses real incidents at the same level it suppresses noise.' },
      { id: 'C', text: 'Increase the number of evaluation periods to 20.', correct: false, why: 'A blunt version of the same trade: less noise and a much slower page for a genuine outage.' },
      { id: 'D', text: 'Use a metric math expression to average error rate and latency into one metric.', correct: false, why: 'Averaging two unrelated units produces a number nobody can reason about or threshold meaningfully.' },
    ],
    explanation:
      'Composite alarms for and/or logic across signals, metric math for genuine derived metrics such as an error percentage, anomaly detection for metrics with no fixed sensible threshold.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Composite_Alarm.html',
  },
  {
    id: 'dva-d4-019',
    families: ['dva'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'xray', 'lambda'],
    stem: 'Investigating a slow request currently means pivoting by hand between the API Gateway metrics, the function logs and the X-Ray trace. The team wants one view that links them for a given request.',
    options: [
      { id: 'A', text: 'Use CloudWatch ServiceLens, which correlates traces, metrics, logs and alarms in one service map.', correct: true, why: 'ServiceLens exists precisely to join X-Ray traces to the corresponding logs and metrics, removing the manual pivot.' },
      { id: 'B', text: 'Build a CloudWatch dashboard with the three widgets side by side.', correct: false, why: 'A dashboard puts them on one page without correlating them for a specific request.' },
      { id: 'C', text: 'Export the logs to S3 and join them with Athena.', correct: false, why: 'An after-the-fact analytical route, not an investigation view.' },
      { id: 'D', text: 'Enable CloudTrail Insights.', correct: false, why: 'CloudTrail Insights detects unusual control-plane API activity, which is a different problem.' },
    ],
    explanation:
      'The observability stack fits together: metrics say something is wrong, traces say where, logs say why. ServiceLens and Lambda Insights are the AWS-native glue between them.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ServiceLens.html',
  },
  {
    id: 'dva-d4-020',
    families: ['dva'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['xray'],
    stem: 'An X-Ray trace shows a subsegment marked with the throttle flag, while the parent segment is marked as a fault. What has happened?',
    options: [
      { id: 'A', text: 'A downstream call was rejected with a 429-class throttling response, and the unhandled result surfaced as a 5xx from the service — so the fix is backoff or more downstream capacity.', correct: true, why: 'X-Ray classifies 4xx as error, 5xx as fault and throttling as its own flag, so the pairing shows a throttled dependency escalating into a server error.' },
      { id: 'B', text: 'The service returned a 4xx because the client sent a malformed request.', correct: false, why: 'That is the error flag on the segment, and the throttle flag here points at the dependency.' },
      { id: 'C', text: 'The trace was sampled out partway through.', correct: false, why: 'Sampling is decided at the start of a trace, and sampled-out traces are absent rather than partial.' },
      { id: 'D', text: 'The subsegment timed out waiting for the downstream service.', correct: false, why: 'A timeout appears as a fault with an exception, not as the throttle flag.' },
    ],
    explanation:
      'X-Ray status vocabulary: error is 4xx (the caller\'s fault), fault is 5xx (yours), throttle is a rate rejection. Reading them correctly tells you whether to fix the client, the service or the capacity.',
    source: 'https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html',
  },
  {
    id: 'dva-d4-021',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'lambda'],
    stem: 'A Lambda function consumes an SQS queue receiving about 300 low-priority messages a second, one message per invocation. Invocation count dominates the bill and a delay of up to 30 seconds is acceptable.',
    options: [
      { id: 'A', text: 'Raise the event source mapping batch size and set a maximum batching window so each invocation handles many messages.', correct: true, why: 'Batching converts many small invocations into fewer larger ones, and the batching window lets Lambda wait to fill a batch — which the tolerated delay permits.' },
      { id: 'B', text: 'Increase the function memory to process messages faster.', correct: false, why: 'It reduces duration per message and does nothing about the number of invocations that is the actual cost driver.' },
      { id: 'C', text: 'Add reserved concurrency to limit parallel executions.', correct: false, why: 'It caps concurrency and the same number of messages still produces the same number of invocations.' },
      { id: 'D', text: 'Switch the queue to FIFO.', correct: false, why: 'FIFO changes ordering semantics and costs more per request.' },
    ],
    explanation:
      'Batch size up to 10,000 for a standard queue with a batching window of up to 300 seconds. Pair it with partial batch failure reporting so one bad message does not undo a large batch.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html',
  },
  {
    id: 'dva-d4-022',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['api-gateway', 'sqs', 'lambda'],
    stem: 'A REST endpoint\'s only job is to validate a JSON body and put it on an SQS queue. The team wants to remove the cost and cold-start latency of the Lambda function that does this.',
    options: [
      { id: 'A', text: 'Use an AWS service integration from API Gateway directly to SQS, with request validation against a model and a mapping template.', correct: true, why: 'API Gateway can call SQS directly, and request validation plus a mapping template covers both jobs the function was doing — removing a hop entirely.' },
      { id: 'B', text: 'Give the function provisioned concurrency.', correct: false, why: 'It removes the cold start and adds cost, when the requirement is to remove both.' },
      { id: 'C', text: 'Move the function to arm64 with less memory.', correct: false, why: 'A marginal saving that keeps the unnecessary hop.' },
      { id: 'D', text: 'Have clients write to SQS directly with credentials from an identity pool.', correct: false, why: 'It removes the API and pushes queue-level access and validation to untrusted clients.' },
    ],
    explanation:
      'API Gateway integrates directly with many AWS services, and Step Functions has SDK integrations for over two hundred. A Lambda function whose body is one SDK call is often removable.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-sqs.html',
  },
  {
    id: 'dva-d4-023',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudfront', 's3'],
    stem: 'A CloudFront distribution reports a 35% cache hit ratio for static assets. Origin cost and latency are both higher than expected.',
    options: [
      { id: 'A', text: 'Send explicit Cache-Control max-age headers from the origin, and remove unnecessary query strings, cookies and headers from the cache key.', correct: true, why: 'Hit ratio is governed by how long objects are cacheable and how many distinct cache keys exist — long TTLs and a narrow key are the two levers.' },
      { id: 'B', text: 'Add more edge locations to the distribution.', correct: false, why: 'Edge locations are not something you add; CloudFront uses the whole network already.' },
      { id: 'C', text: 'Enable field-level encryption.', correct: false, why: 'That protects sensitive form fields end to end and has nothing to do with caching.' },
      { id: 'D', text: 'Switch the price class to include all Regions.', correct: false, why: 'Price class affects which edge locations serve traffic and cost, not hit ratio.' },
    ],
    explanation:
      'Two rules for cache hit ratio: cache for as long as correctness allows, and include in the cache key only what genuinely varies the response. Origin Shield adds a second caching layer when many edges miss on the same object.',
    source: 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cache-hit-ratio.html',
  },
  {
    id: 'dva-d4-024',
    families: ['dva'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A product listing page reads a DynamoDB table 40,000 times a minute. Data is updated a few times a day and a second of staleness is harmless. Read capacity cost must come down.',
    options: [
      { id: 'A', text: 'Use eventually consistent reads, which consume half a read capacity unit per 4 KB instead of a full one.', correct: true, why: 'Eventually consistent reads halve the capacity cost and the stated tolerance for staleness makes them appropriate — the cheapest change available.' },
      { id: 'B', text: 'Switch the table to on-demand capacity mode.', correct: false, why: 'On-demand changes how capacity is billed and often costs more for steady, high-volume traffic.' },
      { id: 'C', text: 'Add a global secondary index to serve the page.', correct: false, why: 'An index adds storage and write cost rather than reducing read cost.' },
      { id: 'D', text: 'Enable point-in-time recovery.', correct: false, why: 'PITR is a backup feature and adds cost.' },
    ],
    explanation:
      'The read capacity table: one strongly consistent read of 4 KB is 1 RCU, eventually consistent is 0.5, transactional is 2. Writes are 1 WCU per KB and 2 for transactional. Cheap wins hide in that table.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html',
  },
]
