import type { Question } from '../schema'

/**
 * Domain 3: Deployment — 24% of DVA-C02. CI/CD, SAM and CloudFormation, and the
 * deployment strategies by name: the paper expects you to know which one
 * shifts traffic gradually and which one can be rolled back in seconds.
 */
export const dvaD3Questions: Question[] = [
  /* ── Domain 3: Deployment (24%) ───────────────────────────────────────── */
  {
    id: 'dva-d3-001',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codedeploy', 'lambda'],
    stem: 'A new Lambda version must receive 10% of traffic for five minutes, then all of it, rolling back automatically if the error rate rises. What should be configured?',
    options: [
      { id: 'A', text: 'A CodeDeploy deployment with the Canary10Percent5Minutes configuration and a CloudWatch alarm as the rollback trigger.', correct: true, why: 'That deployment configuration is literally 10% for five minutes then the remainder, and an alarm on the alias triggers automatic rollback.' },
      { id: 'B', text: 'A weighted alias split 10/90, adjusted manually after five minutes.', correct: false, why: 'It achieves the split but requires a human to complete the shift and to notice the errors.' },
      { id: 'C', text: 'The Linear10PercentEvery1Minute configuration.', correct: false, why: 'That shifts 10% every minute over ten minutes, which is not the pattern described.' },
      { id: 'D', text: 'A blue/green deployment on the function\'s $LATEST version.', correct: false, why: '$LATEST cannot be traffic-weighted; canary deployments require a published version behind an alias.' },
    ],
    explanation:
      'Canary means two jumps; linear means equal increments. Naming the specific configuration is a DVA habit worth having.',
    source: 'https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html',
  },
  {
    id: 'dva-d3-002',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda'],
    stem: 'One API Gateway deployment must serve dev, test and prod, each invoking a different Lambda alias, without duplicating the API definition. What should be used?',
    options: [
      { id: 'A', text: 'Stage variables referencing the Lambda alias, with one stage per environment.', correct: true, why: 'A stage variable substituted into the integration URI lets a single API definition target a different alias per stage.' },
      { id: 'B', text: 'Three separate REST APIs, one per environment.', correct: false, why: 'Duplicates the definition, which the requirement excludes.' },
      { id: 'C', text: 'A Lambda authoriser that routes to the correct alias.', correct: false, why: 'An authoriser authorises; it does not choose integration targets.' },
      { id: 'D', text: 'Custom domain base-path mappings pointing at different functions.', correct: false, why: 'Base-path mappings route to stages, not to different integration targets within one stage.' },
    ],
    explanation:
      'Stage variables plus Lambda aliases is the DVA answer to environment-specific integrations from one API definition.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/stage-variables.html',
  },
  {
    id: 'dva-d3-003',
    families: ['dva'],
    taskId: 'dva-3.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['sam'],
    stem: 'A developer wants to invoke a Lambda function locally with a test event, and run the API locally before deploying. What should be used?',
    options: [
      { id: 'A', text: 'AWS SAM CLI, using sam local invoke and sam local start-api.', correct: true, why: 'SAM CLI runs functions in a Docker container matching the Lambda runtime and can emulate API Gateway locally.' },
      { id: 'B', text: 'The AWS CLI with aws lambda invoke.', correct: false, why: 'That invokes the deployed function in AWS, not a local one.' },
      { id: 'C', text: 'AWS CloudShell with the function code uploaded.', correct: false, why: 'CloudShell is a remote shell, not a local Lambda emulator.' },
      { id: 'D', text: 'AWS CodeBuild with a buildspec that runs the handler.', correct: false, why: 'CodeBuild runs in AWS and is for building, not for local iteration.' },
    ],
    explanation:
      'SAM CLI is the local development loop: sam local invoke, sam local start-api, sam local generate-event. Docker is a prerequisite.',
    source: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html',
  },
  {
    id: 'dva-d3-004',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['appconfig'],
    stem: 'A team wants to enable a new feature for 10% of users, then all of them, rolling back automatically if the error metric rises — without deploying new code. What should be used?',
    options: [
      { id: 'A', text: 'AWS AppConfig feature flags with a gradual deployment strategy and a CloudWatch alarm for automatic rollback.', correct: true, why: 'AppConfig deploys configuration progressively, validates it, monitors an alarm, and rolls the configuration back on its own — all without a code deployment.' },
      { id: 'B', text: 'An SSM Parameter Store parameter read at start-up.', correct: false, why: 'It stores the flag but has no gradual rollout, no validation and no automatic rollback.' },
      { id: 'C', text: 'Lambda environment variables updated by a pipeline.', correct: false, why: 'Changing them is a function update — a deployment — which the requirement excludes.' },
      { id: 'D', text: 'A CodeDeploy canary deployment of the function.', correct: false, why: 'That deploys code; the requirement is to change behaviour without deploying.' },
    ],
    explanation:
      'Feature flags with gradual rollout and alarm-triggered rollback is the AppConfig signature. Parameter Store is the plausible distractor.',
    source: 'https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html',
  },
  {
    id: 'dva-d3-005',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'ecr'],
    stem: 'A Lambda function needs a 600 MB machine-learning dependency. What packaging option supports this?',
    options: [
      { id: 'A', text: 'A container image in Amazon ECR, which supports images up to 10 GB.', correct: true, why: 'The .zip path caps at 250 MB unzipped. Container image packaging raises the ceiling to 10 GB.' },
      { id: 'B', text: 'A Lambda layer, which has its own separate size allowance.', correct: false, why: 'Layers count toward the same 250 MB unzipped limit, so they do not help here.' },
      { id: 'C', text: 'A .zip uploaded via S3 rather than directly.', correct: false, why: 'Uploading via S3 raises the *upload* limit but the 250 MB unzipped limit still applies.' },
      { id: 'D', text: 'Mount the dependency from EFS and keep the package small.', correct: false, why: 'Technically viable and a real pattern, but it adds VPC configuration and cold-start cost — container packaging is the direct answer.' },
    ],
    explanation:
      'The numbers matter: 50 MB zipped direct upload, 250 MB unzipped including layers, 10 GB as a container image.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html',
  },
  {
    id: 'dva-d3-006',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codebuild', 'secrets-manager'],
    stem: 'A CodeBuild project needs a third-party API token during the build. It is currently a plaintext environment variable in the buildspec, visible in the console. What should be done?',
    options: [
      { id: 'A', text: 'Store the token in Secrets Manager and reference it with the SECRETS_MANAGER environment variable type.', correct: true, why: 'CodeBuild resolves the reference at build time, so the value never appears in the buildspec, the project configuration or the console.' },
      { id: 'B', text: 'Base64-encode the token in the buildspec.', correct: false, why: 'Encoding is not encryption — anyone reading the buildspec can decode it trivially.' },
      { id: 'C', text: 'Pass the token as a build override on every manual start.', correct: false, why: 'It breaks automated pipeline builds and puts the secret in command history.' },
      { id: 'D', text: 'Store it in the source repository in an encrypted file and decrypt during the build.', correct: false, why: 'Secrets in source control, plus a decryption key that must also be available. Worse on both counts.' },
    ],
    explanation:
      'CodeBuild supports PARAMETER_STORE and SECRETS_MANAGER variable types precisely so secrets stay out of the buildspec.',
    source: 'https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html',
  },

  {
    id: 'dva-d3-007',
    families: ['dva'],
    taskId: 'dva-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codepipeline', 'codebuild'],
    stem: 'A pipeline builds, then deploys to staging, then deploys to production. Integration tests must run against staging and production deployment must not start if they fail. How should the pipeline be structured?',
    options: [
      { id: 'A', text: 'Add a test stage after the staging deploy containing a CodeBuild test action — a failed action stops the pipeline before the production stage.', correct: true, why: 'CodePipeline promotes an artefact to the next stage only when every action in the current stage succeeds, so a failing test action is itself the gate.' },
      { id: 'B', text: 'Run the integration tests inside the build stage before deploying anywhere.', correct: false, why: 'At build time there is no deployed staging environment to test against.' },
      { id: 'C', text: 'Add a manual approval action and have a person run the tests by hand.', correct: false, why: 'The requirement is automated deployment testing, and a human gate reintroduces the delay and inconsistency automation removes.' },
      { id: 'D', text: 'Configure a CloudWatch alarm on staging errors and a pipeline rule that watches it.', correct: false, why: 'An alarm reports symptoms after the fact and does not deterministically block promotion of this execution.' },
    ],
    explanation:
      'In CodePipeline, ordering is the control flow: stages run in sequence, actions within a stage can run in parallel by run order, and any failed action halts that execution.',
    source: 'https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html',
  },
  {
    id: 'dva-d3-008',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['codedeploy', 'ec2'],
    stem: 'A CodeDeploy in-place deployment to EC2 must run a smoke test against the new revision and fail the deployment before any user traffic reaches it. Which appspec.yml lifecycle hook should run the test?',
    options: [
      { id: 'A', text: 'ValidateService, which runs after the application starts and can fail the deployment for that instance.', correct: true, why: 'ValidateService is the last hook of the deployment lifecycle and exists to verify the revision, with a non-zero exit failing the deployment.' },
      { id: 'B', text: 'BeforeInstall, so problems are caught as early as possible.', correct: false, why: 'The new revision is not installed yet, so there is nothing to smoke test.' },
      { id: 'C', text: 'ApplicationStop, which runs first on the instance.', correct: false, why: 'It runs from the previously deployed revision to shut the application down cleanly.' },
      { id: 'D', text: 'AfterAllowTraffic, which runs once the deployment completes.', correct: false, why: 'It is a valid place to test, but by then traffic is already flowing — the opposite of the requirement. It also only exists for blue/green and load-balanced deployments.' },
    ],
    explanation:
      'Learn the hook order: ApplicationStop, BeforeInstall, AfterInstall, ApplicationStart, ValidateService, and for blue/green the BeforeAllowTraffic and AfterAllowTraffic pair. Questions are usually decided by which hook sits either side of traffic.',
    source: 'https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html',
  },
  {
    id: 'dva-d3-009',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['ecs', 'codedeploy', 'elb'],
    stem: 'An ECS service must deploy a new task definition to a second target group, run automated tests against it on a port no user traffic uses, then shift production traffic across in one step. What supports this?',
    options: [
      { id: 'A', text: 'A CodeDeploy blue/green deployment for ECS with a test listener on the test port and an AfterAllowTestTraffic hook.', correct: true, why: 'ECS blue/green with CodeDeploy defines a production listener and an optional test listener, and the lifecycle hooks let you validate the replacement task set before shifting traffic.' },
      { id: 'B', text: 'The ECS rolling update deployment type with minimumHealthyPercent set to 100.', correct: false, why: 'Rolling updates replace tasks in the same target group, so there is no separate environment to test in isolation.' },
      { id: 'C', text: 'An ECS service with two target groups and manual deregistration.', correct: false, why: 'It approximates the shape by hand and gives up the automated hooks, rollback and traffic shifting the question describes.' },
      { id: 'D', text: 'A Lambda alias with a canary routing configuration.', correct: false, why: 'Alias traffic shifting is a Lambda feature and does not apply to ECS services.' },
    ],
    explanation:
      'Three deployment types for ECS: rolling update by the ECS service scheduler, blue/green via CodeDeploy, and external. Only blue/green gives you a test listener and pre-traffic validation.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-blue-green.html',
  },
  {
    id: 'dva-d3-010',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sam', 'cloudformation', 's3'],
    stem: 'A SAM template references a local directory for function code. Deploying the template directly with CloudFormation fails because CodeUri is not an S3 location. What resolves this correctly?',
    options: [
      { id: 'A', text: 'Run sam build then sam deploy, which packages the code to S3 or ECR and submits the transformed template.', correct: true, why: 'Packaging rewrites local paths into artefact URIs and uploads the bundles. sam deploy does this and then creates a CloudFormation change set.' },
      { id: 'B', text: 'Zip the project by hand and set CodeUri to the local zip file.', correct: false, why: 'CloudFormation cannot read a local path at all, zipped or not.' },
      { id: 'C', text: 'Add the Serverless transform a second time so CloudFormation resolves the path.', correct: false, why: 'The transform expands SAM resource types. It does not upload anything.' },
      { id: 'D', text: 'Inline the function code in the template with the ZipFile property.', correct: false, why: 'Inline code is capped at 4,096 characters and cannot carry dependencies, so it is unusable for real functions.' },
    ],
    explanation:
      'The SAM chain is build, then deploy (package plus create-change-set plus execute). Plain CloudFormation has the same step as aws cloudformation package.',
    source: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html',
  },
  {
    id: 'dva-d3-011',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['ecr', 'ecs'],
    stem: 'A team wants the exact artefact tested in staging to be the artefact that runs in production, and wants old images cleaned up automatically. Which two ECR configurations support this? (Choose two.)',
    options: [
      { id: 'A', text: 'Enable tag immutability on the repository.', correct: true, why: 'Immutable tags stop a tag being repointed at different content, so the thing you tested is provably the thing you deploy.' },
      { id: 'B', text: 'Reference images by digest rather than by a moving tag such as latest.', correct: true, why: 'A digest is a content hash, so it identifies one exact image no matter what tags are added or moved later.' },
      { id: 'C', text: 'Rebuild the image in each environment from the same commit.', correct: false, why: 'Two builds of one commit can differ — base image updates, dependency resolution, build-time timestamps. Build once, promote the artefact.' },
      { id: 'D', text: 'Enable scan on push.', correct: false, why: 'Vulnerability scanning is worth having but says nothing about artefact identity or cleanup.' },
      { id: 'E', text: 'Use one repository per environment and copy images between them on promotion.', correct: false, why: 'A copy creates a new object to verify, and the question asks for the same artefact rather than a duplicate of it.' },
    ],
    explanation:
      'Build once, promote the same immutable artefact, and let a lifecycle policy expire untagged or old images. Rebuilding per environment is the anti-pattern the exam is testing.',
    source: 'https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-tag-mutability.html',
  },
  {
    id: 'dva-d3-012',
    families: ['dva'],
    taskId: 'dva-3.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['device-farm'],
    stem: 'Before release, a mobile client must be tested against a range of real physical Android and iOS devices, with video and logs from each run, driven from the CI pipeline. Which service does this?',
    options: [
      { id: 'A', text: 'AWS Device Farm.', correct: true, why: 'Device Farm runs automated and manual tests on real devices in the cloud and returns videos, screenshots, logs and performance data.' },
      { id: 'B', text: 'Amazon EC2 Mac instances running simulators.', correct: false, why: 'Simulators are not real devices and miss hardware, radio and vendor-specific defects, which is the point of the requirement.' },
      { id: 'C', text: 'AWS CodeBuild with a mobile build image.', correct: false, why: 'CodeBuild compiles and runs unit tests. It has no device fleet.' },
      { id: 'D', text: 'Amazon AppStream 2.0.', correct: false, why: 'AppStream streams desktop applications to users. It is not a test service.' },
    ],
    explanation:
      'Device Farm is the only "real devices" answer on either exam. If a question names physical handsets, it is Device Farm.',
    source: 'https://docs.aws.amazon.com/devicefarm/latest/developerguide/welcome.html',
  },
  {
    id: 'dva-d3-013',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['elastic-beanstalk'],
    stem: 'An Elastic Beanstalk web environment must deploy with no reduction in capacity, no mixing of old and new code on the same instance, and the ability to return to the previous version within seconds if a problem is found. Which deployment approach fits?',
    options: [
      { id: 'A', text: 'Deploy to a second environment and swap CNAMEs — blue/green.', correct: true, why: 'A separate environment means full capacity throughout and no version mixing, and rollback is another CNAME swap, which is the only option that is near-instant.' },
      { id: 'B', text: 'Immutable deployment.', correct: false, why: 'It avoids capacity loss and version mixing by launching fresh instances, but rolling back means another full immutable deployment rather than seconds.' },
      { id: 'C', text: 'Rolling with additional batch.', correct: false, why: 'Capacity is maintained, but old and new versions serve traffic simultaneously during the deployment and rollback is a second rolling deployment.' },
      { id: 'D', text: 'All at once.', correct: false, why: 'It is the fastest and the cheapest, and it takes the whole environment down during the deploy.' },
    ],
    explanation:
      'Rank the Beanstalk policies by what they cost you: all at once (downtime), rolling (reduced capacity), rolling with additional batch (full capacity, mixed versions), immutable (full capacity, no mixing), blue/green (all of that plus instant rollback, at double the environment cost).',
    source: 'https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.deploy-existing-version.html',
  },
  {
    id: 'dva-d3-014',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'A team configures provisioned concurrency and points API Gateway at the function ARN without a qualifier. Cold starts continue. What is wrong?',
    options: [
      { id: 'A', text: 'The unqualified ARN resolves to $LATEST, and provisioned concurrency can only be allocated to a published version or an alias — so callers are not using it.', correct: true, why: 'Provisioned concurrency is a property of a version or alias. Invoking $LATEST bypasses it entirely and gets ordinary on-demand concurrency.' },
      { id: 'B', text: 'Provisioned concurrency takes up to 24 hours to become effective.', correct: false, why: 'It is ready within a couple of minutes and reports a Ready status.' },
      { id: 'C', text: 'Reserved concurrency must be set to zero before provisioned concurrency applies.', correct: false, why: 'Reserved concurrency caps and reserves the function ceiling. Setting it to zero would stop invocations altogether.' },
      { id: 'D', text: 'The function must be in a VPC for provisioned concurrency to apply.', correct: false, why: 'VPC configuration is unrelated, and VPC networking is no longer the main cold-start contributor it once was.' },
    ],
    explanation:
      'Versions are immutable, aliases point at versions, and provisioned concurrency, canary traffic shifting and stable integration targets all attach to a version or alias — never to $LATEST.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html',
  },
  {
    id: 'dva-d3-015',
    families: ['dva'],
    taskId: 'dva-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudformation', 'cloudwatch'],
    stem: 'A CloudFormation stack update must be rolled back automatically if an application error alarm fires during the first ten minutes after the resources are created. What should be configured?',
    options: [
      { id: 'A', text: 'Rollback triggers on the stack update, naming the CloudWatch alarms and a monitoring time in minutes.', correct: true, why: 'Rollback triggers monitor the named alarms for the configured period after resource creation and roll the stack back if any of them fire.' },
      { id: 'B', text: 'A CloudWatch alarm action that calls the CloudFormation DeleteStack API.', correct: false, why: 'Deleting the stack destroys the application rather than restoring the previous version, and an alarm action cannot call arbitrary APIs.' },
      { id: 'C', text: 'A stack policy denying updates to the affected resources.', correct: false, why: 'Stack policies prevent changes during an update. They cannot react to runtime metrics.' },
      { id: 'D', text: 'Termination protection on the stack.', correct: false, why: 'That only prevents accidental stack deletion.' },
    ],
    explanation:
      'CloudFormation rollback triggers are the infrastructure-level equivalent of CodeDeploy alarm rollback: define the alarm that means "this deployment is bad" before you deploy.',
    source: 'https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-rollback-triggers.html',
  },
  {
    id: 'dva-d3-016',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codeartifact', 'codebuild'],
    stem: 'Builds must consume the team\'s private npm packages alongside public ones from npmjs, from a single registry endpoint, with the public packages cached in the account. What should be configured?',
    options: [
      { id: 'A', text: 'A CodeArtifact repository with an upstream external connection to npmjs, and the build authenticated against it.', correct: true, why: 'An external connection makes CodeArtifact fetch and retain public packages on first request, so one registry serves private and public dependencies and the copies persist even if upstream changes.' },
      { id: 'B', text: 'An S3 bucket of tarballs referenced by URL in package.json.', correct: false, why: 'It works for a handful of packages but abandons versioning, resolution and the registry protocol.' },
      { id: 'C', text: 'A private ECR repository for the packages.', correct: false, why: 'ECR stores OCI container images, not language packages.' },
      { id: 'D', text: 'Two registries configured in .npmrc with a scope mapping for the private one.', correct: false, why: 'It resolves both sources but not from a single endpoint, and nothing is cached in the account.' },
    ],
    explanation:
      'CodeArtifact is the managed package registry for npm, PyPI, Maven, NuGet, Cargo, Ruby, Swift and generic packages. Upstream external connections are how you get a single endpoint plus a durable cache of public dependencies.',
    source: 'https://docs.aws.amazon.com/codeartifact/latest/ug/external-connection.html',
  },
  {
    id: 'dva-d3-017',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codebuild'],
    stem: 'A CodeBuild project spends four of its six minutes running npm install. Dependencies change roughly weekly. What should be added to the buildspec?',
    options: [
      { id: 'A', text: 'A cache section declaring the dependency directory as paths, with local or S3 caching enabled on the project.', correct: true, why: 'Caching the dependency directory between builds skips the download and reinstall when the lockfile has not changed, which is the four minutes being wasted.' },
      { id: 'B', text: 'Move npm install into the post_build phase.', correct: false, why: 'Phase order does not change how long the command takes, and the build would fail without dependencies.' },
      { id: 'C', text: 'Use a larger compute type for the project.', correct: false, why: 'It may shave a little time at higher cost, and network-bound installation does not scale with vCPU.' },
      { id: 'D', text: 'Add the dependency directory to the artifacts section.', correct: false, why: 'Artifacts are the build output uploaded at the end, not a between-build cache.' },
    ],
    explanation:
      'buildspec structure worth knowing cold: version, env, phases (install, pre_build, build, post_build), artifacts, cache, reports. Caching and a custom build image are the two levers for build time.',
    source: 'https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html',
  },
  {
    id: 'dva-d3-018',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['cloudformation', 'ec2'],
    stem: 'A CloudFormation stack reports CREATE_COMPLETE for an EC2 instance while the application on it is still installing, so a dependent resource is created too early.',
    options: [
      { id: 'A', text: 'Add a CreationPolicy with a timeout to the instance and call cfn-signal from the bootstrap script when installation succeeds.', correct: true, why: 'CreationPolicy makes CloudFormation wait for an explicit success signal rather than treating the API call as completion, which is exactly the gap described.' },
      { id: 'B', text: 'Add a DependsOn attribute to the dependent resource.', correct: false, why: 'DependsOn orders creation but still treats the instance as complete when EC2 reports it running.' },
      { id: 'C', text: 'Add a WaitCondition with no handle.', correct: false, why: 'A WaitCondition also needs a signal, and CreationPolicy is the current, simpler mechanism for an instance or Auto Scaling group.' },
      { id: 'D', text: 'Increase the stack timeout.', correct: false, why: 'A longer timeout does not tell CloudFormation when the application is ready.' },
    ],
    explanation:
      'CreationPolicy plus cfn-signal for "wait until the software is ready", UpdatePolicy for rolling updates on an Auto Scaling group, DependsOn only for ordering.',
    source: 'https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-creationpolicy.html',
  },
  {
    id: 'dva-d3-019',
    families: ['dva'],
    taskId: 'dva-3.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sam', 'lambda'],
    stem: 'While iterating on a serverless application, a developer wants a code change deployed to their personal development stack in seconds rather than the two minutes a full CloudFormation deployment takes.',
    options: [
      { id: 'A', text: 'Use sam sync with code-only synchronisation, which updates the function code directly and bypasses the change set for code changes.', correct: true, why: 'sam sync is built for the inner development loop, pushing code straight to the service and falling back to a full deployment only when the template changes.' },
      { id: 'B', text: 'Use sam deploy with --no-confirm-changeset.', correct: false, why: 'It removes a prompt and still executes a full CloudFormation change set.' },
      { id: 'C', text: 'Use sam local invoke and skip deployment.', correct: false, why: 'Local invocation is valuable and does not put the change in the development stack, which is what was asked.' },
      { id: 'D', text: 'Update the function code with the Lambda console editor.', correct: false, why: 'It drifts the deployed stack from the template, so the next deployment silently reverts the change.' },
    ],
    explanation:
      'The SAM loop: sam local for offline testing, sam sync for fast iteration against a personal stack, sam deploy for anything shared or production.',
    source: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-sync.html',
  },
  {
    id: 'dva-d3-020',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ecr', 'ecs'],
    stem: 'A container image is 1.4 GB because it contains the compiler toolchain and build dependencies used to produce the binary. Task start-up is slow and the image is expensive to store and pull.',
    options: [
      { id: 'A', text: 'Use a multi-stage Dockerfile — build in one stage, then copy only the compiled artefact into a minimal runtime base image.', correct: true, why: 'Multi-stage builds leave build-time tooling behind in a discarded stage, so the final image carries only what the application needs to run.' },
      { id: 'B', text: 'Add the build directories to .dockerignore.', correct: false, why: 'It reduces build context sent to the daemon, not the layers installed inside the image.' },
      { id: 'C', text: 'Squash all layers into one.', correct: false, why: 'Fewer layers of the same content is the same size, and it also destroys layer caching.' },
      { id: 'D', text: 'Enable ECR lifecycle policies.', correct: false, why: 'Lifecycle policies expire old images, which helps the repository bill and not this image\'s size or pull time.' },
    ],
    explanation:
      'Preparing artefacts for deployment is a DVA task statement, and image size is the usual concrete instance: multi-stage builds, a slim base image, and a layer order that keeps dependencies cached.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/application.html',
  },
  {
    id: 'dva-d3-021',
    families: ['dva'],
    taskId: 'dva-3.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudformation'],
    stem: 'Before applying a template change to a production stack, a team must know exactly which resources will be replaced rather than updated in place.',
    options: [
      { id: 'A', text: 'Create a change set and review the Replacement column for each resource before executing it.', correct: true, why: 'A change set is a dry run: it lists the action per resource and whether the update requires replacement, without changing anything until executed.' },
      { id: 'B', text: 'Run a stack update and watch the events, cancelling if a replacement starts.', correct: false, why: 'By the time the event appears the replacement is under way, and cancelling mid-update has its own risks.' },
      { id: 'C', text: 'Run cfn-lint on the template.', correct: false, why: 'Linting finds template errors; it does not know the deployed state, which is what determines replacement.' },
      { id: 'D', text: 'Enable drift detection on the stack.', correct: false, why: 'Drift detection compares deployed resources with the template as it stands, saying nothing about a proposed change.' },
    ],
    explanation:
      'Change sets are the review gate for infrastructure. Pair them with a stack policy to protect specific resources, and DeletionPolicy Retain on anything holding data.',
    source: 'https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-changesets.html',
  },
  {
    id: 'dva-d3-022',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['api-gateway'],
    stem: 'A new API version must receive 5% of production traffic on the same stage and endpoint, with separate metrics for the new version, before full promotion.',
    options: [
      { id: 'A', text: 'Enable a canary release on the stage with percentTraffic set to 5, then promote the canary when the metrics look right.', correct: true, why: 'Stage canary settings split traffic between the canary and the base deployment on the same stage, and emit separate CloudWatch metrics and logs for each.' },
      { id: 'B', text: 'Create a second stage and split traffic with Route 53 weighted records.', correct: false, why: 'It achieves a split at the cost of a second endpoint and DNS TTL behaviour, when the stage feature does it natively.' },
      { id: 'C', text: 'Use stage variables to point 5% of requests at a different Lambda alias.', correct: false, why: 'Stage variables are static per stage; they cannot express a traffic percentage.' },
      { id: 'D', text: 'Deploy the new version and rely on the Lambda alias canary configuration.', correct: false, why: 'That shifts traffic at the function level, which does not cover API-level changes such as models, mappings or authorisers.' },
    ],
    explanation:
      'Two independent canary mechanisms: API Gateway stage canary for API changes, and Lambda alias traffic shifting via CodeDeploy for function changes. Which one depends on what changed.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/canary-release.html',
  },
  {
    id: 'dva-d3-023',
    families: ['dva'],
    taskId: 'dva-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codebuild', 'codepipeline'],
    stem: 'A team wants pass and fail counts, trends and individual failing test names visible in the console for every build, without building their own dashboard.',
    options: [
      { id: 'A', text: 'Add a reports section to the buildspec pointing at the JUnit or Cucumber output files, producing a CodeBuild test report.', correct: true, why: 'CodeBuild parses standard test report formats and surfaces pass rates, durations and individual case results with history, at no extra work.' },
      { id: 'B', text: 'Print the test output to the build log and read it there.', correct: false, why: 'The information is present and unaggregated, with no trend and no per-case view.' },
      { id: 'C', text: 'Publish custom CloudWatch metrics from the test script.', correct: false, why: 'It gives counts and trends and not failing test names, and it is the dashboard-building the question excludes.' },
      { id: 'D', text: 'Fail the build on the first failing test so the log is short.', correct: false, why: 'That hides the remaining failures and makes each fix a separate build.' },
    ],
    explanation:
      'CodeBuild supports JUnit, NUnit, TestNG, Cucumber, Visual Studio TRX and code-coverage formats. Declaring reports is the cheapest observability win in a pipeline.',
    source: 'https://docs.aws.amazon.com/codebuild/latest/userguide/test-reporting.html',
  },
  {
    id: 'dva-d3-024',
    families: ['dva'],
    taskId: 'dva-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codedeploy', 'cloudwatch'],
    stem: 'A deployment must be rolled back automatically if the application 5xx rate rises within the deployment window, without anyone watching a dashboard.',
    options: [
      { id: 'A', text: 'Associate a CloudWatch alarm on the 5xx metric with the deployment group and enable automatic rollback on alarm threshold.', correct: true, why: 'CodeDeploy monitors the associated alarms during deployment and rolls back to the last known good revision when one goes into ALARM.' },
      { id: 'B', text: 'Add a ValidateService hook that queries CloudWatch for the metric.', correct: false, why: 'The hook runs once per instance at a point in time, so it cannot observe the rate over the deployment window.' },
      { id: 'C', text: 'Set the deployment configuration to OneAtATime.', correct: false, why: 'That limits the blast radius and does not detect or reverse anything.' },
      { id: 'D', text: 'Enable a CodePipeline manual approval before the deploy stage.', correct: false, why: 'An approval gates the start; it cannot react to what happens afterwards.' },
    ],
    explanation:
      'Automated rollback appears in three places worth recognising: CodeDeploy alarms and failed-deployment rollback, CloudFormation rollback triggers, and Lambda alias canary alarms via SAM DeploymentPreference.',
    source: 'https://docs.aws.amazon.com/codedeploy/latest/userguide/deployments-rollback-and-redeploy.html',
  },
  {
    id: 'dva-d3-025',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codepipeline'],
    stem: 'A pipeline with a CodeCommit-style Git source takes up to a minute to notice a new commit, and the team wants it to start immediately without a polling delay.',
    options: [
      { id: 'A', text: 'Use an EventBridge rule on the repository as the pipeline trigger instead of periodic source polling.', correct: true, why: 'Event-driven triggers start the pipeline on the commit event itself, which is both faster and the recommended configuration over polling.' },
      { id: 'B', text: 'Reduce the pipeline polling interval.', correct: false, why: 'The polling interval is not configurable, and polling is the mechanism being replaced.' },
      { id: 'C', text: 'Add a Lambda function that starts the pipeline on a schedule.', correct: false, why: 'A schedule is still polling, with more moving parts.' },
      { id: 'D', text: 'Enable pipeline execution mode SUPERSEDED.', correct: false, why: 'Execution mode governs how concurrent executions queue or replace each other, not how the pipeline is triggered.' },
    ],
    explanation:
      'Prefer event-driven triggers everywhere: EventBridge for repository and ECR events, webhooks for third-party Git providers. Polling is the legacy default and is slower.',
    source: 'https://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-about-starting.html',
  },
  {
    id: 'dva-d3-026',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['codedeploy', 'lambda'],
    stem: 'A Lambda deployment must move traffic to the new version in 10% increments every minute so a problem is caught with limited exposure. Which CodeDeploy deployment configuration matches?',
    options: [
      { id: 'A', text: 'CodeDeployDefault.LambdaLinear10PercentEvery1Minute.', correct: true, why: 'Linear configurations shift equal increments at a fixed interval, which is what "10% every minute" describes.' },
      { id: 'B', text: 'CodeDeployDefault.LambdaCanary10Percent5Minutes.', correct: false, why: 'Canary is two steps — 10% for five minutes, then everything — not repeated increments.' },
      { id: 'C', text: 'CodeDeployDefault.LambdaAllAtOnce.', correct: false, why: 'That shifts 100% immediately, with no graduated exposure.' },
      { id: 'D', text: 'CodeDeployDefault.LambdaBlueGreen10Percent.', correct: false, why: 'No such configuration exists — Lambda traffic shifting is canary, linear or all-at-once.' },
    ],
    explanation:
      'Learn the naming: Canary means two steps (a percentage, a wait, then the rest); Linear means equal increments at an interval; AllAtOnce means immediately. The same vocabulary applies to Lambda and ECS.',
    source: 'https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html',
  },
  {
    id: 'dva-d3-027',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['sam', 'lambda', 'codedeploy'],
    stem: 'A SAM-managed function must run an automated smoke test against the new version before any traffic is shifted, and a second check after the shift completes.',
    options: [
      { id: 'A', text: 'Set AutoPublishAlias and a DeploymentPreference with Hooks PreTraffic and PostTraffic pointing at validation functions.', correct: true, why: 'SAM wires those hooks into the CodeDeploy Lambda deployment, and a hook that reports failure aborts and rolls back before traffic moves.' },
      { id: 'B', text: 'Add a ValidateService hook to an appspec.yml in the project root.', correct: false, why: 'ValidateService is an EC2 and on-premises hook; Lambda deployments use PreTraffic and PostTraffic.' },
      { id: 'C', text: 'Add a CodeBuild test action to the pipeline after the deploy stage.', correct: false, why: 'It tests after the deployment has finished shifting traffic, which is too late for the pre-traffic requirement.' },
      { id: 'D', text: 'Configure provisioned concurrency so the new version is warm before testing.', correct: false, why: 'Warming is unrelated to running validation at a specific point in the traffic shift.' },
    ],
    explanation:
      'The hook names tell you the platform: BeforeAllowTraffic and AfterAllowTraffic for EC2 and ECS blue/green, PreTraffic and PostTraffic for Lambda. Both bracket the moment traffic moves.',
    source: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/automating-updates-to-serverless-apps.html',
  },
  {
    id: 'dva-d3-028',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudformation', 'dynamodb'],
    stem: 'A stack contains a DynamoDB table with production data. The team must ensure that deleting the stack, or renaming the logical resource, never destroys the table.',
    options: [
      { id: 'A', text: 'Set DeletionPolicy to Retain and UpdateReplacePolicy to Retain on the table resource.', correct: true, why: 'DeletionPolicy covers stack deletion and UpdateReplacePolicy covers an update that would replace the resource — both are needed, and the second is the one usually forgotten.' },
      { id: 'B', text: 'Set DeletionPolicy to Retain only.', correct: false, why: 'It protects deletion and leaves an update-triggered replacement free to delete the old table.' },
      { id: 'C', text: 'Enable termination protection on the stack.', correct: false, why: 'It blocks accidental stack deletion and does nothing about a resource replacement during an update.' },
      { id: 'D', text: 'Add the table to a stack policy denying Update:Delete.', correct: false, why: 'Stack policies protect against updates and are not applied when the stack is deleted.' },
    ],
    explanation:
      'Two attributes, two events: DeletionPolicy for stack deletion, UpdateReplacePolicy for replacement during an update. Both should be Retain on anything holding data.',
    source: 'https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html',
  },
  {
    id: 'dva-d3-029',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cdk', 'cloudformation'],
    stem: 'A team defines infrastructure with the AWS CDK in TypeScript. On a new account the first deployment fails with an error about a missing staging bucket and deployment role.',
    options: [
      { id: 'A', text: 'Run cdk bootstrap for that account and Region to create the CDKToolkit stack the CDK needs for assets and deployment roles.', correct: true, why: 'Bootstrapping provisions the S3 bucket, ECR repository and IAM roles the CDK uses to stage assets, once per account and Region.' },
      { id: 'B', text: 'Run cdk synth and deploy the resulting template with the CloudFormation console.', correct: false, why: 'It sidesteps the CLI and the template still references staged assets that need somewhere to live.' },
      { id: 'C', text: 'Add an S3 bucket for assets to the CDK app itself.', correct: false, why: 'The bucket must exist before the app deploys, which is the ordering bootstrapping solves.' },
      { id: 'D', text: 'Grant the deploying principal AdministratorAccess.', correct: false, why: 'Permissions are not the missing piece — the bootstrap resources are.' },
    ],
    explanation:
      'The CDK loop: cdk synth produces CloudFormation, cdk diff compares against deployed state, cdk deploy applies it — and cdk bootstrap is the once-per-account-and-Region prerequisite.',
    source: 'https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html',
  },
  {
    id: 'dva-d3-030',
    families: ['dva'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['ecs'],
    stem: 'A bad container image is deployed to an ECS service. Tasks fail their health checks, the scheduler keeps launching replacements, and the service sits in a failing rolling update until someone intervenes.',
    options: [
      { id: 'A', text: 'Enable deployment circuit breaker with rollback on the service, so a repeatedly failing deployment stops and reverts to the last stable task definition.', correct: true, why: 'The circuit breaker detects that a deployment cannot reach a steady state and, with rollback enabled, restores the previous task definition without human involvement.' },
      { id: 'B', text: 'Reduce minimumHealthyPercent to zero so the old tasks are stopped first.', correct: false, why: 'That accelerates removing the only healthy tasks, making the outage worse.' },
      { id: 'C', text: 'Increase the load balancer health check grace period.', correct: false, why: 'It helps a slow-starting healthy task; here the task is genuinely broken.' },
      { id: 'D', text: 'Set the desired count to zero and redeploy manually.', correct: false, why: 'That is the human intervention the question wants to make unnecessary.' },
    ],
    explanation:
      'ECS rolling updates are governed by minimumHealthyPercent, maximumPercent and the deployment circuit breaker. The circuit breaker is what makes a bad image self-correcting.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-circuit-breaker.html',
  },
  {
    id: 'dva-d3-031',
    families: ['dva'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['elastic-beanstalk'],
    stem: 'An Elastic Beanstalk application needs a package installed, an environment variable set and a cron entry created on every instance, defined in source control alongside the code.',
    options: [
      { id: 'A', text: 'Add .ebextensions configuration files in the application source bundle.', correct: true, why: '.ebextensions YAML files are applied during deployment and are the documented way to declare packages, files, container commands and option settings in the repository.' },
      { id: 'B', text: 'Configure everything through the Elastic Beanstalk console.', correct: false, why: 'Console changes are not in source control and are lost when the environment is rebuilt.' },
      { id: 'C', text: 'Bake the changes into a custom AMI and point the environment at it.', correct: false, why: 'A valid advanced option that adds AMI maintenance and is not code-adjacent configuration.' },
      { id: 'D', text: 'Add a Procfile to the bundle.', correct: false, why: 'A Procfile declares which processes to run, not packages or cron entries.' },
    ],
    explanation:
      'Beanstalk source-bundle conventions: .ebextensions for environment configuration, Procfile for processes, Buildfile for build commands, .platform hooks for platform-level scripts.',
    source: 'https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions.html',
  },
  {
    id: 'dva-d3-032',
    families: ['dva'],
    taskId: 'dva-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codepipeline', 'sns'],
    stem: 'A release to production must wait for a named release manager to approve it, and that person must be notified when a build is waiting rather than having to check the console.',
    options: [
      { id: 'A', text: 'A manual approval action with an SNS topic configured, and the approver granted codepipeline:PutApprovalResult.', correct: true, why: 'The approval action publishes to the topic when it starts waiting, and the IAM permission is what allows that person specifically to approve.' },
      { id: 'B', text: 'An EventBridge rule on pipeline state change that emails the manager.', correct: false, why: 'It notifies without creating the gate; the pipeline would proceed regardless.' },
      { id: 'C', text: 'Disabling the transition into the production stage and re-enabling it by hand.', correct: false, why: 'It halts the pipeline with no notification, no audit record and no approver identity.' },
      { id: 'D', text: 'A Lambda action that polls a ticket system for approval.', correct: false, why: 'Buildable, and it reimplements an action CodePipeline provides with notifications and audit built in.' },
    ],
    explanation:
      'Manual approval is a first-class action: optional SNS notification, a comment and URL for reviewers, a seven-day timeout, and an auditable record of who approved.',
    source: 'https://docs.aws.amazon.com/codepipeline/latest/userguide/approvals.html',
  },
]
