import type { Question } from '../schema'

/**
 * Domain 1: Development with AWS Services — 32% of DVA-C02, the largest
 * slice. Lambda's execution model and DynamoDB's key design carry most of it,
 * and the questions ask for the specific setting rather than the shape of the
 * architecture.
 */
export const dvaD1Questions: Question[] = [
  /* ── Domain 1: Development with AWS Services (32%) ────────────────────── */
  {
    id: 'dva-d1-001',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function opens a database connection on every invocation and is exhausting the connection pool under load. Where should the connection be created?',
    options: [
      { id: 'A', text: 'Outside the handler, in the initialisation code, so it is reused across invocations in the same execution environment.', correct: true, why: 'Initialisation code runs once per execution environment, not once per invocation, so warm invocations reuse the connection. This is asked directly on DVA.' },
      { id: 'B', text: 'Inside the handler, but closed in a finally block.', correct: false, why: 'It avoids leaks but still pays connection setup on every single invocation, which is the cost being complained about.' },
      { id: 'C', text: 'In a Lambda layer, so it is shared between functions.', correct: false, why: 'Layers ship code and dependencies. They do not share runtime state between functions.' },
      { id: 'D', text: 'In a Lambda extension running as a separate process.', correct: false, why: 'Extensions are for telemetry and lifecycle hooks, not for sharing application database connections.' },
    ],
    explanation:
      'Anything expensive and reusable — SDK clients, connection pools, parsed configuration — belongs outside the handler. For relational databases, add RDS Proxy as well.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html',
  },
  {
    id: 'dva-d1-002',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A DynamoDB Query returns 40 items when the developer expects 900. No error is raised. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The 1 MB result-page limit was reached and the code is not following LastEvaluatedKey to fetch subsequent pages.', correct: true, why: 'Query returns at most 1 MB per call and signals more results with LastEvaluatedKey. Ignoring it silently truncates the result set.' },
      { id: 'B', text: 'The table has insufficient read capacity, so items were dropped.', correct: false, why: 'Insufficient capacity produces a ProvisionedThroughputExceededException, not silently missing items.' },
      { id: 'C', text: 'Eventually consistent reads returned stale data.', correct: false, why: 'Eventual consistency can return slightly stale values, not a truncated count of this magnitude.' },
      { id: 'D', text: 'The FilterExpression removed the other items before they were read.', correct: false, why: 'A filter is applied after the read, and it would explain fewer items only if a filter were present — the far more common cause is pagination.' },
    ],
    explanation:
      'Every DynamoDB read API paginates at 1 MB. Use the SDK paginators, or loop on LastEvaluatedKey — "fewer results than expected" is nearly always this.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html',
  },
  {
    id: 'dva-d1-003',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'Two clients read the same DynamoDB item and both write an update. One update is silently lost. Which mechanism prevents this?',
    options: [
      { id: 'A', text: 'A conditional write using a version attribute — optimistic locking.', correct: true, why: 'A ConditionExpression asserting the version has not changed makes the second write fail rather than overwrite, and the client can retry with fresh data.' },
      { id: 'B', text: 'Strongly consistent reads on both clients.', correct: false, why: 'It guarantees each client reads the latest value, but does nothing to stop the second write overwriting the first.' },
      { id: 'C', text: 'A DynamoDB transaction wrapping each individual write.', correct: false, why: 'Transactions give atomicity across items. A single-item write is already atomic — the problem is the lost update, not partial writes.' },
      { id: 'D', text: 'Enabling DynamoDB Streams to detect the conflict afterwards.', correct: false, why: 'Streams let you observe what happened; they do not prevent it.' },
    ],
    explanation:
      'Optimistic locking with a version attribute plus a ConditionExpression is the standard DynamoDB answer to concurrent updates.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html',
  },
  {
    id: 'dva-d1-004',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function has reserved concurrency of 5. During a traffic burst, callers receive 429 TooManyRequestsException. The account concurrency limit is 1,000 and is not near being reached. What explains this?',
    options: [
      { id: 'A', text: 'Reserved concurrency also acts as a maximum, capping this function at 5 concurrent executions.', correct: true, why: 'Reserved concurrency does two things at once: it guarantees that much capacity and it caps the function at exactly that number. This dual behaviour is examined directly.' },
      { id: 'B', text: 'Reserved concurrency only guarantees a minimum, so the cause must be the account limit.', correct: false, why: 'It is a hard ceiling as well as a floor, and the question states the account limit is not the constraint.' },
      { id: 'C', text: 'Provisioned concurrency needs to be enabled to remove throttling.', correct: false, why: 'Provisioned concurrency pre-warms environments to remove cold starts. It does not raise the reserved ceiling.' },
      { id: 'D', text: 'The function timeout is too short, so invocations are being rejected.', correct: false, why: 'A short timeout produces a task-timeout error inside the invocation, not a 429 at the API boundary.' },
    ],
    explanation:
      'Reserved concurrency = guarantee *and* cap. Provisioned concurrency = pre-warmed environments to remove cold starts. Two different settings, constantly confused.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html',
  },
  {
    id: 'dva-d1-005',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'sqs'],
    stem: 'A Lambda function is invoked asynchronously by S3 events. Some events appear to be lost when the function throws an error. What should be configured to capture them?',
    options: [
      { id: 'A', text: 'An on-failure destination or a dead-letter queue on the function.', correct: true, why: 'Asynchronous invocations retry twice more and then discard the event unless a DLQ or on-failure destination is configured to receive it.' },
      { id: 'B', text: 'Increase the function timeout so it has more time to succeed.', correct: false, why: 'The function is erroring, not timing out. The event is still discarded after retries.' },
      { id: 'C', text: 'Enable S3 versioning so the event can be replayed.', correct: false, why: 'Versioning preserves objects, not the notification events derived from them.' },
      { id: 'D', text: 'Switch to synchronous invocation so the caller can retry.', correct: false, why: 'S3 event notifications to Lambda are asynchronous; this is not a configurable choice.' },
    ],
    explanation:
      'Async: two extra retries, then a DLQ or destination or the event is gone. Sync: no retries at all — the caller owns the retry.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html',
  },
  {
    id: 'dva-d1-006',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sdk', 'dynamodb'],
    stem: 'An application calling DynamoDB intermittently receives ProvisionedThroughputExceededException. What is the appropriate first response in the application code?',
    options: [
      { id: 'A', text: 'Rely on the SDK\'s built-in exponential backoff with jitter, and raise the retry configuration if needed.', correct: true, why: 'The AWS SDKs already implement exponential backoff with jitter for throttling errors. Hand-rolling it is the wrong answer; tuning maxAttempts or the retry mode is right.' },
      { id: 'B', text: 'Write a custom retry loop with a fixed 100 ms delay.', correct: false, why: 'A fixed delay from many clients synchronises retries and makes throttling worse. Jitter exists specifically to avoid this.' },
      { id: 'C', text: 'Catch the exception and return an error to the user immediately.', correct: false, why: 'Throttling is transient by nature, so failing straight through discards a request that would likely succeed on retry.' },
      { id: 'D', text: 'Switch every read to eventually consistent to halve the capacity used.', correct: false, why: 'Sometimes a valid optimisation, but it changes consistency semantics and does not address transient throttling properly.' },
    ],
    explanation:
      'The SDKs retry throttling errors with exponential backoff and jitter by default. Answers that propose writing your own are usually wrong on DVA.',
    source: 'https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html',
  },
  {
    id: 'dva-d1-007',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'vpc', 'privatelink'],
    stem: 'A Lambda function is configured for VPC access so it can reach an RDS instance in a private subnet. It now times out calling the public Stripe API. What is the cause and the cheapest fix for AWS API calls made by the same function?',
    options: [
      { id: 'A', text: 'A private subnet has no internet route, so the function needs a NAT gateway for third-party APIs — and VPC interface endpoints are cheaper for AWS service calls.', correct: true, why: 'Attaching a function to a VPC removes its default internet access. Third-party APIs need NAT; AWS APIs are better served by endpoints, which avoid the per-GB NAT charge.' },
      { id: 'B', text: 'The function needs a public IP address assigned.', correct: false, why: 'Lambda ENIs cannot be given public IP addresses. Egress must go through NAT.' },
      { id: 'C', text: 'The function\'s security group needs an inbound rule for the Stripe API.', correct: false, why: 'Outbound calls need an outbound rule, and security groups are stateful so the reply is automatic. This is a routing problem, not a filtering one.' },
      { id: 'D', text: 'The function should be removed from the VPC entirely.', correct: false, why: 'It would restore internet access but break the private RDS connection the VPC attachment exists for.' },
    ],
    explanation:
      'A VPC-attached Lambda has private-subnet networking, with all that implies. This is one of the most common real-world Lambda surprises and a recurring exam item.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/foundation-networking.html',
  },
  {
    id: 'dva-d1-008',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda'],
    stem: 'An API Gateway REST API with Lambda proxy integration returns HTTP 502 Bad Gateway. The function logs show it completed successfully. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The function is not returning the response shape Lambda proxy integration requires, with statusCode and body.', correct: true, why: 'Proxy integration requires a specific JSON envelope. A function that returns a bare object succeeds internally, and API Gateway cannot translate it — producing a 502.' },
      { id: 'B', text: 'The function exceeded the 29-second integration timeout.', correct: false, why: 'That produces a 504 Gateway Timeout, not a 502.' },
      { id: 'C', text: 'API Gateway is being throttled.', correct: false, why: 'Throttling returns 429 Too Many Requests.' },
      { id: 'D', text: 'The API Gateway execution role lacks lambda:InvokeFunction.', correct: false, why: 'That produces a 500 with an authorisation error, and the function would never run at all.' },
    ],
    explanation:
      'Know the codes: 502 malformed response, 504 integration timeout, 429 throttling, 403 authoriser rejection. DVA asks these directly.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html',
  },
  {
    id: 'dva-d1-009',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A table must automatically delete session records 30 days after creation, at no additional cost. What should be used?',
    options: [
      { id: 'A', text: 'Enable TTL on an attribute holding the expiry time as a Unix epoch timestamp.', correct: true, why: 'TTL deletes expired items with no write capacity consumed and no cost. Deletion happens within about 48 hours of expiry rather than instantly.' },
      { id: 'B', text: 'A scheduled Lambda function scanning for old items and deleting them.', correct: false, why: 'It works but consumes read and write capacity, and a full-table scan is exactly the access pattern to avoid.' },
      { id: 'C', text: 'A DynamoDB Streams consumer that deletes items after 30 days.', correct: false, why: 'Streams have a 24-hour retention, so a 30-day delay cannot be driven from them.' },
      { id: 'D', text: 'An S3 lifecycle rule on the table\'s backups.', correct: false, why: 'Lifecycle rules apply to S3 objects, not DynamoDB items.' },
    ],
    explanation:
      'TTL is free and the intended answer for expiring data. Note that deletion is eventual — filter expired items in queries if precision matters.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html',
  },
  {
    id: 'dva-d1-010',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'lambda'],
    stem: 'A Lambda function processes SQS messages in batches of 10. When one message in a batch fails, all 10 are redelivered and the successful nine are processed again. What should be configured?',
    options: [
      { id: 'A', text: 'Enable ReportBatchItemFailures on the event source mapping and return the failed message identifiers from the handler.', correct: true, why: 'Partial batch response makes only the failed messages become visible again, so successful ones are not reprocessed.' },
      { id: 'B', text: 'Reduce the batch size to 1.', correct: false, why: 'It solves the symptom by giving up batching entirely, raising invocation count and cost.' },
      { id: 'C', text: 'Increase the visibility timeout.', correct: false, why: 'That addresses duplicate processing from timeouts, not partial batch failure.' },
      { id: 'D', text: 'Switch to a FIFO queue.', correct: false, why: 'FIFO makes it worse — a failing message blocks its entire message group.' },
    ],
    explanation:
      'ReportBatchItemFailures is the specific fix for partial batch failure, and it applies to SQS, Kinesis and DynamoDB Streams event sources.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html',
  },
  {
    id: 'dva-d1-011',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['step-functions', 'lambda'],
    stem: 'A workflow must pause until a human approves a request, which may take days, then continue. What Step Functions pattern should be used?',
    options: [
      { id: 'A', text: 'A task with .waitForTaskToken, resumed by a call to SendTaskSuccess when the approval arrives.', correct: true, why: 'The callback pattern suspends the execution — for up to a year on a Standard workflow — until something external returns the task token.' },
      { id: 'B', text: 'A Wait state with a long timeout, polling an approvals table.', correct: false, why: 'Wastes state transitions polling, and requires guessing the delay in advance.' },
      { id: 'C', text: 'An Express workflow with a long timeout.', correct: false, why: 'Express workflows are capped at five minutes, so days of waiting is impossible.' },
      { id: 'D', text: 'A Lambda function that sleeps until approval is received.', correct: false, why: 'Lambda caps at 15 minutes, and paying to sleep is exactly what workflow state exists to avoid.' },
    ],
    explanation:
      '.waitForTaskToken is the human-in-the-loop pattern. Standard workflows for anything long or requiring exactly-once; Express for high-volume short executions.',
    source: 'https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html',
  },
  {
    id: 'dva-d1-012',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb'],
    stem: 'A developer adds a GSI to a busy table. Shortly afterwards, writes to the base table begin to throttle, though the base table\'s own capacity is ample. Why?',
    options: [
      { id: 'A', text: 'The GSI has insufficient write capacity, and a throttled index throttles writes to the base table.', correct: true, why: 'Every base-table write that affects an indexed attribute must also write to the GSI. If the index cannot keep up, the base write fails.' },
      { id: 'B', text: 'GSIs are eventually consistent, so writes queue until the index catches up.', correct: false, why: 'Eventual consistency describes reads of the index, not back-pressure on writes.' },
      { id: 'C', text: 'The GSI must use the same partition key as the base table, and the mismatch causes throttling.', correct: false, why: 'A GSI is specifically allowed a different partition key — that is the whole point of it.' },
      { id: 'D', text: 'Adding a GSI requires a table rebuild, during which writes are throttled.', correct: false, why: 'A GSI backfills online without blocking writes.' },
    ],
    explanation:
      'An under-provisioned GSI breaks the base table. This surprises people and is examined directly — provision indexes as carefully as tables.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html',
  },

  {
    id: 'dva-d1-013',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda', 'kinesis-data-streams'],
    stem: 'A Lambda function reads a Kinesis Data Stream. One malformed record throws on every attempt, and processing for that shard has stopped advancing for hours. Records behind it are ageing out. What configuration keeps the shard moving while preserving the bad record for analysis?',
    options: [
      { id: 'A', text: 'On the event source mapping, set BisectBatchOnFunctionError, a MaximumRetryAttempts value, and an on-failure destination.', correct: true, why: 'Bisecting isolates the poison record from the rest of the batch, the retry cap stops it blocking the shard forever, and the destination captures its metadata for investigation.' },
      { id: 'B', text: 'Increase the function timeout so the record has longer to succeed.', correct: false, why: 'The record fails deterministically. More time per attempt only slows the backlog further.' },
      { id: 'C', text: 'Switch the event source to an SQS queue with a dead-letter queue.', correct: false, why: 'It would work for new architecture but discards the per-shard ordering Kinesis was chosen for, and is not a configuration change.' },
      { id: 'D', text: 'Set the starting position to LATEST so processing skips ahead.', correct: false, why: 'StartingPosition only applies when the mapping is created, and skipping ahead silently loses every record in the backlog.' },
    ],
    explanation:
      'A stream shard is ordered, so one failing record blocks everything behind it. The three-part answer — bisect, cap retries, send failures to a destination — is the standard Kinesis and DynamoDB Streams poison-pill fix.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html',
  },
  {
    id: 'dva-d1-014',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb'],
    stem: 'A table stores IoT readings with partition key deviceId and sort key timestamp. Three of 10,000 devices produce 90% of the traffic and their writes throttle while the table as a whole is well under its provisioned capacity. What change fixes this?',
    options: [
      { id: 'A', text: 'Write-shard the hot key — append a calculated suffix such as deviceId#0..deviceId#9 — and query all shards in parallel on read.', correct: true, why: 'Throughput is allocated per partition, so a single partition key cannot exceed 1,000 WCU regardless of table capacity. Spreading one logical key over several physical keys is the documented remedy.' },
      { id: 'B', text: 'Switch the table to on-demand capacity mode.', correct: false, why: 'On-demand removes the table-level ceiling but the per-partition limit still applies, so the same three devices keep throttling.' },
      { id: 'C', text: 'Add a global secondary index on timestamp.', correct: false, why: 'A GSI adds a read path. It does not relieve write pressure on the base table partition — it adds to it.' },
      { id: 'D', text: 'Enable DynamoDB Accelerator (DAX) in front of the table.', correct: false, why: 'DAX is a read-through cache. Writes still go to the table.' },
    ],
    explanation:
      'Every "capacity is fine but one key throttles" question is about the per-partition limit: 3,000 RCU and 1,000 WCU. The fix is always a better key distribution, never more table capacity.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html',
  },
  {
    id: 'dva-d1-015',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['elasticache', 'rds'],
    stem: 'An application caches product records in ElastiCache using lazy loading. After a price change is written to the database, users keep seeing the old price for hours. Which change fixes the staleness with the least added write latency?',
    options: [
      { id: 'A', text: 'Keep lazy loading, but set a TTL on each cached item and delete the key when the record is updated.', correct: true, why: 'Invalidating on write bounds staleness to zero for the changed record, and the TTL is the safety net for updates that bypass the application. Neither adds work to the common read path.' },
      { id: 'B', text: 'Switch to write-through caching for every write in the application.', correct: false, why: 'It keeps the cache fresh but adds a cache write to every database write, including records nobody ever reads — the cost the question is asking you to avoid.' },
      { id: 'C', text: 'Reduce the cache node size so entries are evicted sooner.', correct: false, why: 'Relying on memory pressure for correctness is unpredictable, and it evicts hot entries as readily as stale ones.' },
      { id: 'D', text: 'Read from the database and populate the cache asynchronously afterwards.', correct: false, why: 'That is lazy loading described differently. It does not address the stale entry already in the cache.' },
    ],
    explanation:
      'Lazy loading plus a TTL plus explicit invalidation on write is the default caching answer. Write-through is for data that must be readable the instant it is written.',
    source: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Strategies.html',
  },
  {
    id: 'dva-d1-016',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway'],
    stem: 'A new API needs request-body validation against a JSON schema, per-customer API keys with usage plans, and AWS WAF in front of it. Which API Gateway type meets all three requirements?',
    options: [
      { id: 'A', text: 'A REST API.', correct: true, why: 'Request validation with models, API keys with usage plans and WAF integration are all REST API features.' },
      { id: 'B', text: 'An HTTP API.', correct: false, why: 'HTTP APIs are cheaper and lower-latency but have no API keys or usage plans, no request validation and no WAF support.' },
      { id: 'C', text: 'A WebSocket API.', correct: false, why: 'WebSocket APIs are for bidirectional persistent connections, not request/response endpoints.' },
      { id: 'D', text: 'An HTTP API with a Lambda authoriser doing the validation in code.', correct: false, why: 'It could approximate validation but still leaves API keys, usage plans and WAF unmet, and moves platform work into code you have to maintain.' },
    ],
    explanation:
      'Choose HTTP API by default for cost and latency; choose REST API when you need API keys and usage plans, request validation, WAF, or private endpoints.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html',
  },
  {
    id: 'dva-d1-017',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['sqs', 'lambda', 'dynamodb'],
    stem: 'A payment worker consumes a standard SQS queue. Occasionally a payment is charged twice. The team confirms the producer sends each message once. What must the worker do?',
    options: [
      { id: 'A', text: 'Make processing idempotent — record the message deduplication id in DynamoDB with a conditional write, and skip the work if the write fails.', correct: true, why: 'Standard queues guarantee at-least-once delivery, so duplicates are expected behaviour and the consumer is responsible for tolerating them. A conditional write is the atomic "have I already done this" check.' },
      { id: 'B', text: 'Increase the visibility timeout to exceed the processing time.', correct: false, why: 'It removes one common cause of duplicates — redelivery mid-processing — but not the at-least-once guarantee itself, so double charges can still occur.' },
      { id: 'C', text: 'Set the queue to long polling with a 20-second wait time.', correct: false, why: 'Long polling reduces empty receives and cost. It has nothing to do with duplicate delivery.' },
      { id: 'D', text: 'Delete the message before processing it rather than after.', correct: false, why: 'That converts a duplicate-processing bug into a lost-payment bug, which is strictly worse.' },
    ],
    explanation:
      'Standard SQS is at-least-once and unordered. FIFO queues offer exactly-once processing within a deduplication window, but the exam expects a consumer to be idempotent either way.',
    source: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html',
  },
  {
    id: 'dva-d1-018',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['step-functions', 's3', 'lambda'],
    stem: 'A workflow must run the same Lambda transformation over roughly 400,000 objects in an S3 prefix, with concurrency control and per-item error handling. Which Step Functions feature fits?',
    options: [
      { id: 'A', text: 'A Distributed Map state, which reads the S3 inventory directly and runs child executions in large-scale parallelism.', correct: true, why: 'Distributed Map is built for large-scale data processing over S3 and supports item batching, tolerated failure thresholds and a configurable maximum concurrency.' },
      { id: 'B', text: 'An inline Map state over an array of keys passed in the state input.', correct: false, why: 'Inline Map is capped at 40 concurrent iterations and the whole array must fit in the 256 KB state payload — nowhere near 400,000 keys.' },
      { id: 'C', text: 'A Parallel state with one branch per object.', correct: false, why: 'Parallel branches are defined statically in the state machine. You cannot write 400,000 of them.' },
      { id: 'D', text: 'A Choice state looping back on itself once per object.', correct: false, why: 'Sequential iteration with 400,000 state transitions is slow and expensive, and Standard workflows have a 25,000-event execution history limit.' },
    ],
    explanation:
      'Inline Map for small in-payload arrays; Distributed Map when the item source is S3 or the count runs to thousands. The 40-concurrency and 256 KB payload limits are the numbers that decide it.',
    source: 'https://docs.aws.amazon.com/step-functions/latest/dg/concepts-orchestrate-large-scale-parallel-workloads.html',
  },
  {
    id: 'dva-d1-019',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function downloads a 3 GB video from S3, transcodes it on local disk and uploads the result. It fails with "No space left on device". What is the correct fix?',
    options: [
      { id: 'A', text: 'Increase the function ephemeral storage (/tmp) allocation, which can be configured up to 10,240 MB.', correct: true, why: '/tmp defaults to 512 MB and is configurable to 10 GB. It is the exact knob for a function that needs local scratch space.' },
      { id: 'B', text: 'Increase the function memory, since /tmp is carved out of the memory allocation.', correct: false, why: 'Memory and ephemeral storage are separate settings. Raising memory buys CPU, not disk.' },
      { id: 'C', text: 'Write to /var/task instead, which is not size-limited.', correct: false, why: '/var/task holds the deployment package and is read-only at runtime.' },
      { id: 'D', text: 'Enable a Lambda layer to provide additional storage.', correct: false, why: 'Layers add read-only code and dependencies, counting against the 250 MB unzipped package limit.' },
    ],
    explanation:
      'Three separate Lambda limits worth knowing cold: 512 MB default /tmp configurable to 10 GB, 250 MB unzipped package including layers, and 10 GB for a container image. Mount EFS when the working set exceeds even 10 GB or must be shared.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-ephemeral-storage.html',
  },
  {
    id: 'dva-d1-020',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'api-gateway', 'lambda'],
    stem: 'Browser clients must upload files of up to 200 MB straight to S3 without the bytes passing through the application, and the upload link must expire after 15 minutes. What should the backend return to the client?',
    options: [
      { id: 'A', text: 'A presigned URL generated with the caller credentials of a role that can write only to the intended prefix.', correct: true, why: 'A presigned URL carries the signer permissions and an expiry, so the browser uploads directly to S3 and the application never handles the payload.' },
      { id: 'B', text: 'Temporary IAM user access keys created per upload.', correct: false, why: 'Creating IAM users per request is an anti-pattern — it is rate-limited, leaves credentials to clean up and is far broader than one upload needs.' },
      { id: 'C', text: 'A public-write bucket policy scoped to the upload prefix.', correct: false, why: 'Anonymous write access to a prefix lets anyone on the internet fill the bucket.' },
      { id: 'D', text: 'A base64 upload through API Gateway to a Lambda function that forwards it to S3.', correct: false, why: 'API Gateway caps the payload at 10 MB, and the requirement is explicitly that bytes should not pass through the application.' },
    ],
    explanation:
      'Presigned URL for direct client transfer, expiring and scoped. Remember the API Gateway 10 MB payload limit and the Lambda 6 MB synchronous response limit — they are why the direct-to-S3 pattern exists.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html',
  },
  {
    id: 'dva-d1-021',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['eventbridge', 'sns'],
    stem: 'An order service must publish events that several teams consume. Consumers need to subscribe to events whose JSON body matches specific field values, and one team needs to replay last month\'s events into a new service. Which service should carry the events?',
    options: [
      { id: 'A', text: 'Amazon EventBridge, using rules with content-based event patterns and an event archive with replay.', correct: true, why: 'Event patterns match on the event payload structure, and archive plus replay is an EventBridge feature. Both requirements point to the same service.' },
      { id: 'B', text: 'Amazon SNS with subscription filter policies.', correct: false, why: 'SNS filter policies match message attributes rather than the message body by default, and SNS has no archive and replay capability.' },
      { id: 'C', text: 'Amazon SQS with one queue per consumer.', correct: false, why: 'A queue is point-to-point. Fanning out to several teams needs a topic or bus in front, and there is no content routing or replay.' },
      { id: 'D', text: 'Kinesis Data Streams with a 30-day retention setting.', correct: false, why: 'Retention would allow re-reading, but consumers must filter every record themselves and manage shard-level consumption — far heavier than rule-based routing.' },
    ],
    explanation:
      'SNS for high-throughput fanout of simple notifications; EventBridge when you need content-based routing, schema discovery, replay, or third-party and AWS service events.',
    source: 'https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-archive.html',
  },
  {
    id: 'dva-d1-022',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda', 'sqs', 'eventbridge'],
    stem: 'An asynchronously invoked function must, on success, hand the result and the original event to another service, and on failure record the same context for replay. A dead-letter queue is already configured but the team finds it insufficient. Why, and what should replace it?',
    options: [
      { id: 'A', text: 'A DLQ receives only the failed event payload — Lambda destinations send the event plus the response or error to SQS, SNS, EventBridge or another function, on success as well as failure.', correct: true, why: 'Destinations carry invocation context and cover the success path, which is exactly the gap the team hit.' },
      { id: 'B', text: 'A DLQ only works for synchronous invocations, so it never received anything.', correct: false, why: 'It is the other way round: DLQs and destinations both apply to asynchronous invocation.' },
      { id: 'C', text: 'The DLQ needs a redrive policy with maxReceiveCount raised.', correct: false, why: 'That setting belongs to an SQS source queue feeding its own DLQ, not to Lambda asynchronous failure handling.' },
      { id: 'D', text: 'The function should catch its own errors and publish to SNS itself.', correct: false, why: 'It works and pushes platform plumbing into application code, and it cannot capture a timeout or an out-of-memory kill.' },
    ],
    explanation:
      'Destinations supersede the asynchronous DLQ: same failure coverage, plus the success path, plus the response payload. Keep the DLQ only for pre-existing configurations.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html',
  },
  {
    id: 'dva-d1-023',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'An account has the default 1,000 concurrent executions. A developer tries to set reserved concurrency of 950 on one function and the request is rejected. Why?',
    options: [
      { id: 'A', text: 'Lambda requires at least 100 unreserved concurrency to remain in the account pool, so the maximum reservable here is 900.', correct: true, why: 'Reserved concurrency is carved out of the account pool and Lambda refuses to leave fewer than 100 for everything else.' },
      { id: 'B', text: 'Reserved concurrency cannot exceed 500 per function.', correct: false, why: 'There is no such per-function ceiling; the constraint is the account pool and the 100 unreserved floor.' },
      { id: 'C', text: 'Provisioned concurrency must be configured before reserved concurrency.', correct: false, why: 'They are independent settings, though provisioned cannot exceed reserved when both are set.' },
      { id: 'D', text: 'The function must be published as a version first.', correct: false, why: 'Reserved concurrency applies to the function as a whole, unqualified — unlike provisioned concurrency.' },
    ],
    explanation:
      'Reserved concurrency both guarantees and caps a function, and is deducted from the account pool. Provisioned concurrency pre-warms environments on a version or alias and is billed whether used or not.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html',
  },
  {
    id: 'dva-d1-024',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A Java function behind a synchronous API shows 4-second cold starts caused by framework initialisation. Traffic is spiky and provisioned concurrency has been rejected as too expensive for the idle hours.',
    options: [
      { id: 'A', text: 'Enable SnapStart, which takes a snapshot of the initialised execution environment and restores from it.', correct: true, why: 'SnapStart removes most initialisation cost for Java at no additional charge, which suits spiky traffic where paying for always-warm capacity does not.' },
      { id: 'B', text: 'Increase the memory allocation to speed up initialisation.', correct: false, why: 'More CPU shortens initialisation somewhat, and it raises the cost of every invocation without removing the cold start.' },
      { id: 'C', text: 'Move the framework setup inside the handler.', correct: false, why: 'That makes every invocation pay the cost rather than only cold ones — strictly worse.' },
      { id: 'D', text: 'Schedule a warming event every five minutes with EventBridge.', correct: false, why: 'A well-known hack that keeps one environment warm and does nothing for a burst that needs fifty.' },
    ],
    explanation:
      'SnapStart caveats worth knowing: state captured in the snapshot is reused, so re-seed randomness and re-establish network connections in the afterRestore runtime hook.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html',
  },
  {
    id: 'dva-d1-025',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'A function generates a 40 MB CSV export. Invoked synchronously it fails, and the team wants the client to start receiving bytes before generation finishes.',
    options: [
      { id: 'A', text: 'Use response streaming through a Lambda function URL or InvokeWithResponseStream, which raises the payload ceiling well beyond the 6 MB buffered limit and sends bytes as they are produced.', correct: true, why: 'Streaming both defeats the 6 MB synchronous response limit and improves time to first byte, which is the second requirement.' },
      { id: 'B', text: 'Increase the function memory and timeout.', correct: false, why: 'The 6 MB synchronous response payload limit is fixed and unrelated to memory or timeout.' },
      { id: 'C', text: 'Write the file to S3 and return a presigned URL.', correct: false, why: 'A perfectly good pattern that gives the client nothing until generation completes, which the question rules out.' },
      { id: 'D', text: 'Compress the response with gzip.', correct: false, why: 'It might squeeze under the limit today and will break again as exports grow, and it does not stream.' },
    ],
    explanation:
      'Lambda payload limits: 6 MB synchronous request and response, 256 KB asynchronous, 20 MB soft limit with response streaming. API Gateway adds its own 10 MB request cap.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html',
  },
  {
    id: 'dva-d1-026',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'Six functions share the same 40 MB of dependencies. Each deployment package currently bundles them, deployments are slow and the console editor is unavailable.',
    options: [
      { id: 'A', text: 'Move the dependencies into a Lambda layer and attach the published layer version to each function.', correct: true, why: 'A layer is uploaded once and shared, so the function packages shrink back under the 3 MB console-editing threshold and deployments carry only application code.' },
      { id: 'B', text: 'Mount an EFS file system holding the dependencies.', correct: false, why: 'Possible for very large dependencies, and it adds VPC configuration, mount latency and a file system to run.' },
      { id: 'C', text: 'Switch every function to a container image.', correct: false, why: 'It raises the size ceiling to 10 GB and gives up the console editor entirely and adds an image build to every deploy.' },
      { id: 'D', text: 'Reference the dependencies from S3 at start-up.', correct: false, why: 'Downloading and unpacking on each cold start adds latency the layer avoids.' },
    ],
    explanation:
      'Layers are immutable, versioned, up to five per function, and count towards the same 250 MB unzipped limit. Editing in the console requires the deployment package to be under 3 MB.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/chapter-layers.html',
  },
  {
    id: 'dva-d1-027',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A function needs 30 configuration values injected as environment variables. Deployment fails with an error about the environment variables exceeding a limit.',
    options: [
      { id: 'A', text: 'The 4 KB total limit for environment variables has been exceeded — move the configuration into Parameter Store or AppConfig and read it at initialisation.', correct: true, why: 'The 4 KB cap is on the combined size of all environment variables, and externalising configuration also means changing it without a deployment.' },
      { id: 'B', text: 'Each environment variable is limited to 256 bytes, so the values must be shortened.', correct: false, why: 'There is no documented per-variable cap; the limit is 4 KB in total.' },
      { id: 'C', text: 'Environment variables must be encrypted with a customer managed key above a certain size.', correct: false, why: 'Encryption helpers are optional and unrelated to the size limit.' },
      { id: 'D', text: 'Lambda supports at most 20 environment variables.', correct: false, why: 'There is no count limit, only the total size.' },
    ],
    explanation:
      'Environment variables suit a handful of small, deploy-time values. Anything larger, shared, or changing at runtime belongs in Parameter Store, Secrets Manager or AppConfig.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html',
  },
  {
    id: 'dva-d1-028',
    families: ['dva'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A team wants to cut the cost of a fleet of Node.js functions with no change in behaviour. The code has no native binary dependencies.',
    options: [
      { id: 'A', text: 'Switch the functions to the arm64 architecture, then load test to confirm.', correct: true, why: 'Graviton-based arm64 functions are billed at a lower rate per GB-second and often run faster, and a pure-JavaScript codebase has nothing architecture-specific to port.' },
      { id: 'B', text: 'Reduce the timeout on each function.', correct: false, why: 'Timeout is a ceiling, not a billed quantity. Lowering it only turns slow invocations into failures.' },
      { id: 'C', text: 'Reduce the memory setting to the minimum.', correct: false, why: 'It cuts the per-millisecond rate and usually extends duration, frequently costing more overall.' },
      { id: 'D', text: 'Move the functions into a VPC.', correct: false, why: 'VPC configuration adds no cost saving and constrains networking.' },
    ],
    explanation:
      'Lambda cost is memory multiplied by duration multiplied by the architecture rate. arm64 lowers the rate, right-sizing memory optimises the product — verify both by measuring billed duration.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html',
  },
  {
    id: 'dva-d1-029',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb'],
    stem: 'Code calls BatchWriteItem with 25 items. The call returns HTTP 200, but some items are missing from the table afterwards. What is the defect?',
    options: [
      { id: 'A', text: 'The response UnprocessedItems map is being ignored — a partially throttled batch still returns 200 and the caller must retry the remainder with backoff.', correct: true, why: 'BatchWriteItem is not atomic. Individual writes can be rejected for capacity while the call as a whole succeeds, and the SDK does not retry them for you.' },
      { id: 'B', text: 'BatchWriteItem accepts a maximum of 10 items, so 15 were silently discarded.', correct: false, why: 'The limit is 25 items or 16 MB, and exceeding it raises a validation error rather than discarding items.' },
      { id: 'C', text: 'The writes need a ConditionExpression to be durable.', correct: false, why: 'A condition controls whether a write is allowed, not whether it persists — and BatchWriteItem does not support conditions.' },
      { id: 'D', text: 'The table is eventually consistent for writes, so the items will appear later.', correct: false, why: 'DynamoDB writes are durable and immediately visible to a strongly consistent read once acknowledged. Consistency applies to reads.' },
    ],
    explanation:
      'Both batch APIs return a partial-failure map: UnprocessedItems for BatchWriteItem, UnprocessedKeys for BatchGetItem. Ignoring them is one of the most common real-world DynamoDB bugs, and it is examined.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html',
  },
  {
    id: 'dva-d1-030',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb'],
    stem: 'A retried TransactWriteItems call must not apply the same transaction twice when the client times out and retries. What supports this?',
    options: [
      { id: 'A', text: 'Supply a ClientRequestToken — DynamoDB treats a repeated call with the same token within about 10 minutes as idempotent.', correct: true, why: 'The token makes the transaction idempotent for the duration of the idempotency window, which is exactly the timeout-and-retry case.' },
      { id: 'B', text: 'Wrap each item write in its own ConditionExpression.', correct: false, why: 'Conditions guard state and would make the retry fail rather than succeed idempotently, which is not the same outcome.' },
      { id: 'C', text: 'Enable DynamoDB Streams and deduplicate downstream.', correct: false, why: 'That handles duplicate consumers, not a duplicate write.' },
      { id: 'D', text: 'Use BatchWriteItem instead, which is idempotent.', correct: false, why: 'BatchWriteItem is neither atomic nor idempotent, and a duplicate PutItem simply overwrites.' },
    ],
    explanation:
      'TransactWriteItems: up to 100 items, 4 MB, all-or-nothing, consumes twice the capacity of a normal write, and idempotent via ClientRequestToken. Those four facts answer most transaction questions.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html',
  },
  {
    id: 'dva-d1-031',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A nightly export must read every item in a 500 GB table as quickly as possible from a fleet of workers, without affecting a live workload beyond a known capacity share.',
    options: [
      { id: 'A', text: 'A parallel Scan, with each worker passing a distinct Segment and the same TotalSegments.', correct: true, why: 'Parallel scan divides the table between workers so they read different partitions concurrently, and the number of segments plus rate limiting bounds the capacity consumed.' },
      { id: 'B', text: 'A Query with no key condition, run once per worker.', correct: false, why: 'Query requires a partition key value; it cannot read a whole table.' },
      { id: 'C', text: 'A sequential Scan with a large Limit value.', correct: false, why: 'Limit caps items per page and the scan is still single-threaded, so it will not be as fast as possible.' },
      { id: 'D', text: 'Repeated BatchGetItem calls covering all keys.', correct: false, why: 'It needs every key in advance, which is the thing the export is trying to discover.' },
    ],
    explanation:
      'Scan reads everything and is a last resort. When it is genuinely needed, parallelise with Segment and TotalSegments — and consider a DynamoDB export to S3 instead, which consumes no table capacity at all.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html',
  },
  {
    id: 'dva-d1-032',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb', 's3'],
    stem: 'Each record must store a 2 MB JSON document alongside about 20 queryable attributes. Writes fail with a validation error about item size.',
    options: [
      { id: 'A', text: 'Store the document in S3 and keep an object key pointer in the item, leaving the queryable attributes in DynamoDB.', correct: true, why: 'The DynamoDB item size limit is 400 KB including attribute names. The standard pattern is metadata in the table, payload in S3.' },
      { id: 'B', text: 'Split the document across several items sharing a partition key.', correct: false, why: 'It technically fits and makes every read a multi-item reassembly, and a 2 MB read consumes far more capacity than an S3 GET.' },
      { id: 'C', text: 'Compress the document with gzip before writing.', correct: false, why: 'It may fit today and reintroduces the failure as documents grow, while making the payload unqueryable anyway.' },
      { id: 'D', text: 'Request a limit increase for maximum item size.', correct: false, why: 'The 400 KB item size limit is a hard limit and cannot be raised.' },
    ],
    explanation:
      'Hard DynamoDB numbers: 400 KB per item, 1 MB per read page, 2,048 bytes for a partition key, 1,024 for a sort key. The 400 KB one always points at the S3-pointer pattern.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html',
  },
  {
    id: 'dva-d1-033',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A sign-up flow must guarantee that a username is claimed only once, even if two requests arrive simultaneously. The username is the partition key.',
    options: [
      { id: 'A', text: 'PutItem with ConditionExpression attribute_not_exists(username), treating ConditionalCheckFailedException as "already taken".', correct: true, why: 'The condition is evaluated atomically on the item, so exactly one of two concurrent writes succeeds and the other fails deterministically.' },
      { id: 'B', text: 'GetItem to check, then PutItem if absent.', correct: false, why: 'Classic check-then-act race: both requests can read "absent" before either writes.' },
      { id: 'C', text: 'PutItem twice and compare the returned attributes.', correct: false, why: 'PutItem overwrites by default, so both succeed and the first registration is lost.' },
      { id: 'D', text: 'A strongly consistent Query before the write.', correct: false, why: 'Strong consistency guarantees a fresh read, not that nothing changes between the read and the write.' },
    ],
    explanation:
      'Conditional writes are the only atomic primitive on a single item, and attribute_not_exists is how you express uniqueness, create-if-absent and optimistic locking.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html',
  },
  {
    id: 'dva-d1-034',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A Query returns items with 30 attributes each, but the screen needs only three of them. Read capacity consumption is higher than the team expects and they want to reduce it.',
    options: [
      { id: 'A', text: 'A ProjectionExpression reduces the data transferred but not the capacity consumed — the fix is a GSI projecting only the needed attributes and querying that.', correct: true, why: 'Capacity is charged on the item size read from the table regardless of projection, so the only way to read less is to read a smaller index item.' },
      { id: 'B', text: 'Add a ProjectionExpression naming the three attributes, which reduces consumed capacity proportionally.', correct: false, why: 'It cuts network transfer and parsing only; DynamoDB has already read the whole item to filter it.' },
      { id: 'C', text: 'Add a FilterExpression on the three attributes.', correct: false, why: 'Filters are applied after the read, so consumed capacity is unchanged — the same trap in a different shape.' },
      { id: 'D', text: 'Switch to eventually consistent reads with a Limit.', correct: false, why: 'Eventual consistency halves the cost per read unit, and it does not address reading 30 attributes to display three.' },
    ],
    explanation:
      'ProjectionExpression and FilterExpression both act after DynamoDB has read the item, so neither saves capacity. Reading less means storing less in the index you read — a KEYS_ONLY or INCLUDE projection.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general.html',
  },
  {
    id: 'dva-d1-035',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'lambda', 'eventbridge'],
    stem: 'A function is triggered by S3 object-created notifications. Occasionally it runs twice for the same object, and duplicate rows appear downstream.',
    options: [
      { id: 'A', text: 'S3 event notification delivery is at-least-once, so the consumer must be idempotent — key the downstream write on bucket, key and version id.', correct: true, why: 'AWS documents that notifications are typically delivered once but occasionally more than once, so duplicate handling belongs in the consumer.' },
      { id: 'B', text: 'Two overlapping notification configurations exist and one should be removed.', correct: false, why: 'Worth checking, and S3 rejects overlapping configurations for the same prefix, suffix and event type.' },
      { id: 'C', text: 'The function is timing out and being retried, which can be fixed by raising the timeout.', correct: false, why: 'Retry on failure is one source of duplicates, but the at-least-once guarantee means duplicates occur even on success.' },
      { id: 'D', text: 'Enabling S3 versioning will deduplicate the events.', correct: false, why: 'Versioning gives you a version id useful as an idempotency key; it does not reduce event delivery.' },
    ],
    explanation:
      'Nearly every AWS event source is at-least-once: S3 notifications, SNS, standard SQS, EventBridge, Lambda asynchronous retries. Idempotency is not optional in event-driven design.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventNotifications.html',
  },
  {
    id: 'dva-d1-036',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway'],
    stem: 'A browser application on https://app.example.com calls a REST API with Lambda proxy integration and fails with a CORS error. The team has enabled CORS on the resource in the console. What else is required?',
    options: [
      { id: 'A', text: 'The Lambda function must return the Access-Control-Allow-Origin header itself, because with proxy integration the function owns the response headers.', correct: true, why: 'Enabling CORS creates the OPTIONS preflight method, but for a proxy integration API Gateway passes the function response through unchanged — so the actual response headers come from the function.' },
      { id: 'B', text: 'The API must be redeployed to the stage for the CORS change to take effect, which is all that is missing.', correct: false, why: 'Deployment is genuinely required for the OPTIONS method, and the non-preflight response headers still come from the function.' },
      { id: 'C', text: 'A gateway response mapping for DEFAULT_4XX is the only supported way to add the header.', correct: false, why: 'That is needed so error responses also carry CORS headers — a useful refinement, not the cause here.' },
      { id: 'D', text: 'CORS is not supported with Lambda proxy integration; a non-proxy integration is required.', correct: false, why: 'It is fully supported; the function is simply responsible for the headers.' },
    ],
    explanation:
      'Preflight OPTIONS is configuration; the headers on the real response are the integration\'s job. With proxy integration that means your code — and remember gateway responses for the 4xx and 5xx paths.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html',
  },
  {
    id: 'dva-d1-037',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['api-gateway'],
    stem: 'A REST API stage has caching enabled with a 300-second TTL. After a data fix, support staff need one specific resource\'s cached entry cleared without flushing the whole cache or waiting.',
    options: [
      { id: 'A', text: 'Send the request with a Cache-Control: max-age=0 header from a caller granted InvalidateCache permission on that resource.', correct: true, why: 'That header invalidates the entry for that cache key, and the stage can be configured to require the apigateway:InvalidateCache permission so any caller cannot do it.' },
      { id: 'B', text: 'Flush the entire stage cache from the console.', correct: false, why: 'It clears the entry and everything else, which the question explicitly excludes.' },
      { id: 'C', text: 'Reduce the stage TTL to zero and raise it again.', correct: false, why: 'That disables caching for every resource while it is applied and requires two deployments.' },
      { id: 'D', text: 'Add the resource to a cache key parameter list.', correct: false, why: 'Cache key parameters decide what makes an entry distinct, not how an entry is removed.' },
    ],
    explanation:
      'API Gateway caching is per stage, sized in GB, keyed on the request parameters you nominate, and invalidated per entry with Cache-Control: max-age=0 — which should be permission-gated.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-caching.html',
  },
  {
    id: 'dva-d1-038',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['step-functions', 'lambda'],
    stem: 'A state machine calls a third-party API that returns HTTP 429 intermittently. The workflow should retry with increasing delays, and if it still fails, run a compensating step rather than aborting.',
    options: [
      { id: 'A', text: 'A Retry block with IntervalSeconds, MaxAttempts and BackoffRate on the task, plus a Catch block routing the error to the compensating state.', correct: true, why: 'Retry handles transient failure with exponential backoff, and Catch handles the terminal case by transitioning rather than failing the execution.' },
      { id: 'B', text: 'Retry logic inside the Lambda function with a sleep loop.', correct: false, why: 'You pay Lambda duration to sleep, and the state machine loses visibility into the retries.' },
      { id: 'C', text: 'A Choice state examining the HTTP status and looping back.', correct: false, why: 'It can be built by hand and reimplements backoff and attempt counting that Retry expresses declaratively.' },
      { id: 'D', text: 'A Wait state before the task to slow the workflow down.', correct: false, why: 'A fixed delay on every execution, whether or not the call fails.' },
    ],
    explanation:
      'Retry then Catch is the Step Functions error idiom, and the reason to orchestrate rather than chain functions: the retry policy, the timeout and the fallback path are visible in the definition, not buried in code.',
    source: 'https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html',
  },
  {
    id: 'dva-d1-039',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kinesis-data-streams', 'lambda'],
    stem: 'Three consumers read the same Kinesis stream. As the third was added, all of them began seeing ReadProvisionedThroughputExceeded and rising propagation delay.',
    options: [
      { id: 'A', text: 'Register the consumers for enhanced fan-out, giving each a dedicated 2 MB/s per shard read throughput over SubscribeToShard.', correct: true, why: 'Standard consumers share 2 MB/s per shard between them; enhanced fan-out gives each consumer its own pipe and pushes records with lower latency.' },
      { id: 'B', text: 'Increase the shard count to triple the read capacity.', correct: false, why: 'It raises total throughput and costs more, and shared-throughput consumers still contend on every shard.' },
      { id: 'C', text: 'Increase the stream retention period.', correct: false, why: 'Retention governs how long records are available, not read throughput.' },
      { id: 'D', text: 'Have the consumers poll less frequently with a larger batch size.', correct: false, why: 'It reduces GetRecords calls and worsens the propagation delay the question is complaining about.' },
    ],
    explanation:
      'Per shard: 1 MB/s or 1,000 records in, 2 MB/s out shared across standard consumers, or 2 MB/s each for up to 20 enhanced fan-out consumers. Multiple consumers on one stream is the enhanced fan-out signal.',
    source: 'https://docs.aws.amazon.com/streams/latest/dev/enhanced-consumers.html',
  },
  {
    id: 'dva-d1-040',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['eventbridge', 'lambda'],
    stem: 'A function must run once for each of about 40,000 customers at a customer-specific local time, and the schedules change daily. The team does not want 40,000 EventBridge rules.',
    options: [
      { id: 'A', text: 'EventBridge Scheduler, which supports one-time and recurring schedules at scale with time zones and can be created and deleted through its API.', correct: true, why: 'Scheduler is built for large numbers of fine-grained, programmatically managed schedules with time-zone support, unlike the rule quota on an event bus.' },
      { id: 'B', text: 'One EventBridge rule per customer with a cron expression.', correct: false, why: 'This is the approach the question rules out, and rules per bus are quota-limited well below 40,000.' },
      { id: 'C', text: 'A single rule running every minute, with the function scanning for due customers.', correct: false, why: 'It works and costs an invocation and a scan every minute, and the "due" logic becomes yours to get right.' },
      { id: 'D', text: 'Step Functions Wait states, one execution per customer.', correct: false, why: 'Feasible for a bounded set and it means 40,000 long-running executions to manage and re-create daily.' },
    ],
    explanation:
      'EventBridge rules for reacting to events and a handful of crons. EventBridge Scheduler for many schedules, time zones, flexible time windows and per-schedule management through an API.',
    source: 'https://docs.aws.amazon.com/scheduler/latest/UserGuide/what-is-scheduler.html',
  },
  {
    id: 'dva-d1-041',
    families: ['dva'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['appsync', 'api-gateway'],
    stem: 'A collaborative editor needs clients to receive updates pushed from the server the moment another user changes a document, with each client subscribing only to the documents it has open, over a schema-typed API.',
    options: [
      { id: 'A', text: 'AWS AppSync with GraphQL subscriptions, which push over WebSockets to clients subscribed to a given mutation.', correct: true, why: 'Subscriptions are AppSync\'s real-time primitive, filtered per client argument, and the GraphQL schema provides the typing.' },
      { id: 'B', text: 'An API Gateway REST API polled every second.', correct: false, why: 'Polling is neither instant nor cheap at editor scale, and it is not server-push.' },
      { id: 'C', text: 'An API Gateway WebSocket API with routes implemented in Lambda.', correct: false, why: 'It genuinely supports push and leaves connection registry, fan-out and subscription filtering for you to build, which AppSync provides.' },
      { id: 'D', text: 'SNS mobile push notifications to each client.', correct: false, why: 'SNS push targets device notification services; it is not an in-application data channel.' },
    ],
    explanation:
      'AppSync when the requirement mentions GraphQL, per-client subscriptions or offline sync. API Gateway WebSocket when you need a raw bidirectional channel and will build the routing yourself.',
    source: 'https://docs.aws.amazon.com/appsync/latest/devguide/aws-appsync-real-time-data.html',
  },
  {
    id: 'dva-d1-042',
    families: ['dva'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['aurora-serverless', 'lambda', 'rds-proxy'],
    stem: 'A Lambda function must query an Aurora PostgreSQL cluster. The team wants no VPC configuration on the function, no connection pooling to manage, and IAM-based access.',
    options: [
      { id: 'A', text: 'Call the cluster through the RDS Data API, which is an HTTPS endpoint authorised by IAM with credentials from Secrets Manager.', correct: true, why: 'The Data API removes persistent connections entirely, so the function needs no VPC attachment and no pool, and access is IAM-authorised.' },
      { id: 'B', text: 'Attach the function to the VPC and use RDS Proxy.', correct: false, why: 'The standard answer when a driver connection is needed, and it requires exactly the VPC configuration the question excludes.' },
      { id: 'C', text: 'Open the cluster to public access and connect over the internet.', correct: false, why: 'It removes the VPC requirement by exposing the database, which is unacceptable.' },
      { id: 'D', text: 'Use DynamoDB instead.', correct: false, why: 'A change of database rather than an answer to how to reach this one.' },
    ],
    explanation:
      'Three ways for Lambda to reach a relational database: direct in-VPC (simplest, exhausts connections), RDS Proxy (pooling and failover, still in-VPC), Data API (no VPC, no connections, HTTPS and IAM).',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html',
  },
]
