import type { Question } from '../schema'

/**
 * DVA-C02. A build-and-debug paper, not an architecture paper — it wants the
 * specific setting, the specific API call, the specific error. Lambda and
 * DynamoDB carry most of the weight.
 */
export const dvaQuestions: Question[] = [
  /* ── Domain 1: Development with AWS Services (32%) ────────────────────── */
  {
    id: 'dva-d1-001',
    certs: ['DVA-C02'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function opens a database connection on every invocation and is exhausting the connection pool under load. Where should the connection be created?',
    options: [
      { id: 'A', text: 'Outside the handler, in the initialisation code, so it is reused across invocations in the same execution environment.', correct: true, why: 'Initialisation code runs once per execution environment, not once per invocation, so warm invocations reuse the connection. This is asked directly on DVA.' },
      { id: 'B', text: 'Inside the handler, but closed in a finally block.', correct: false, why: 'It avoids leaks but still pays connection setup on every single invocation, which is the cost being complained about.' },
      { id: 'C', text: 'In a Lambda layer, so it is shared between functions.', correct: false, why: 'Layers ship code and dependencies. They do not share runtime state between functions.' },
      { id: 'D', text: 'In a Lambda extension running as a separate process.', correct: false, why: 'Extensions are for telemetry and lifecycle hooks, not for sharing application database connections.' },
    ],
    explanation:
      'Anything expensive and reusable — SDK clients, connection pools, parsed configuration — belongs outside the handler. For relational databases, add RDS Proxy as well.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html',
  },
  {
    id: 'dva-d1-002',
    certs: ['DVA-C02'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A DynamoDB Query returns 40 items when the developer expects 900. No error is raised. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The 1 MB result-page limit was reached and the code is not following LastEvaluatedKey to fetch subsequent pages.', correct: true, why: 'Query returns at most 1 MB per call and signals more results with LastEvaluatedKey. Ignoring it silently truncates the result set.' },
      { id: 'B', text: 'The table has insufficient read capacity, so items were dropped.', correct: false, why: 'Insufficient capacity produces a ProvisionedThroughputExceededException, not silently missing items.' },
      { id: 'C', text: 'Eventually consistent reads returned stale data.', correct: false, why: 'Eventual consistency can return slightly stale values, not a truncated count of this magnitude.' },
      { id: 'D', text: 'The FilterExpression removed the other items before they were read.', correct: false, why: 'A filter is applied after the read, and it would explain fewer items only if a filter were present — the far more common cause is pagination.' },
    ],
    explanation:
      'Every DynamoDB read API paginates at 1 MB. Use the SDK paginators, or loop on LastEvaluatedKey — "fewer results than expected" is nearly always this.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html',
  },
  {
    id: 'dva-d1-003',
    certs: ['DVA-C02'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'Two clients read the same DynamoDB item and both write an update. One update is silently lost. Which mechanism prevents this?',
    options: [
      { id: 'A', text: 'A conditional write using a version attribute — optimistic locking.', correct: true, why: 'A ConditionExpression asserting the version has not changed makes the second write fail rather than overwrite, and the client can retry with fresh data.' },
      { id: 'B', text: 'Strongly consistent reads on both clients.', correct: false, why: 'It guarantees each client reads the latest value, but does nothing to stop the second write overwriting the first.' },
      { id: 'C', text: 'A DynamoDB transaction wrapping each individual write.', correct: false, why: 'Transactions give atomicity across items. A single-item write is already atomic — the problem is the lost update, not partial writes.' },
      { id: 'D', text: 'Enabling DynamoDB Streams to detect the conflict afterwards.', correct: false, why: 'Streams let you observe what happened; they do not prevent it.' },
    ],
    explanation:
      'Optimistic locking with a version attribute plus a ConditionExpression is the standard DynamoDB answer to concurrent updates.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html',
  },
  {
    id: 'dva-d1-004',
    certs: ['DVA-C02'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function has reserved concurrency of 5. During a traffic burst, callers receive 429 TooManyRequestsException. The account concurrency limit is 1,000 and is not near being reached. What explains this?',
    options: [
      { id: 'A', text: 'Reserved concurrency also acts as a maximum, capping this function at 5 concurrent executions.', correct: true, why: 'Reserved concurrency does two things at once: it guarantees that much capacity and it caps the function at exactly that number. This dual behaviour is examined directly.' },
      { id: 'B', text: 'Reserved concurrency only guarantees a minimum, so the cause must be the account limit.', correct: false, why: 'It is a hard ceiling as well as a floor, and the question states the account limit is not the constraint.' },
      { id: 'C', text: 'Provisioned concurrency needs to be enabled to remove throttling.', correct: false, why: 'Provisioned concurrency pre-warms environments to remove cold starts. It does not raise the reserved ceiling.' },
      { id: 'D', text: 'The function timeout is too short, so invocations are being rejected.', correct: false, why: 'A short timeout produces a task-timeout error inside the invocation, not a 429 at the API boundary.' },
    ],
    explanation:
      'Reserved concurrency = guarantee *and* cap. Provisioned concurrency = pre-warmed environments to remove cold starts. Two different settings, constantly confused.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html',
  },
  {
    id: 'dva-d1-005',
    certs: ['DVA-C02'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'sqs'],
    stem: 'A Lambda function is invoked asynchronously by S3 events. Some events appear to be lost when the function throws an error. What should be configured to capture them?',
    options: [
      { id: 'A', text: 'An on-failure destination or a dead-letter queue on the function.', correct: true, why: 'Asynchronous invocations retry twice more and then discard the event unless a DLQ or on-failure destination is configured to receive it.' },
      { id: 'B', text: 'Increase the function timeout so it has more time to succeed.', correct: false, why: 'The function is erroring, not timing out. The event is still discarded after retries.' },
      { id: 'C', text: 'Enable S3 versioning so the event can be replayed.', correct: false, why: 'Versioning preserves objects, not the notification events derived from them.' },
      { id: 'D', text: 'Switch to synchronous invocation so the caller can retry.', correct: false, why: 'S3 event notifications to Lambda are asynchronous; this is not a configurable choice.' },
    ],
    explanation:
      'Async: two extra retries, then a DLQ or destination or the event is gone. Sync: no retries at all — the caller owns the retry.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html',
  },
  {
    id: 'dva-d1-006',
    certs: ['DVA-C02'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sdk', 'dynamodb'],
    stem: 'An application calling DynamoDB intermittently receives ProvisionedThroughputExceededException. What is the appropriate first response in the application code?',
    options: [
      { id: 'A', text: 'Rely on the SDK\'s built-in exponential backoff with jitter, and raise the retry configuration if needed.', correct: true, why: 'The AWS SDKs already implement exponential backoff with jitter for throttling errors. Hand-rolling it is the wrong answer; tuning maxAttempts or the retry mode is right.' },
      { id: 'B', text: 'Write a custom retry loop with a fixed 100 ms delay.', correct: false, why: 'A fixed delay from many clients synchronises retries and makes throttling worse. Jitter exists specifically to avoid this.' },
      { id: 'C', text: 'Catch the exception and return an error to the user immediately.', correct: false, why: 'Throttling is transient by nature, so failing straight through discards a request that would likely succeed on retry.' },
      { id: 'D', text: 'Switch every read to eventually consistent to halve the capacity used.', correct: false, why: 'Sometimes a valid optimisation, but it changes consistency semantics and does not address transient throttling properly.' },
    ],
    explanation:
      'The SDKs retry throttling errors with exponential backoff and jitter by default. Answers that propose writing your own are usually wrong on DVA.',
    source: 'https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html',
  },
  {
    id: 'dva-d1-007',
    certs: ['DVA-C02'],
    taskId: 'dva-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'vpc', 'privatelink'],
    stem: 'A Lambda function is configured for VPC access so it can reach an RDS instance in a private subnet. It now times out calling the public Stripe API. What is the cause and the cheapest fix for AWS API calls made by the same function?',
    options: [
      { id: 'A', text: 'A private subnet has no internet route, so the function needs a NAT gateway for third-party APIs — and VPC interface endpoints are cheaper for AWS service calls.', correct: true, why: 'Attaching a function to a VPC removes its default internet access. Third-party APIs need NAT; AWS APIs are better served by endpoints, which avoid the per-GB NAT charge.' },
      { id: 'B', text: 'The function needs a public IP address assigned.', correct: false, why: 'Lambda ENIs cannot be given public IP addresses. Egress must go through NAT.' },
      { id: 'C', text: 'The function\'s security group needs an inbound rule for the Stripe API.', correct: false, why: 'Outbound calls need an outbound rule, and security groups are stateful so the reply is automatic. This is a routing problem, not a filtering one.' },
      { id: 'D', text: 'The function should be removed from the VPC entirely.', correct: false, why: 'It would restore internet access but break the private RDS connection the VPC attachment exists for.' },
    ],
    explanation:
      'A VPC-attached Lambda has private-subnet networking, with all that implies. This is one of the most common real-world Lambda surprises and a recurring exam item.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/foundation-networking.html',
  },
  {
    id: 'dva-d1-008',
    certs: ['DVA-C02'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda'],
    stem: 'An API Gateway REST API with Lambda proxy integration returns HTTP 502 Bad Gateway. The function logs show it completed successfully. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The function is not returning the response shape Lambda proxy integration requires, with statusCode and body.', correct: true, why: 'Proxy integration requires a specific JSON envelope. A function that returns a bare object succeeds internally, and API Gateway cannot translate it — producing a 502.' },
      { id: 'B', text: 'The function exceeded the 29-second integration timeout.', correct: false, why: 'That produces a 504 Gateway Timeout, not a 502.' },
      { id: 'C', text: 'API Gateway is being throttled.', correct: false, why: 'Throttling returns 429 Too Many Requests.' },
      { id: 'D', text: 'The API Gateway execution role lacks lambda:InvokeFunction.', correct: false, why: 'That produces a 500 with an authorisation error, and the function would never run at all.' },
    ],
    explanation:
      'Know the codes: 502 malformed response, 504 integration timeout, 429 throttling, 403 authoriser rejection. DVA asks these directly.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html',
  },
  {
    id: 'dva-d1-009',
    certs: ['DVA-C02'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A table must automatically delete session records 30 days after creation, at no additional cost. What should be used?',
    options: [
      { id: 'A', text: 'Enable TTL on an attribute holding the expiry time as a Unix epoch timestamp.', correct: true, why: 'TTL deletes expired items with no write capacity consumed and no cost. Deletion happens within about 48 hours of expiry rather than instantly.' },
      { id: 'B', text: 'A scheduled Lambda function scanning for old items and deleting them.', correct: false, why: 'It works but consumes read and write capacity, and a full-table scan is exactly the access pattern to avoid.' },
      { id: 'C', text: 'A DynamoDB Streams consumer that deletes items after 30 days.', correct: false, why: 'Streams have a 24-hour retention, so a 30-day delay cannot be driven from them.' },
      { id: 'D', text: 'An S3 lifecycle rule on the table\'s backups.', correct: false, why: 'Lifecycle rules apply to S3 objects, not DynamoDB items.' },
    ],
    explanation:
      'TTL is free and the intended answer for expiring data. Note that deletion is eventual — filter expired items in queries if precision matters.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html',
  },
  {
    id: 'dva-d1-010',
    certs: ['DVA-C02'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'lambda'],
    stem: 'A Lambda function processes SQS messages in batches of 10. When one message in a batch fails, all 10 are redelivered and the successful nine are processed again. What should be configured?',
    options: [
      { id: 'A', text: 'Enable ReportBatchItemFailures on the event source mapping and return the failed message identifiers from the handler.', correct: true, why: 'Partial batch response makes only the failed messages become visible again, so successful ones are not reprocessed.' },
      { id: 'B', text: 'Reduce the batch size to 1.', correct: false, why: 'It solves the symptom by giving up batching entirely, raising invocation count and cost.' },
      { id: 'C', text: 'Increase the visibility timeout.', correct: false, why: 'That addresses duplicate processing from timeouts, not partial batch failure.' },
      { id: 'D', text: 'Switch to a FIFO queue.', correct: false, why: 'FIFO makes it worse — a failing message blocks its entire message group.' },
    ],
    explanation:
      'ReportBatchItemFailures is the specific fix for partial batch failure, and it applies to SQS, Kinesis and DynamoDB Streams event sources.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html',
  },
  {
    id: 'dva-d1-011',
    certs: ['DVA-C02'],
    taskId: 'dva-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['step-functions', 'lambda'],
    stem: 'A workflow must pause until a human approves a request, which may take days, then continue. What Step Functions pattern should be used?',
    options: [
      { id: 'A', text: 'A task with .waitForTaskToken, resumed by a call to SendTaskSuccess when the approval arrives.', correct: true, why: 'The callback pattern suspends the execution — for up to a year on a Standard workflow — until something external returns the task token.' },
      { id: 'B', text: 'A Wait state with a long timeout, polling an approvals table.', correct: false, why: 'Wastes state transitions polling, and requires guessing the delay in advance.' },
      { id: 'C', text: 'An Express workflow with a long timeout.', correct: false, why: 'Express workflows are capped at five minutes, so days of waiting is impossible.' },
      { id: 'D', text: 'A Lambda function that sleeps until approval is received.', correct: false, why: 'Lambda caps at 15 minutes, and paying to sleep is exactly what workflow state exists to avoid.' },
    ],
    explanation:
      '.waitForTaskToken is the human-in-the-loop pattern. Standard workflows for anything long or requiring exactly-once; Express for high-volume short executions.',
    source: 'https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html',
  },
  {
    id: 'dva-d1-012',
    certs: ['DVA-C02'],
    taskId: 'dva-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb'],
    stem: 'A developer adds a GSI to a busy table. Shortly afterwards, writes to the base table begin to throttle, though the base table\'s own capacity is ample. Why?',
    options: [
      { id: 'A', text: 'The GSI has insufficient write capacity, and a throttled index throttles writes to the base table.', correct: true, why: 'Every base-table write that affects an indexed attribute must also write to the GSI. If the index cannot keep up, the base write fails.' },
      { id: 'B', text: 'GSIs are eventually consistent, so writes queue until the index catches up.', correct: false, why: 'Eventual consistency describes reads of the index, not back-pressure on writes.' },
      { id: 'C', text: 'The GSI must use the same partition key as the base table, and the mismatch causes throttling.', correct: false, why: 'A GSI is specifically allowed a different partition key — that is the whole point of it.' },
      { id: 'D', text: 'Adding a GSI requires a table rebuild, during which writes are throttled.', correct: false, why: 'A GSI backfills online without blocking writes.' },
    ],
    explanation:
      'An under-provisioned GSI breaks the base table. This surprises people and is examined directly — provision indexes as carefully as tables.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html',
  },

  /* ── Domain 2: Security (26%) ─────────────────────────────────────────── */
  {
    id: 'dva-d2-001',
    certs: ['DVA-C02'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cognito'],
    stem: 'A mobile app must let users sign in with email and password, then upload files directly to S3 using scoped AWS credentials. Which Cognito components are needed?',
    options: [
      { id: 'A', text: 'A user pool for authentication and an identity pool to exchange the resulting token for temporary AWS credentials.', correct: true, why: 'The user pool is the directory that authenticates; the identity pool calls STS to convert that token into scoped AWS credentials the client can use against S3.' },
      { id: 'B', text: 'A user pool only — its tokens can be used directly as AWS credentials.', correct: false, why: 'A user pool issues JWTs for your application, not SigV4 credentials for AWS APIs.' },
      { id: 'C', text: 'An identity pool only, with users created inside it.', correct: false, why: 'Identity pools do not store users or handle sign-in; they federate an existing identity.' },
      { id: 'D', text: 'A user pool plus an IAM user per application user.', correct: false, why: 'IAM users are for AWS principals, never for application customers.' },
    ],
    explanation:
      'User pool = who you are. Identity pool = what AWS credentials you get. Questions needing both sign-in and direct AWS access need both.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html',
  },
  {
    id: 'dva-d2-002',
    certs: ['DVA-C02'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kms'],
    stem: 'An application must encrypt 50 MB files before storing them in S3, using a key managed in KMS. What is the correct approach?',
    options: [
      { id: 'A', text: 'Envelope encryption: call GenerateDataKey, encrypt the file locally with the plaintext data key, and store the encrypted data key alongside the ciphertext.', correct: true, why: 'KMS can only encrypt up to 4 KB directly. Envelope encryption is the designed pattern, and KMS never sees the bulk data.' },
      { id: 'B', text: 'Call kms:Encrypt with the file contents as the plaintext parameter.', correct: false, why: 'The Encrypt API rejects payloads over 4 KB, so a 50 MB file cannot be passed to it.' },
      { id: 'C', text: 'Split the file into 4 KB chunks and call kms:Encrypt on each.', correct: false, why: 'Technically possible and completely impractical — 12,800 API calls per file, and reassembly complexity for no benefit.' },
      { id: 'D', text: 'Store the KMS key material in the application and encrypt locally.', correct: false, why: 'KMS key material never leaves KMS. That is the security property the service exists to provide.' },
    ],
    explanation:
      'The 4 KB limit is why envelope encryption exists. SSE-KMS on S3 does this for you; client-side encryption means doing it explicitly.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html',
  },
  {
    id: 'dva-d2-003',
    certs: ['DVA-C02'],
    taskId: 'dva-2.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['secrets-manager', 'lambda'],
    stem: 'A Lambda function currently reads a database password from a plaintext environment variable. Security requires that the credential be encrypted at rest, rotated automatically, and not visible to anyone who can view the function configuration. What should be used?',
    options: [
      { id: 'A', text: 'Store the credential in AWS Secrets Manager with rotation enabled, and retrieve it at run time using the execution role.', correct: true, why: 'It is encrypted with KMS, rotated on a schedule, and never appears in the function configuration where anyone with lambda:GetFunction could read it.' },
      { id: 'B', text: 'Encrypt the environment variable with a KMS key and decrypt it in the handler.', correct: false, why: 'Better than plaintext, but there is still no rotation, and the ciphertext remains in the function configuration.' },
      { id: 'C', text: 'Store it in an SSM Parameter Store String parameter.', correct: false, why: 'A String parameter is not encrypted at all. SecureString would encrypt but still would not rotate.' },
      { id: 'D', text: 'Pass the credential in the event payload from the caller.', correct: false, why: 'It moves the secret into logs and traces, which is considerably worse.' },
    ],
    explanation:
      'Rotation is the discriminator. Cache the retrieved secret outside the handler so you are not calling the API on every invocation.',
    source: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html',
  },
  {
    id: 'dva-d2-004',
    certs: ['DVA-C02'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'cognito', 'lambda'],
    stem: 'An API must be authorised using a third-party OIDC provider\'s JWTs, with custom logic that checks a claim against a DynamoDB allow-list. Which API Gateway authoriser fits?',
    options: [
      { id: 'A', text: 'A Lambda authoriser, which can validate the token and run arbitrary authorisation logic.', correct: true, why: 'Custom logic beyond token validation — such as a database lookup — is precisely what a Lambda authoriser is for, and its result can be cached.' },
      { id: 'B', text: 'A Cognito user pool authoriser.', correct: false, why: 'That validates tokens issued by a Cognito user pool, not a third-party provider, and cannot run custom logic.' },
      { id: 'C', text: 'IAM authorisation with SigV4 signing.', correct: false, why: 'That authenticates AWS principals, not application users holding OIDC tokens.' },
      { id: 'D', text: 'A resource policy on the API restricting source IPs.', correct: false, why: 'Network-level restriction, unrelated to token-based authorisation.' },
    ],
    explanation:
      'Cognito token → Cognito authoriser. Third-party token or custom logic → Lambda authoriser. AWS principal → IAM.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html',
  },
  {
    id: 'dva-d2-005',
    certs: ['DVA-C02'],
    taskId: 'dva-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kms', 's3'],
    stem: 'Account A must let a role in Account B decrypt objects in an S3 bucket encrypted with a customer managed KMS key in Account A. What must be configured?',
    options: [
      { id: 'A', text: 'The bucket policy must allow the Account B role, the KMS key policy must allow it kms:Decrypt, and Account B\'s identity policy must allow both actions.', correct: true, why: 'Three policies must all agree: the resource policy, the key policy, and the caller\'s identity policy. Missing the key policy is the usual failure.' },
      { id: 'B', text: 'Only the bucket policy needs to allow the Account B role.', correct: false, why: 'The object cannot be decrypted without the key policy also permitting the role.' },
      { id: 'C', text: 'Only Account B\'s identity policy needs s3:GetObject and kms:Decrypt.', correct: false, why: 'Cross-account access needs the resource side to allow it too — an identity policy alone cannot reach into another account.' },
      { id: 'D', text: 'The key must be converted to an AWS managed key so it can be shared.', correct: false, why: 'AWS managed keys cannot be shared cross-account at all. Only customer managed keys can.' },
    ],
    explanation:
      'Cross-account plus SSE-KMS means three policies. The key policy is authoritative and is the one people forget.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/key-policy-modifying-external-accounts.html',
  },
  {
    id: 'dva-d2-006',
    certs: ['DVA-C02'],
    taskId: 'dva-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sts', 'iam'],
    stem: 'An application running on ECS Fargate must call an API in another AWS account. What is the correct approach?',
    options: [
      { id: 'A', text: 'Have the task role call sts:AssumeRole on a role in the target account whose trust policy allows the task role.', correct: true, why: 'Role assumption yields temporary credentials scoped to the target account, with both sides explicitly configured.' },
      { id: 'B', text: 'Store an IAM user\'s access keys for the target account in the task definition environment variables.', correct: false, why: 'Long-lived credentials visible to anyone who can describe the task definition.' },
      { id: 'C', text: 'Add the target account to the task execution role\'s policy.', correct: false, why: 'The execution role pulls images and writes logs; it is not the application\'s identity, and cross-account needs the target side too.' },
      { id: 'D', text: 'Enable cross-account access in the ECS cluster settings.', correct: false, why: 'No such setting exists.' },
    ],
    explanation:
      'Also worth knowing the ECS pair: the *execution* role pulls the image and writes logs; the *task* role is what your code uses.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html',
  },

  /* ── Domain 3: Deployment (24%) ───────────────────────────────────────── */
  {
    id: 'dva-d3-001',
    certs: ['DVA-C02'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codedeploy', 'lambda'],
    stem: 'A new Lambda version must receive 10% of traffic for five minutes, then all of it, rolling back automatically if the error rate rises. What should be configured?',
    options: [
      { id: 'A', text: 'A CodeDeploy deployment with the Canary10Percent5Minutes configuration and a CloudWatch alarm as the rollback trigger.', correct: true, why: 'That deployment configuration is literally 10% for five minutes then the remainder, and an alarm on the alias triggers automatic rollback.' },
      { id: 'B', text: 'A weighted alias split 10/90, adjusted manually after five minutes.', correct: false, why: 'It achieves the split but requires a human to complete the shift and to notice the errors.' },
      { id: 'C', text: 'The Linear10PercentEvery1Minute configuration.', correct: false, why: 'That shifts 10% every minute over ten minutes, which is not the pattern described.' },
      { id: 'D', text: 'A blue/green deployment on the function\'s $LATEST version.', correct: false, why: '$LATEST cannot be traffic-weighted; canary deployments require a published version behind an alias.' },
    ],
    explanation:
      'Canary means two jumps; linear means equal increments. Naming the specific configuration is a DVA habit worth having.',
    source: 'https://docs.aws.amazon.com/codedeploy/latest/userguide/deployment-configurations.html',
  },
  {
    id: 'dva-d3-002',
    certs: ['DVA-C02'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda'],
    stem: 'One API Gateway deployment must serve dev, test and prod, each invoking a different Lambda alias, without duplicating the API definition. What should be used?',
    options: [
      { id: 'A', text: 'Stage variables referencing the Lambda alias, with one stage per environment.', correct: true, why: 'A stage variable substituted into the integration URI lets a single API definition target a different alias per stage.' },
      { id: 'B', text: 'Three separate REST APIs, one per environment.', correct: false, why: 'Duplicates the definition, which the requirement excludes.' },
      { id: 'C', text: 'A Lambda authoriser that routes to the correct alias.', correct: false, why: 'An authoriser authorises; it does not choose integration targets.' },
      { id: 'D', text: 'Custom domain base-path mappings pointing at different functions.', correct: false, why: 'Base-path mappings route to stages, not to different integration targets within one stage.' },
    ],
    explanation:
      'Stage variables plus Lambda aliases is the DVA answer to environment-specific integrations from one API definition.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/stage-variables.html',
  },
  {
    id: 'dva-d3-003',
    certs: ['DVA-C02'],
    taskId: 'dva-3.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['sam'],
    stem: 'A developer wants to invoke a Lambda function locally with a test event, and run the API locally before deploying. What should be used?',
    options: [
      { id: 'A', text: 'AWS SAM CLI, using sam local invoke and sam local start-api.', correct: true, why: 'SAM CLI runs functions in a Docker container matching the Lambda runtime and can emulate API Gateway locally.' },
      { id: 'B', text: 'The AWS CLI with aws lambda invoke.', correct: false, why: 'That invokes the deployed function in AWS, not a local one.' },
      { id: 'C', text: 'AWS CloudShell with the function code uploaded.', correct: false, why: 'CloudShell is a remote shell, not a local Lambda emulator.' },
      { id: 'D', text: 'AWS CodeBuild with a buildspec that runs the handler.', correct: false, why: 'CodeBuild runs in AWS and is for building, not for local iteration.' },
    ],
    explanation:
      'SAM CLI is the local development loop: sam local invoke, sam local start-api, sam local generate-event. Docker is a prerequisite.',
    source: 'https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-invoke.html',
  },
  {
    id: 'dva-d3-004',
    certs: ['DVA-C02'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['appconfig'],
    stem: 'A team wants to enable a new feature for 10% of users, then all of them, rolling back automatically if the error metric rises — without deploying new code. What should be used?',
    options: [
      { id: 'A', text: 'AWS AppConfig feature flags with a gradual deployment strategy and a CloudWatch alarm for automatic rollback.', correct: true, why: 'AppConfig deploys configuration progressively, validates it, monitors an alarm, and rolls the configuration back on its own — all without a code deployment.' },
      { id: 'B', text: 'An SSM Parameter Store parameter read at start-up.', correct: false, why: 'It stores the flag but has no gradual rollout, no validation and no automatic rollback.' },
      { id: 'C', text: 'Lambda environment variables updated by a pipeline.', correct: false, why: 'Changing them is a function update — a deployment — which the requirement excludes.' },
      { id: 'D', text: 'A CodeDeploy canary deployment of the function.', correct: false, why: 'That deploys code; the requirement is to change behaviour without deploying.' },
    ],
    explanation:
      'Feature flags with gradual rollout and alarm-triggered rollback is the AppConfig signature. Parameter Store is the plausible distractor.',
    source: 'https://docs.aws.amazon.com/appconfig/latest/userguide/what-is-appconfig.html',
  },
  {
    id: 'dva-d3-005',
    certs: ['DVA-C02'],
    taskId: 'dva-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'ecr'],
    stem: 'A Lambda function needs a 600 MB machine-learning dependency. What packaging option supports this?',
    options: [
      { id: 'A', text: 'A container image in Amazon ECR, which supports images up to 10 GB.', correct: true, why: 'The .zip path caps at 250 MB unzipped. Container image packaging raises the ceiling to 10 GB.' },
      { id: 'B', text: 'A Lambda layer, which has its own separate size allowance.', correct: false, why: 'Layers count toward the same 250 MB unzipped limit, so they do not help here.' },
      { id: 'C', text: 'A .zip uploaded via S3 rather than directly.', correct: false, why: 'Uploading via S3 raises the *upload* limit but the 250 MB unzipped limit still applies.' },
      { id: 'D', text: 'Mount the dependency from EFS and keep the package small.', correct: false, why: 'Technically viable and a real pattern, but it adds VPC configuration and cold-start cost — container packaging is the direct answer.' },
    ],
    explanation:
      'The numbers matter: 50 MB zipped direct upload, 250 MB unzipped including layers, 10 GB as a container image.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html',
  },
  {
    id: 'dva-d3-006',
    certs: ['DVA-C02'],
    taskId: 'dva-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['codebuild', 'secrets-manager'],
    stem: 'A CodeBuild project needs a third-party API token during the build. It is currently a plaintext environment variable in the buildspec, visible in the console. What should be done?',
    options: [
      { id: 'A', text: 'Store the token in Secrets Manager and reference it with the SECRETS_MANAGER environment variable type.', correct: true, why: 'CodeBuild resolves the reference at build time, so the value never appears in the buildspec, the project configuration or the console.' },
      { id: 'B', text: 'Base64-encode the token in the buildspec.', correct: false, why: 'Encoding is not encryption — anyone reading the buildspec can decode it trivially.' },
      { id: 'C', text: 'Pass the token as a build override on every manual start.', correct: false, why: 'It breaks automated pipeline builds and puts the secret in command history.' },
      { id: 'D', text: 'Store it in the source repository in an encrypted file and decrypt during the build.', correct: false, why: 'Secrets in source control, plus a decryption key that must also be available. Worse on both counts.' },
    ],
    explanation:
      'CodeBuild supports PARAMETER_STORE and SECRETS_MANAGER variable types precisely so secrets stay out of the buildspec.',
    source: 'https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html',
  },

  /* ── Domain 4: Troubleshooting & Optimization (18%) ───────────────────── */
  {
    id: 'dva-d4-001',
    certs: ['DVA-C02'],
    taskId: 'dva-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['xray'],
    stem: 'A developer needs to search X-Ray traces for a specific customer id to investigate one customer\'s slow requests. How should the id be attached to the trace?',
    options: [
      { id: 'A', text: 'As an annotation, because annotations are indexed and can be used in filter expressions.', correct: true, why: 'Annotations are indexed key–value pairs and are the only thing X-Ray can filter on. This distinction is examined directly.' },
      { id: 'B', text: 'As metadata, which stores arbitrary data on the segment.', correct: false, why: 'Metadata is attached and visible but not indexed, so it cannot be searched or filtered.' },
      { id: 'C', text: 'In the segment name.', correct: false, why: 'Segment names identify the service, and a high-cardinality name would fragment the service map.' },
      { id: 'D', text: 'In a CloudWatch Logs entry correlated by timestamp.', correct: false, why: 'That is manual correlation, not trace filtering, and timestamps are unreliable as a join key.' },
    ],
    explanation:
      'Annotations are indexed and filterable; metadata is not. If a question says "filter traces by X", the answer is an annotation.',
    source: 'https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html',
  },
  {
    id: 'dva-d4-002',
    certs: ['DVA-C02'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch', 'lambda'],
    stem: 'A Lambda function must emit a custom business metric on every invocation with minimal latency and cost. What is the recommended approach?',
    options: [
      { id: 'A', text: 'Write structured logs in the CloudWatch embedded metric format, letting CloudWatch extract the metrics asynchronously.', correct: true, why: 'EMF turns a log line into a metric with no extra API call, so there is no PutMetricData latency on the invocation path and no per-call charge.' },
      { id: 'B', text: 'Call PutMetricData synchronously at the end of the handler.', correct: false, why: 'It adds an API call and its latency to every invocation, and PutMetricData is charged per call.' },
      { id: 'C', text: 'Write the metric to DynamoDB and aggregate it later with a scheduled job.', correct: false, why: 'Reinvents metric collection, with more cost, more code and more delay.' },
      { id: 'D', text: 'Enable Lambda Insights and derive the business metric from it.', correct: false, why: 'Lambda Insights provides system-level telemetry, not your application\'s business metrics.' },
    ],
    explanation:
      'EMF is the intended answer for custom metrics from Lambda: log once, get a metric, pay no per-call API cost.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format.html',
  },
  {
    id: 'dva-d4-003',
    certs: ['DVA-C02'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A user-facing Lambda function behind API Gateway shows p99 latency of 3 seconds due to cold starts, while p50 is 80 ms. Traffic is steady during business hours. What should be configured?',
    options: [
      { id: 'A', text: 'Provisioned concurrency sized to the business-hours baseline, optionally on a schedule.', correct: true, why: 'Provisioned concurrency keeps environments initialised so requests skip the cold start. Scheduling it to business hours avoids paying for it overnight.' },
      { id: 'B', text: 'Reserved concurrency set to the expected peak.', correct: false, why: 'Reserved concurrency guarantees and caps capacity. It does not pre-warm anything, so cold starts remain.' },
      { id: 'C', text: 'A scheduled EventBridge rule pinging the function every minute to keep it warm.', correct: false, why: 'The old workaround: it warms one environment, not the many needed under concurrency, and it is superseded by provisioned concurrency.' },
      { id: 'D', text: 'Increase the memory allocation to reduce initialisation time.', correct: false, why: 'More memory speeds initialisation somewhat but does not remove the cold start.' },
    ],
    explanation:
      'Cold starts are provisioned concurrency. Concurrency limits are reserved concurrency. The names are similar and the exam exploits that.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html',
  },
  {
    id: 'dva-d4-004',
    certs: ['DVA-C02'],
    taskId: 'dva-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudwatch'],
    stem: 'An operations team must be alerted whenever the text "OutOfMemoryError" appears in an application\'s CloudWatch log group. What should be configured?',
    options: [
      { id: 'A', text: 'A metric filter on the log group that increments a custom metric, with a CloudWatch alarm on that metric.', correct: true, why: 'Metric filters turn a log pattern into a metric, and alarms act on metrics. This is the standard log-to-alert path.' },
      { id: 'B', text: 'A CloudWatch alarm directly on the log group.', correct: false, why: 'Alarms evaluate metrics, not log content. A metric filter is the required intermediate step.' },
      { id: 'C', text: 'A Logs Insights query on a schedule, emailing the results.', correct: false, why: 'Possible with extra machinery, but it polls rather than reacting and there is a native mechanism.' },
      { id: 'D', text: 'A CloudTrail trail filtered for the error string.', correct: false, why: 'CloudTrail records API calls, not application log output.' },
    ],
    explanation:
      'Log pattern → metric filter → alarm → SNS. This chain appears repeatedly, in both DVA and SAA framing.',
    source: 'https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html',
  },
  {
    id: 'dva-d4-005',
    certs: ['DVA-C02'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sns', 'sqs'],
    stem: 'Four SQS queues subscribe to an SNS topic, but each consumer only cares about a subset of message types. Currently every consumer reads and discards most messages. What reduces waste?',
    options: [
      { id: 'A', text: 'Subscription filter policies on each SNS subscription, so only relevant messages reach each queue.', correct: true, why: 'Filtering happens in SNS before delivery, so each queue receives only what it needs — fewer requests, less compute, less cost.' },
      { id: 'B', text: 'A separate SNS topic per message type.', correct: false, why: 'It works but multiplies topics and forces publishers to know the routing, which is what filter policies avoid.' },
      { id: 'C', text: 'A Lambda function between the topic and the queues that routes messages.', correct: false, why: 'Adds a component and its cost to do what SNS does natively.' },
      { id: 'D', text: 'Longer polling intervals on each consumer.', correct: false, why: 'It changes when messages are read, not how many irrelevant ones arrive.' },
    ],
    explanation:
      'DVA names "subscription filter policies to optimize messaging" as a skill. Filter at the source, not in the consumer.',
    source: 'https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html',
  },
  {
    id: 'dva-d4-006',
    certs: ['DVA-C02'],
    taskId: 'dva-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudfront', 'api-gateway'],
    stem: 'An API returns different responses depending on the Accept-Language header. Behind CloudFront, users are receiving responses in the wrong language. What should be changed?',
    options: [
      { id: 'A', text: 'Include Accept-Language in the CloudFront cache key so responses are cached per language.', correct: true, why: 'A header that changes the response must be part of the cache key, or one language\'s response is served to everyone.' },
      { id: 'B', text: 'Disable caching on the distribution entirely.', correct: false, why: 'It fixes correctness by giving up all caching benefit — an over-correction.' },
      { id: 'C', text: 'Forward all headers to the origin.', correct: false, why: 'It fixes correctness but makes almost every request a cache miss, since the key then includes highly variable headers.' },
      { id: 'D', text: 'Add a Lambda@Edge function to rewrite the response.', correct: false, why: 'Far more machinery than needed for something the cache-key policy expresses directly.' },
    ],
    explanation:
      'Anything that varies the response must be in the cache key — and nothing else should be. That balance is the whole art of CDN caching.',
    source: 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/controlling-the-cache-key.html',
  },
]
