import type { Question } from '../schema'

/**
 * Design Secure Architectures — 30% of SAA-C03, and the domain most people
 * fail on. Every question here is a scenario, not a definition, and every
 * option carries an explanation of the specific misconception it targets.
 */
export const saaD1Questions: Question[] = [
  {
    id: 'saa-d1-001',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['iam', 'organizations'],
    stem: 'A company has an AWS Organizations structure with a Sandbox organizational unit. An SCP attached to that OU allows only ec2:* and s3:*. A developer in a sandbox account has an IAM policy granting AdministratorAccess and attempts to create a DynamoDB table. What happens, and why?',
    options: [
      { id: 'A', text: 'The call fails, because the SCP does not permit dynamodb:CreateTable and an SCP sets the maximum available permissions.', correct: true, why: 'An SCP is a ceiling. Any action it does not permit is unavailable regardless of identity policy, and no IAM policy can raise the ceiling.' },
      { id: 'B', text: 'The call succeeds, because AdministratorAccess grants all actions and identity policies take precedence over SCPs.', correct: false, why: 'Identity policies never override an SCP. The effective permission is the intersection of the SCP and the identity policy.' },
      { id: 'C', text: 'The call succeeds, because SCPs apply only to the management account.', correct: false, why: 'It is the reverse: SCPs apply to member accounts and do not apply to the management account. That is precisely why workloads should not run there.' },
      { id: 'D', text: 'The call fails, because AdministratorAccess must be attached at the OU level to take effect.', correct: false, why: 'IAM policies attach to identities, not OUs. The failure has nothing to do with where the policy is attached.' },
    ],
    explanation:
      'An SCP filters permissions; it never grants them. The effective permission set is the intersection of every applicable ceiling and the identity policy, so the least permissive layer always wins.',
    source: 'https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html',
  },
  {
    id: 'saa-d1-002',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['kms', 's3', 'iam'],
    stem: 'An application role has s3:* on a bucket. Objects are encrypted with SSE-KMS using a customer managed key. The application receives AccessDenied on GetObject. The bucket policy does not deny the role. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The KMS key policy does not grant the role kms:Decrypt.', correct: true, why: 'A KMS key policy is authoritative for its key. Without a grant there — directly or delegated to IAM — no S3 permission can decrypt the object.' },
      { id: 'B', text: 'The role needs s3:GetObjectVersion in addition to s3:GetObject.', correct: false, why: 'That is only required for a specific version of a versioned object, and it would not present as a KMS-related denial.' },
      { id: 'C', text: 'S3 Block Public Access is enabled on the bucket.', correct: false, why: 'Block Public Access constrains public and anonymous access. It does not affect an authenticated IAM role.' },
      { id: 'D', text: 'The bucket needs a VPC endpoint policy allowing the role.', correct: false, why: 'An endpoint policy would only matter if traffic were routed through a VPC endpoint, and its absence would not be described as an encryption-related failure.' },
    ],
    explanation:
      'With SSE-KMS, every read is two authorisations: S3 for the object and KMS for the key. "Full S3 permissions but still denied" is nearly always the key policy.',
    source: 'https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html',
  },
  {
    id: 'saa-d1-003',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['nacl', 'security-group'],
    stem: 'A solutions architect must block a single malicious IP address from reaching instances in a public subnet, while leaving all other internet traffic unaffected. What should be used?',
    options: [
      { id: 'A', text: 'A network ACL inbound deny rule for that IP, numbered lower than the allow rule.', correct: true, why: 'NACLs support deny rules and are evaluated in ascending rule order, so a low-numbered deny takes effect before the broader allow.' },
      { id: 'B', text: 'A security group inbound deny rule for that IP.', correct: false, why: 'Security groups are allow-only. There is no deny rule to write — this is the most-tested property of security groups.' },
      { id: 'C', text: 'Remove 0.0.0.0/0 from the security group and list every permitted IP instead.', correct: false, why: 'Technically possible but unmanageable for public internet traffic, and it would block everyone not enumerated rather than just the attacker.' },
      { id: 'D', text: 'A route table entry sending that IP to a blackhole target.', correct: false, why: 'Route tables match destinations for outbound traffic, not inbound sources. There is no per-source-IP routing control.' },
    ],
    explanation:
      'Deny is the dividing line: security groups cannot express it, NACLs can. Any question containing "block a specific IP" is pointing at a NACL, or at WAF if the traffic is HTTP.',
    source: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html',
  },
  {
    id: 'saa-d1-004',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['nacl', 'security-group'],
    stem: 'A web server in a public subnet has a security group allowing inbound TCP 443 from 0.0.0.0/0 and a custom network ACL with a single inbound allow rule for TCP 443 from 0.0.0.0/0. Users report that HTTPS requests time out. Which TWO statements explain and correct this?',
    options: [
      { id: 'A', text: 'Network ACLs are stateless, so the response traffic is being dropped by the outbound rules.', correct: true, why: 'A stateless NACL judges each direction independently, so an allowed request does not imply an allowed reply.' },
      { id: 'B', text: 'Add an outbound allow rule for TCP 1024–65535 to the network ACL.', correct: true, why: 'Replies go to the client\'s ephemeral source port, so the outbound rule must cover that range.' },
      { id: 'C', text: 'Add an outbound rule to the security group allowing TCP 1024–65535.', correct: false, why: 'Security groups are stateful — the reply to an allowed inbound request is permitted automatically, regardless of outbound rules.' },
      { id: 'D', text: 'Network ACLs evaluate rules in reverse numeric order, so the rule number must be raised.', correct: false, why: 'Evaluation is in ascending order, lowest first, and there is only one rule here anyway.' },
      { id: 'E', text: 'The security group must reference the network ACL to take effect.', correct: false, why: 'They are independent, unlinked controls operating at different layers — ENI and subnet.' },
    ],
    explanation:
      'This is the canonical stateful-versus-stateless scenario. When a custom NACL is involved, always ask whether the return path has its own rule on the ephemeral range.',
    source: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html',
  },
  {
    id: 'saa-d1-005',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['iam', 'ec2', 'sts'],
    stem: 'An application on EC2 must read from an S3 bucket. The team currently stores an IAM user\'s access keys in a configuration file on the instance. What is the recommended change?',
    options: [
      { id: 'A', text: 'Attach an IAM role to the instance through an instance profile and remove the stored keys.', correct: true, why: 'The instance receives automatically rotated temporary credentials from STS through the metadata service, so there is no long-lived secret to leak.' },
      { id: 'B', text: 'Move the access keys into AWS Secrets Manager and fetch them at start-up.', correct: false, why: 'Better than a flat file, but it still maintains a long-lived key. It also requires credentials to reach Secrets Manager, which is circular.' },
      { id: 'C', text: 'Encrypt the configuration file with KMS and decrypt it at run time.', correct: false, why: 'The key is still long-lived and still on the instance; you have only added a step for an attacker with instance access.' },
      { id: 'D', text: 'Create an IAM user per instance and rotate the keys every 90 days.', correct: false, why: 'This multiplies the number of long-lived credentials and the operational burden, without removing the underlying risk.' },
    ],
    explanation:
      'Anything that runs code should use a role, never a stored key. If a question describes access keys on a compute resource, the answer is almost always an IAM role.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html',
  },
  {
    id: 'saa-d1-006',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sts', 'iam'],
    stem: 'A third-party monitoring vendor needs read-only access to your account. The vendor will call AWS APIs from its own account. What is the most secure way to grant this?',
    options: [
      { id: 'A', text: 'Create an IAM role the vendor can assume, with a trust policy requiring an ExternalId the vendor supplies.', correct: true, why: 'Role assumption gives temporary credentials, and the ExternalId condition is the specific defence against the confused-deputy problem when a vendor serves many customers.' },
      { id: 'B', text: 'Create an IAM user for the vendor and send the access keys over an encrypted channel.', correct: false, why: 'A long-lived credential you cannot rotate on the vendor\'s behalf, and no defence against the vendor being tricked into using it for another customer.' },
      { id: 'C', text: 'Create an IAM role the vendor can assume with a trust policy allowing Principal "*".', correct: false, why: 'That lets any AWS principal assume the role. It is a wildcard trust policy — one of the most serious misconfigurations possible.' },
      { id: 'D', text: 'Add the vendor\'s account to your AWS Organizations structure and apply a read-only SCP.', correct: false, why: 'Organizations is for accounts you own. It does not apply to a third party, and an SCP grants nothing.' },
    ],
    explanation:
      'Cross-account third-party access is always a role plus a trust policy. The ExternalId is what stops the vendor being manipulated into using its access to your account on someone else\'s behalf.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html',
  },
  {
    id: 'saa-d1-007',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 's3-glacier'],
    stem: 'A financial firm must retain transaction records for seven years in a way that guarantees nobody — including an account administrator or the root user — can delete or alter them before the period expires. Cost should be minimised. What meets this?',
    options: [
      { id: 'A', text: 'S3 with Object Lock in compliance mode and a seven-year retention period, with objects in Glacier Deep Archive.', correct: true, why: 'Compliance mode cannot be shortened or removed by any principal, including root, and Deep Archive is the cheapest storage class for data that is essentially never read.' },
      { id: 'B', text: 'S3 with Object Lock in governance mode and a seven-year retention period.', correct: false, why: 'Governance mode is deliberately breakable by a principal holding s3:BypassGovernanceRetention, so it does not meet "nobody can delete it".' },
      { id: 'C', text: 'S3 versioning with MFA Delete enabled on the bucket.', correct: false, why: 'MFA Delete makes deletion harder, not impossible — the root user with an MFA device can still remove versions.' },
      { id: 'D', text: 'A bucket policy denying s3:DeleteObject to all principals.', correct: false, why: 'A bucket policy can be edited by anyone with s3:PutBucketPolicy, so it is not immutable retention.' },
    ],
    explanation:
      'Compliance mode versus governance mode is the whole question. "Not even an administrator" or "not even root" means compliance mode.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html',
  },
  {
    id: 'saa-d1-008',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['systems-manager', 'privatelink'],
    stem: 'Administrators need interactive shell access to EC2 instances in private subnets. Security policy forbids inbound SSH, bastion hosts, and SSH key management. All sessions must be logged. What should be implemented?',
    options: [
      { id: 'A', text: 'Systems Manager Session Manager, with session logging to S3 or CloudWatch Logs.', correct: true, why: 'Session Manager needs no inbound ports, no bastion and no SSH keys, and every session is auditable through CloudTrail and session logs.' },
      { id: 'B', text: 'AWS Client VPN with certificate-based authentication, then SSH over the tunnel.', correct: false, why: 'It still requires SSH and key management, which the policy forbids.' },
      { id: 'C', text: 'An EC2 Instance Connect endpoint with a security group allowing SSH from the corporate CIDR.', correct: false, why: 'Still SSH, and still an inbound rule on port 22.' },
      { id: 'D', text: 'A NAT gateway plus a security group allowing SSH from the administrators\' IP addresses.', correct: false, why: 'A NAT gateway is outbound-only and cannot carry inbound sessions, and this still opens SSH.' },
    ],
    explanation:
      'Session Manager is the standard answer to "shell access with no open ports and no bastion". In a private subnet with no NAT it needs interface endpoints for ssm, ssmmessages and ec2messages.',
    source: 'https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html',
  },
  {
    id: 'saa-d1-009',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['waf', 'shield', 'cloudfront'],
    stem: 'A public web application behind CloudFront and an Application Load Balancer is suffering SQL injection attempts and scripted scraping from a small number of IP addresses. What should be added?',
    options: [
      { id: 'A', text: 'AWS WAF on the CloudFront distribution, with managed rule groups plus a rate-based rule.', correct: true, why: 'WAF inspects HTTP content at Layer 7 and rate-based rules throttle a single IP. Attaching at CloudFront filters at the edge, before traffic reaches the Region.' },
      { id: 'B', text: 'AWS Shield Advanced on the load balancer.', correct: false, why: 'Shield addresses volumetric Layer 3/4 DDoS. It does not inspect SQL in a request body.' },
      { id: 'C', text: 'A network ACL denying the offending IP addresses on the ALB subnets.', correct: false, why: 'It would block those specific addresses but does nothing about injection from any other source, and NACLs cannot inspect HTTP payloads.' },
      { id: 'D', text: 'GuardDuty with automated remediation through EventBridge.', correct: false, why: 'GuardDuty detects malicious behaviour from logs after the fact; it is not an inline request filter.' },
    ],
    explanation:
      'Layer 7 request content means WAF. Layer 3/4 volume means Shield. Attach WAF as far forward as possible — CloudFront rather than the ALB — for both speed and cost.',
    source: 'https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html',
  },
  {
    id: 'saa-d1-010',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['iam-identity-center', 'organizations', 'iam'],
    stem: 'A company with 40 AWS accounts wants employees to sign in once using the corporate Microsoft Entra ID directory and receive appropriate permissions per account. Joiners and leavers must be handled automatically. What should be implemented?',
    options: [
      { id: 'A', text: 'AWS IAM Identity Center federated to Entra ID via SAML with SCIM provisioning, using permission sets assigned to groups.', correct: true, why: 'One sign-in across every account, permission sets as reusable policy bundles, and SCIM keeps users and groups in sync as people join and leave.' },
      { id: 'B', text: 'IAM users in each account, with a script that creates and deletes them from the directory nightly.', correct: false, why: '40 accounts × every employee of long-lived credentials, plus bespoke sync code. This is the anti-pattern Identity Center exists to replace.' },
      { id: 'C', text: 'A single account holding IAM users, with cross-account roles assumed into the other 39.', correct: false, why: 'Workable historically, but it still means managing IAM users and passwords, and it does not federate the corporate directory.' },
      { id: 'D', text: 'AWS Directory Service AD Connector in each account, with IAM users mapped to directory groups.', correct: false, why: 'AD Connector proxies authentication but does not provide cross-account single sign-on with permission sets, and per-account deployment does not scale.' },
    ],
    explanation:
      'Workforce access across many accounts is IAM Identity Center. SCIM is the specific mechanism that makes joiners and leavers automatic.',
    source: 'https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html',
  },
  {
    id: 'saa-d1-011',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['kms', 'ebs'],
    stem: 'A team must copy an encrypted EBS snapshot from eu-west-1 to us-east-1 for disaster recovery. The snapshot is encrypted with a single-Region customer managed key. What must be done?',
    options: [
      { id: 'A', text: 'Copy the snapshot to us-east-1 and specify a KMS key that exists in us-east-1 to re-encrypt it.', correct: true, why: 'A single-Region key cannot decrypt in another Region, so the copy operation must re-encrypt with a destination-Region key. A multi-Region key would avoid this step.' },
      { id: 'B', text: 'Nothing extra — KMS keys are global and the copy will use the same key.', correct: false, why: 'KMS keys are regional. Only an explicitly created multi-Region key has replicas elsewhere.' },
      { id: 'C', text: 'Decrypt the snapshot, copy it unencrypted, then re-encrypt it in us-east-1.', correct: false, why: 'Snapshots cannot be decrypted to plaintext this way, and deliberately transiting unencrypted data would fail the requirement anyway.' },
      { id: 'D', text: 'Share the eu-west-1 key with us-east-1 using a key policy statement.', correct: false, why: 'Key policies control principals, not Regions. A key cannot be made usable in another Region by policy.' },
    ],
    explanation:
      'KMS keys are regional. Cross-Region encrypted copies need a destination-Region key, or a multi-Region key created for the purpose.',
    source: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-copy-snapshot.html',
  },
  {
    id: 'saa-d1-012',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['macie', 'guardduty', 'inspector'],
    stem: 'A compliance team must find out which S3 buckets contain personally identifiable information, and be alerted when new PII appears. Which service is purpose-built for this?',
    options: [
      { id: 'A', text: 'Amazon Macie', correct: true, why: 'Macie discovers and classifies sensitive data in S3 using managed and custom data identifiers, and emits findings continuously.' },
      { id: 'B', text: 'Amazon GuardDuty', correct: false, why: 'GuardDuty detects malicious activity and compromised credentials. It never inspects the content of your objects.' },
      { id: 'C', text: 'Amazon Inspector', correct: false, why: 'Inspector scans EC2, ECR images and Lambda for software vulnerabilities, not data for sensitivity.' },
      { id: 'D', text: 'AWS Config', correct: false, why: 'Config evaluates resource configuration — whether a bucket is public, say — not what is stored inside it.' },
    ],
    explanation:
      'Remember the trio: GuardDuty finds threats, Inspector finds vulnerabilities, Macie finds sensitive data. All three are usually offered together.',
    source: 'https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html',
  },
  {
    id: 'saa-d1-013',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['privatelink', 's3', 'nat-gateway'],
    stem: 'Instances in private subnets download large volumes of data from S3 through a NAT gateway. The NAT data-processing charge has become the largest line on the bill. Compliance also requires that this traffic never traverse the public internet. What is the best change?',
    options: [
      { id: 'A', text: 'Create a gateway VPC endpoint for S3 and add a route to it in the private subnets\' route tables.', correct: true, why: 'Gateway endpoints for S3 and DynamoDB are free, remove the NAT per-GB charge entirely, and keep traffic on the AWS network.' },
      { id: 'B', text: 'Create an interface VPC endpoint for S3 in each Availability Zone.', correct: false, why: 'Functionally possible, but interface endpoints charge per endpoint-hour per AZ plus per GB — the gateway endpoint is free and is the intended answer for S3.' },
      { id: 'C', text: 'Consolidate to a single NAT gateway shared across all Availability Zones.', correct: false, why: 'It halves the hourly fee but leaves the per-GB charge, adds cross-AZ transfer costs, and creates a single point of failure.' },
      { id: 'D', text: 'Enable S3 Transfer Acceleration on the bucket.', correct: false, why: 'Transfer Acceleration speeds up long-distance uploads over the internet. It adds cost and does not remove the NAT path.' },
    ],
    explanation:
      'S3 or DynamoDB traffic through NAT is almost always a gateway-endpoint question. Gateway endpoints are free; interface endpoints are for the other services.',
    source: 'https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html',
  },
  {
    id: 'saa-d1-014',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['security-group'],
    stem: 'A three-tier application must be configured so that only the application tier can reach the database tier on port 5432. Instances in both tiers are replaced frequently by Auto Scaling. What is the most maintainable configuration?',
    options: [
      { id: 'A', text: 'In the database security group, allow inbound TCP 5432 with the application tier\'s security group as the source.', correct: true, why: 'A security-group reference keeps working as instances and IP addresses change, and it expresses the intent rather than an address that happens to be true today.' },
      { id: 'B', text: 'In the database security group, allow inbound TCP 5432 from the application subnet CIDR.', correct: false, why: 'It works, but it permits anything in that subnet — not only the application tier — and breaks if subnets are re-planned.' },
      { id: 'C', text: 'In the database security group, allow inbound TCP 5432 from each application instance\'s private IP.', correct: false, why: 'Auto Scaling replaces instances constantly, so these rules would need continuous maintenance and would break silently.' },
      { id: 'D', text: 'Use a network ACL on the database subnet allowing TCP 5432 from the application subnet.', correct: false, why: 'Coarser, stateless, and requires ephemeral-port return rules. Security groups are the right tool for tier-to-tier access.' },
    ],
    explanation:
      'Referencing another security group is the idiomatic AWS way to express tier-to-tier access, and the exam consistently rewards it over a CIDR.',
    source: 'https://docs.aws.amazon.com/vpc/latest/userguide/vpc-security-groups.html',
  },
  {
    id: 'saa-d1-015',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['acm', 'cloudfront'],
    stem: 'A team is configuring HTTPS on a CloudFront distribution with the custom domain shop.example.com. The origin is an ALB in ap-southeast-1. They request an ACM certificate in ap-southeast-1 but it cannot be selected on the distribution. Why?',
    options: [
      { id: 'A', text: 'A certificate used by CloudFront must be issued in or imported into us-east-1.', correct: true, why: 'CloudFront is a global service whose certificate store is in us-east-1, regardless of where the origin lives. This is asked directly and often.' },
      { id: 'B', text: 'The certificate must be issued by ACM Private CA for use with CloudFront.', correct: false, why: 'Public ACM certificates are the normal choice for a public distribution; Private CA is for internal certificates.' },
      { id: 'C', text: 'ACM certificates cannot be used with CloudFront — a third-party certificate must be imported.', correct: false, why: 'ACM public certificates are fully supported, and are free.' },
      { id: 'D', text: 'The certificate must be in the same Region as the origin ALB.', correct: false, why: 'That rule applies to the ALB\'s own listener certificate, not to CloudFront\'s.' },
    ],
    explanation:
      'CloudFront certificates live in us-east-1. Regional services (ALB, API Gateway) need the certificate in their own Region — so a design with both needs two certificates.',
    source: 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-requirements.html',
  },
  {
    id: 'saa-d1-016',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['iam', 'organizations'],
    stem: 'A security team must guarantee that no principal in any member account can launch resources outside eu-west-1 and eu-central-1, and must detect any existing non-compliant resources. Which TWO actions together achieve this?',
    options: [
      { id: 'A', text: 'Attach an SCP denying all actions when aws:RequestedRegion is not one of the two approved Regions.', correct: true, why: 'An SCP with a region condition is the preventive control, and it applies even to the root user of member accounts.' },
      { id: 'B', text: 'Enable AWS Config with a multi-account aggregator and rules that flag resources outside the approved Regions.', correct: true, why: 'Config is the detective half — it reports what already exists and what changed, which an SCP cannot do retroactively.' },
      { id: 'C', text: 'Attach an IAM policy to every user denying access outside the two Regions.', correct: false, why: 'It would need to be attached to every principal in every account and could be removed by an administrator. An SCP is the account-wide ceiling.' },
      { id: 'D', text: 'Enable GuardDuty in all accounts to detect resources in unapproved Regions.', correct: false, why: 'GuardDuty finds malicious activity, not configuration or location compliance.' },
      { id: 'E', text: 'Use AWS Control Tower Account Factory to recreate every account with a Region restriction.', correct: false, why: 'Enormously disruptive, and unnecessary — the guardrail can be applied to existing accounts.' },
    ],
    explanation:
      'Preventive plus detective is a recurring pairing: SCPs stop it happening, Config finds what already happened. Neither substitutes for the other.',
    source: 'https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples_general.html',
  },
  {
    id: 'saa-d1-017',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['secrets-manager', 'systems-manager'],
    stem: 'An application needs database credentials that must be rotated automatically every 30 days without code changes, and the same secret must be readable from a second AWS account. What should be used?',
    options: [
      { id: 'A', text: 'AWS Secrets Manager with automatic rotation and a resource policy granting the second account access.', correct: true, why: 'Secrets Manager has built-in rotation for RDS-family credentials and supports a resource policy for cross-account reads. Both requirements are native features.' },
      { id: 'B', text: 'SSM Parameter Store SecureString parameters, encrypted with a customer managed KMS key.', correct: false, why: 'Parameter Store encrypts but does not rotate, and standard parameters have no resource policy for cross-account access.' },
      { id: 'C', text: 'Environment variables on the compute resource, encrypted with KMS.', correct: false, why: 'No rotation, no cross-account sharing, and the value is visible to anyone who can describe the resource configuration.' },
      { id: 'D', text: 'An S3 object holding the credentials, protected by a bucket policy.', correct: false, why: 'Cross-account works, but there is no rotation machinery and secrets do not belong in object storage.' },
    ],
    explanation:
      'Rotation is the deciding feature between Secrets Manager and Parameter Store. Parameter Store is free and static; Secrets Manager costs money and rotates.',
    source: 'https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets.html',
  },
  {
    id: 'saa-d1-018',
    certs: ['SAA-C03'],
    taskId: 'saa-1.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cognito', 'iam', 's3'],
    stem: 'A mobile application lets each signed-in user upload photos directly to S3. Each user must only be able to read and write objects under their own prefix. What is the appropriate design?',
    options: [
      { id: 'A', text: 'A Cognito user pool for sign-in and an identity pool that exchanges the token for IAM credentials, with a role policy scoped by the ${cognito-identity.amazonaws.com:sub} policy variable.', correct: true, why: 'The user pool authenticates, the identity pool issues scoped temporary credentials via STS, and the policy variable confines each user to their own prefix without a policy per user.' },
      { id: 'B', text: 'An IAM user per application user, each with a policy limited to their prefix.', correct: false, why: 'IAM users are for AWS principals, not application customers. This does not scale and creates long-lived credentials on devices.' },
      { id: 'C', text: 'A single shared IAM role for the app, with the application enforcing prefixes in code.', correct: false, why: 'Anyone extracting the credentials could read every user\'s data. The control must be in the policy, not the client.' },
      { id: 'D', text: 'A bucket policy granting s3:* to authenticated Cognito users on the whole bucket.', correct: false, why: 'It authorises every user for every object, which is the opposite of the requirement.' },
    ],
    explanation:
      'Per-user isolation in S3 from a mobile client is the classic identity-pool plus policy-variable pattern. Never one IAM user per app user.',
    source: 'https://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html',
  },
  {
    id: 'saa-d1-019',
    certs: ['SAA-C03'],
    taskId: 'saa-1.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['iam'],
    stem: 'A developer role has an identity policy allowing s3:* on all resources. A permissions boundary attached to the role allows only s3:GetObject and s3:ListBucket. The bucket policy allows s3:* to the account. What can the role do?',
    options: [
      { id: 'A', text: 'Only s3:GetObject and s3:ListBucket, because a permissions boundary caps the effective permissions.', correct: true, why: 'A boundary is a ceiling: the effective permission is the intersection of the identity policy and the boundary. The bucket policy cannot raise it.' },
      { id: 'B', text: 'Everything under s3:*, because the identity policy and bucket policy both allow it.', correct: false, why: 'A boundary is evaluated alongside them and removes anything it does not permit.' },
      { id: 'C', text: 'Nothing, because a permissions boundary must also be attached to the bucket.', correct: false, why: 'Boundaries attach to IAM identities only. There is no such thing as a boundary on a resource.' },
      { id: 'D', text: 'Everything under s3:*, because permissions boundaries apply only to IAM users, not roles.', correct: false, why: 'Boundaries apply to both users and roles.' },
    ],
    explanation:
      'Boundaries, SCPs and session policies are all ceilings. They never grant anything, and the effective permission is always the intersection.',
    source: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html',
  },
  {
    id: 'saa-d1-020',
    certs: ['SAA-C03'],
    taskId: 'saa-1.3',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['cloudtrail', 's3'],
    stem: 'An investigation needs to determine which IAM principal downloaded a specific object from an S3 bucket three weeks ago. CloudTrail is enabled with a management-events trail. What is the likely outcome?',
    options: [
      { id: 'A', text: 'The download will not be recorded, because object-level access requires S3 data events, which are not enabled by default.', correct: true, why: 'Management events cover control-plane calls like CreateBucket. Object-level GetObject is a data event, and data events must be enabled explicitly.' },
      { id: 'B', text: 'The download will be in CloudTrail Event history, which retains 90 days of all events.', correct: false, why: 'Event history holds 90 days of *management* events only. Data events never appear there.' },
      { id: 'C', text: 'The download will be in S3 server access logs, which are enabled by default.', correct: false, why: 'Server access logging is not enabled by default either, and it must be configured per bucket.' },
      { id: 'D', text: 'The download will be recorded because a trail captures all API activity in the account.', correct: false, why: 'A trail captures what you configured it to capture. Data events are opt-in precisely because of their volume.' },
    ],
    explanation:
      'This is the most common CloudTrail trap. "Who accessed this object?" needs S3 data events configured in advance — after the fact is too late.',
    source: 'https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-data-events-with-cloudtrail.html',
  },
]
