import type { Question } from '../schema'

/** Design Resilient Architectures — 26% of SAA-C03. Decoupling and surviving failure. */
export const saaD2Questions: Question[] = [
  {
    id: 'saa-d2-001',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'ec2-auto-scaling'],
    stem: 'An image-processing application receives unpredictable bursts — sometimes 50 uploads an hour, sometimes 20,000 in ten minutes. Each image takes about 40 seconds to process. During bursts the EC2 fleet is overwhelmed and uploads fail. What is the most appropriate redesign?',
    options: [
      { id: 'A', text: 'Write each upload to an SQS queue, and scale the worker Auto Scaling group on a backlog-per-instance target using ApproximateNumberOfMessagesVisible.', correct: true, why: 'The queue absorbs the burst so nothing is lost, and queue depth is the metric that actually reflects pending work for a worker fleet.' },
      { id: 'B', text: 'Increase the Auto Scaling group maximum and scale on average CPU utilisation.', correct: false, why: 'CPU is a lagging and misleading signal for workers: instances waiting on work show low CPU while a backlog grows, and uploads still fail during the ramp-up.' },
      { id: 'C', text: 'Move the processing to Lambda with reserved concurrency set to the burst size.', correct: false, why: 'Plausible, but the burst still arrives synchronously with nothing buffering it, and reserved concurrency caps rather than queues.' },
      { id: 'D', text: 'Put the fleet behind a Network Load Balancer to distribute the bursts more evenly.', correct: false, why: 'A load balancer distributes requests; it does not buffer them or create capacity. The fleet is still overwhelmed.' },
    ],
    explanation:
      'A queue converts a burst into a backlog. Scaling on queue depth rather than CPU is the canonical decoupled worker architecture and appears repeatedly.',
    source: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-using-sqs-queue.html',
  },
  {
    id: 'saa-d2-002',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sns', 'sqs'],
    stem: 'When an order is placed, four independent downstream systems each need a copy of the event: billing, fulfilment, analytics and email. Each processes at a different rate, and no system may lose an event if it is temporarily offline. What design meets this?',
    options: [
      { id: 'A', text: 'Publish to an SNS topic with four subscribed SQS queues, one per consumer.', correct: true, why: 'SNS fans the event out to all four; each SQS queue gives that consumer durability and its own processing pace, so an offline consumer loses nothing.' },
      { id: 'B', text: 'Publish to a single SQS queue that all four systems poll.', correct: false, why: 'Consumers on one queue compete for messages — each message goes to one consumer, so the four would split the work rather than each receiving a copy.' },
      { id: 'C', text: 'Publish to an SNS topic with the four systems subscribed as HTTPS endpoints.', correct: false, why: 'SNS has no retention. Beyond its retry window an offline endpoint loses the event, which the requirement forbids.' },
      { id: 'D', text: 'Write each order to a Kinesis data stream and have all four systems consume it.', correct: false, why: 'It would work, but it is heavier than needed: there is no ordering or replay requirement, and shard management is operational overhead SNS-to-SQS avoids.' },
    ],
    explanation:
      'SNS fan-out to per-consumer SQS queues is the standard pattern. The SQS layer is what supplies the durability SNS lacks.',
    source: 'https://docs.aws.amazon.com/sns/latest/dg/sns-common-scenarios.html',
  },
  {
    id: 'saa-d2-003',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['rds', 'aurora'],
    stem: 'A reporting workload is overloading the primary RDS for PostgreSQL instance. The database is already deployed as Multi-AZ. What should be done to relieve the read pressure?',
    options: [
      { id: 'A', text: 'Add one or more read replicas and point the reporting workload at them.', correct: true, why: 'Read replicas add read capacity. Multi-AZ does not — the standby serves no traffic at all in a classic single-standby deployment.' },
      { id: 'B', text: 'Nothing is needed — the Multi-AZ standby already serves read traffic.', correct: false, why: 'This is the single most common RDS misconception. The Multi-AZ standby exists for failover and is not readable in the classic deployment.' },
      { id: 'C', text: 'Enable Multi-AZ in a second Region so reports can read from there.', correct: false, why: 'Multi-AZ never spans Regions, and it still would not provide a readable endpoint.' },
      { id: 'D', text: 'Increase the instance size and enable Performance Insights.', correct: false, why: 'Vertical scaling buys headroom at higher cost with a restart, and Performance Insights only observes. Neither separates the reporting load.' },
    ],
    explanation:
      'Multi-AZ is availability; read replicas are performance. Questions mixing the two are testing exactly this distinction.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.html',
  },
  {
    id: 'saa-d2-004',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['aurora', 'route53', 's3'],
    stem: 'A business-critical application must survive the loss of an entire Region with an RTO under one minute and an RPO of seconds, at the lowest cost that still meets those numbers. Which strategy fits?',
    options: [
      { id: 'A', text: 'Warm standby: Aurora Global Database with a scaled-down application stack in the second Region, and Route 53 failover.', correct: true, why: 'Aurora Global Database replicates in about a second with sub-minute promotion, and a scaled-down but running stack meets a one-minute RTO without paying for full duplicate capacity.' },
      { id: 'B', text: 'Backup and restore: nightly snapshots copied cross-Region, restored on demand.', correct: false, why: 'RPO would be up to 24 hours and RTO hours. It is the cheapest strategy and it fails both stated numbers.' },
      { id: 'C', text: 'Pilot light: database replicated, application servers stopped until needed.', correct: false, why: 'RPO would be met but starting and scaling the application tier takes longer than a minute.' },
      { id: 'D', text: 'Multi-site active-active with full capacity in both Regions.', correct: false, why: 'It exceeds the requirement and roughly doubles the cost, which the question explicitly rules out with "lowest cost that still meets those numbers".' },
    ],
    explanation:
      'The four DR strategies map to RTO/RPO in a fixed order. Read the numbers, then pick the cheapest strategy that clears them — not the most resilient one available.',
    source: 'https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html',
  },
  {
    id: 'saa-d2-005',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs'],
    stem: 'A worker reads messages from a standard SQS queue. Processing takes about 90 seconds. Operators notice that many jobs are being executed twice. The queue uses default settings. What is the cause and fix?',
    options: [
      { id: 'A', text: 'The 30-second default visibility timeout expires mid-processing, so the message is redelivered. Raise it above the processing time.', correct: true, why: 'While a message is invisible only one consumer holds it. If that window closes before the work finishes, another consumer legitimately receives the same message.' },
      { id: 'B', text: 'Standard queues deliver out of order, so a FIFO queue is required.', correct: false, why: 'Ordering is unrelated to duplicate processing here, and switching to FIFO caps throughput without fixing the timeout.' },
      { id: 'C', text: 'Message retention is too short, so messages are being requeued.', correct: false, why: 'Retention controls how long an unprocessed message survives, not redelivery to a second consumer.' },
      { id: 'D', text: 'Long polling is disabled, causing duplicate receives.', correct: false, why: 'Long polling reduces empty responses and cost. It has no bearing on duplicate delivery.' },
    ],
    explanation:
      'Visibility timeout must exceed processing time. This is the most-tested SQS failure mode, and the reason consumers should also be idempotent.',
    source: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html',
  },
  {
    id: 'saa-d2-006',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['ec2-auto-scaling', 'elb', 'nat-gateway'],
    stem: 'A single-AZ web tier must be made resilient to the loss of an Availability Zone. The tier sits behind an Application Load Balancer, in a private subnet, and reaches the internet through one NAT gateway. Which TWO changes are required?',
    options: [
      { id: 'A', text: 'Add private subnets in a second Availability Zone to the Auto Scaling group, and public subnets in both AZs to the load balancer.', correct: true, why: 'An ASG only launches into the subnets it was given, and a load balancer needs subnets in at least two AZs to route around a failure.' },
      { id: 'B', text: 'Deploy a second NAT gateway in the new Availability Zone and give each private subnet a route to the NAT gateway in its own AZ.', correct: true, why: 'A NAT gateway is zonal. One shared NAT means an AZ failure removes egress for the survivors, and it also generates cross-AZ data charges.' },
      { id: 'C', text: 'Enable cross-zone load balancing on the Application Load Balancer.', correct: false, why: 'It is already on by default for ALB, and it distributes traffic — it does not create capacity in another AZ.' },
      { id: 'D', text: 'Place the Auto Scaling group in a cluster placement group for faster failover.', correct: false, why: 'A cluster placement group confines instances to a single AZ, which is the opposite of what is needed.' },
      { id: 'E', text: 'Increase the desired capacity so more instances run in the existing AZ.', correct: false, why: 'More instances in one AZ still all fail together when that AZ does.' },
    ],
    explanation:
      'Multi-AZ is not a switch — it is subnets in more than one AZ on every component in the path, including the NAT gateway most designs forget.',
    source: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html',
  },
  {
    id: 'saa-d2-007',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['step-functions', 'lambda'],
    stem: 'An order pipeline has six sequential steps, some of which call third-party APIs that occasionally fail. The team currently chains Lambda functions that invoke each other, and cannot tell which step failed when something goes wrong. What should they use?',
    options: [
      { id: 'A', text: 'AWS Step Functions, with per-state retry and catch behaviour and a visual execution history.', correct: true, why: 'Step Functions owns the state, retries with configured backoff, catches failures to a fallback state, and shows exactly which step failed and with what input.' },
      { id: 'B', text: 'An SQS queue between each pair of Lambda functions.', correct: false, why: 'It adds durability but no view of the workflow. You would still be reconstructing the sequence from logs.' },
      { id: 'C', text: 'A single larger Lambda function containing all six steps.', correct: false, why: 'It risks the 15-minute limit, restarts everything on any failure, and makes the failure point harder to see, not easier.' },
      { id: 'D', text: 'EventBridge rules chaining each function to the next.', correct: false, why: 'EventBridge routes individual events statelessly. It holds no workflow state and offers no execution history.' },
    ],
    explanation:
      'The tell is "multiple steps", "retries" and "see which step failed". Orchestration means Step Functions; stateless routing means EventBridge.',
    source: 'https://docs.aws.amazon.com/step-functions/latest/dg/welcome.html',
  },
  {
    id: 'saa-d2-008',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['efs', 'ebs', 's3'],
    stem: 'A legacy content-management application runs on several EC2 instances across two Availability Zones. All instances must read and write the same directory of uploaded files, and the application cannot be modified. What storage should be used?',
    options: [
      { id: 'A', text: 'Amazon EFS, mounted on every instance.', correct: true, why: 'EFS is a shared POSIX filesystem accessible from multiple instances across AZs, so the application keeps writing to a normal path with no code change.' },
      { id: 'B', text: 'An EBS volume attached to each instance, synchronised on a schedule.', correct: false, why: 'EBS attaches to one instance and cannot cross an AZ. Scheduled sync means inconsistent reads and conflicting writes.' },
      { id: 'C', text: 'Amazon S3, with the application rewritten to use the S3 API.', correct: false, why: 'The question states the application cannot be modified, which rules this out even though S3 would be cheaper.' },
      { id: 'D', text: 'An EBS Multi-Attach io2 volume shared by all instances.', correct: false, why: 'Multi-Attach is limited to one AZ and requires a cluster-aware filesystem — a standard filesystem would corrupt.' },
    ],
    explanation:
      '"Shared filesystem, multiple instances, no application change" is EFS. Add Windows or SMB to the requirement and it becomes FSx for Windows File Server.',
    source: 'https://docs.aws.amazon.com/efs/latest/ug/whatisefs.html',
  },
  {
    id: 'saa-d2-009',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['route53', 'global-accelerator'],
    stem: 'A multi-Region application must fail over between Regions in a few seconds. The team currently uses Route 53 failover routing with a 60-second TTL, and observes that some clients keep hitting the failed Region for several minutes. What should be used instead?',
    options: [
      { id: 'A', text: 'AWS Global Accelerator, which provides static anycast IPs and shifts traffic at the network layer.', correct: true, why: 'Clients keep the same IP addresses, so there is no DNS record to re-resolve and no client-side cache to wait out. Failover happens in seconds.' },
      { id: 'B', text: 'Route 53 with the TTL lowered to 10 seconds.', correct: false, why: 'It shortens the window but does not close it — many resolvers and client libraries ignore or floor low TTLs, which is exactly the behaviour described.' },
      { id: 'C', text: 'Route 53 latency-based routing with health checks on both Regions.', correct: false, why: 'Still DNS, still subject to client caching, and latency routing does not change failover speed.' },
      { id: 'D', text: 'CloudFront with both Regions configured as origins in an origin group.', correct: false, why: 'Origin failover helps for cacheable HTTP through CloudFront, but it is not a general answer for arbitrary traffic and does not give static IPs.' },
    ],
    explanation:
      'DNS-based failover is bounded by client caching, whatever the TTL says. When "seconds" is a hard requirement, the answer is Global Accelerator.',
    source: 'https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html',
  },
  {
    id: 'saa-d2-010',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['elb'],
    stem: 'An application must route /api/* requests to one target group and /images/* to another, based on the URL path. Which load balancer supports this?',
    options: [
      { id: 'A', text: 'Application Load Balancer', correct: true, why: 'The ALB operates at Layer 7 and can route on path, host, header, query string and HTTP method.' },
      { id: 'B', text: 'Network Load Balancer', correct: false, why: 'The NLB works at Layer 4 on TCP/UDP and has no visibility of the HTTP path.' },
      { id: 'C', text: 'Gateway Load Balancer', correct: false, why: 'The GWLB inserts third-party inspection appliances into the traffic path; it does not do content routing.' },
      { id: 'D', text: 'Classic Load Balancer', correct: false, why: 'The CLB is legacy and supports no path-based routing rules.' },
    ],
    explanation:
      'Content-based routing means Layer 7, which means ALB. Static IPs, extreme throughput or non-HTTP protocols mean NLB.',
    source: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html',
  },
  {
    id: 'saa-d2-011',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['elasticache', 'rds'],
    stem: 'A web tier behind a load balancer stores session state in memory on each instance. Users are randomly logged out when Auto Scaling replaces instances. The application code can be changed. What is the best fix?',
    options: [
      { id: 'A', text: 'Store session state in ElastiCache for Redis so the web tier becomes stateless.', correct: true, why: 'Externalising session state means any instance can serve any request, which is what makes instances disposable — the property Auto Scaling depends on.' },
      { id: 'B', text: 'Enable sticky sessions on the Application Load Balancer.', correct: false, why: 'It masks the problem: users still lose their session when their pinned instance is replaced, and it unbalances the fleet.' },
      { id: 'C', text: 'Increase the Auto Scaling health check grace period so instances live longer.', correct: false, why: 'It changes nothing about what happens when an instance is eventually replaced, which is inevitable.' },
      { id: 'D', text: 'Store session state in an RDS table.', correct: false, why: 'It works but adds relational-database latency and load to a pure key-value, high-churn access pattern that a cache handles far better.' },
    ],
    explanation:
      'Externalising session state is the standard "make the tier stateless" answer. Sticky sessions are the plausible distractor that only defers the problem.',
    source: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/WhatIs.html',
  },
  {
    id: 'saa-d2-012',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['sqs', 'lambda'],
    stem: 'A Lambda function triggered by an SQS queue keeps failing on one malformed message. The queue backs up and no other messages are processed successfully. What should be configured?',
    options: [
      { id: 'A', text: 'A dead-letter queue on the source queue with a maxReceiveCount, so the poison message is moved aside after a few attempts.', correct: true, why: 'A redrive policy removes the message after the configured number of receives, unblocking the queue and preserving the message for inspection.' },
      { id: 'B', text: 'Increase the Lambda function timeout.', correct: false, why: 'The function is failing, not timing out. A longer timeout changes nothing.' },
      { id: 'C', text: 'Reduce the event source batch size to 1.', correct: false, why: 'It limits the collateral damage per batch but the poison message is still retried forever.' },
      { id: 'D', text: 'Switch the queue to FIFO so failed messages are skipped.', correct: false, why: 'FIFO does the opposite — strict ordering means a failing message blocks its message group entirely.' },
    ],
    explanation:
      'A poison message needs a dead-letter queue. For stream and batch sources, ReportBatchItemFailures narrows the retry to the failing records.',
    source: 'https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html',
  },
  {
    id: 'saa-d2-013',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ec2-auto-scaling', 'cloudwatch'],
    stem: 'Instances in an Auto Scaling group are launched, terminated after a few minutes, and launched again in a loop. The application takes about four minutes to start and pass its health check. What is the most likely cause?',
    options: [
      { id: 'A', text: 'The health check grace period is shorter than the application start-up time, so instances are marked unhealthy while still booting.', correct: true, why: 'The grace period defines how long the ASG waits before honouring health checks. If it expires mid-boot, the ASG kills a perfectly healthy instance and repeats forever.' },
      { id: 'B', text: 'The Auto Scaling group has no scaling policy attached.', correct: false, why: 'Without a policy the group would hold a steady desired count, not cycle instances.' },
      { id: 'C', text: 'The cooldown period is too long, causing repeated scaling actions.', correct: false, why: 'A long cooldown suppresses scaling actions; it does not cause termination loops.' },
      { id: 'D', text: 'The load balancer has cross-zone load balancing disabled.', correct: false, why: 'That affects traffic distribution, not instance health or lifecycle.' },
    ],
    explanation:
      'Launch-terminate loops are almost always the health check grace period versus real start-up time. Turning on ELB health checks makes the ASG replace instances whose app is dead but whose OS is fine.',
    source: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/health-check-grace-period.html',
  },
  {
    id: 'saa-d2-014',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway', 'lambda', 'sqs'],
    stem: 'An API endpoint triggers a report that takes about three minutes to generate. Clients receive HTTP 504 errors. The report logic cannot be made faster. What should change?',
    options: [
      { id: 'A', text: 'Accept the request, put the job on a queue, return 202 with a status URL, and let a worker generate the report asynchronously.', correct: true, why: 'API Gateway has a hard 29-second integration timeout. Any work longer than that must become asynchronous — there is no configuration that raises the ceiling.' },
      { id: 'B', text: 'Increase the API Gateway integration timeout to 300 seconds.', correct: false, why: 'The 29-second maximum cannot be raised. This option does not exist.' },
      { id: 'C', text: 'Increase the Lambda function timeout to 15 minutes.', correct: false, why: 'The function may already have time; it is API Gateway that gives up at 29 seconds and returns the 504.' },
      { id: 'D', text: 'Put CloudFront in front of API Gateway and cache the response.', correct: false, why: 'Caching helps repeat requests, but the first request still has to complete inside 29 seconds.' },
    ],
    explanation:
      'The 29-second API Gateway ceiling is a hard limit and a common design constraint. Long work becomes a job plus a status endpoint.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html',
  },
  {
    id: 'saa-d2-015',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['rds-proxy', 'lambda', 'rds'],
    stem: 'A Lambda function backed by RDS for MySQL fails under load with "Too many connections". Concurrency is high and each invocation opens its own connection. What is the correct fix?',
    options: [
      { id: 'A', text: 'Put Amazon RDS Proxy between Lambda and the database so connections are pooled and reused.', correct: true, why: 'This is a connection-count problem, and pooling is what solves it. RDS Proxy also shortens observed failover time and can source credentials from Secrets Manager.' },
      { id: 'B', text: 'Add read replicas and distribute queries across them.', correct: false, why: 'Replicas add read throughput. They do nothing about the number of connections the writer is being asked to accept.' },
      { id: 'C', text: 'Increase the RDS instance size to raise max_connections.', correct: false, why: 'It buys headroom but scales linearly with cost and does not fix the underlying pattern — Lambda concurrency can always outgrow it.' },
      { id: 'D', text: 'Set Lambda reserved concurrency to 10 so fewer connections are opened.', correct: false, why: 'It stops the errors by throttling your own application, which trades one failure for another.' },
    ],
    explanation:
      '"Too many connections" plus Lambda is always RDS Proxy. Read replicas are the plausible distractor because they sound like scaling.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html',
  },
  {
    id: 'saa-d2-016',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['eventbridge', 'sns', 'lambda'],
    stem: 'A security team wants a Lambda function invoked whenever an EC2 instance changes state to "stopped" anywhere in the account, and only for instances tagged Environment=production. What should be configured?',
    options: [
      { id: 'A', text: 'An EventBridge rule matching the EC2 state-change event pattern, with the Lambda function as its target.', correct: true, why: 'EventBridge receives AWS service events natively and matches on any field of the event JSON, which is what makes the tag and state filter possible without code.' },
      { id: 'B', text: 'An SNS topic subscribed to EC2 state changes, with the Lambda function subscribed to the topic.', correct: false, why: 'SNS does not receive AWS service events directly, and its filter policies match message attributes rather than arbitrary event structure.' },
      { id: 'C', text: 'A CloudWatch alarm on the EC2 StatusCheckFailed metric with a Lambda action.', correct: false, why: 'That metric is about instance health, not lifecycle state, and alarms cannot filter by tag.' },
      { id: 'D', text: 'A Lambda function on a one-minute schedule polling DescribeInstances.', correct: false, why: 'Polling is wasteful, delayed, and will miss transitions between polls.' },
    ],
    explanation:
      'Reacting to an AWS service event is EventBridge. Content-based filtering on the event body is what distinguishes it from SNS.',
    source: 'https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-what-is.html',
  },
  {
    id: 'saa-d2-017',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'backup'],
    stem: 'A team needs objects in an S3 bucket replicated to a bucket in another Region for disaster recovery, including the 40 TB of objects that already exist. What is required?',
    options: [
      { id: 'A', text: 'Enable versioning on both buckets, configure Cross-Region Replication, and run S3 Batch Replication for the existing objects.', correct: true, why: 'Replication requires versioning on both sides and only applies to objects written after it is configured — existing objects need Batch Replication explicitly.' },
      { id: 'B', text: 'Configure Cross-Region Replication; existing objects are replicated automatically within 24 hours.', correct: false, why: 'Replication is forward-looking only. Pre-existing objects are never replicated automatically, which is the trap in this question.' },
      { id: 'C', text: 'Enable Cross-Region Replication without versioning, since replication implies versioning.', correct: false, why: 'Versioning is a hard prerequisite on both source and destination and must be enabled explicitly.' },
      { id: 'D', text: 'Use AWS DataSync on a schedule instead, as replication cannot cross Regions.', correct: false, why: 'Replication does cross Regions. DataSync would work but is the wrong tool for continuous object replication.' },
    ],
    explanation:
      'Two facts carry this question: replication needs versioning on both buckets, and it never touches objects that already existed.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html',
  },
  {
    id: 'saa-d2-018',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ecs', 'fargate', 'ec2'],
    stem: 'A team wants to containerise a stateless web service. They have no Kubernetes experience, do not want to manage instances, and the requirement stresses minimal operational overhead. What should they use?',
    options: [
      { id: 'A', text: 'Amazon ECS with the Fargate launch type.', correct: true, why: 'ECS has a short learning curve and no control-plane charge, and Fargate removes the hosts entirely. This is the least-overhead containerised option.' },
      { id: 'B', text: 'Amazon EKS with managed node groups.', correct: false, why: 'It introduces Kubernetes to a team with no Kubernetes experience, and adds a per-cluster control-plane charge — more overhead, not less.' },
      { id: 'C', text: 'Amazon ECS with the EC2 launch type.', correct: false, why: 'Correct orchestrator, but it puts the instances back under your management, which the requirement rules out.' },
      { id: 'D', text: 'EC2 instances in an Auto Scaling group running Docker directly.', correct: false, why: 'No orchestration at all: you would be building scheduling, placement and health management by hand.' },
    ],
    explanation:
      'The word "Kubernetes" is the EKS trigger. Without it, plus "minimal operational overhead", the answer is ECS on Fargate.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html',
  },
  {
    id: 'saa-d2-019',
    certs: ['SAA-C03'],
    taskId: 'saa-2.2',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['dynamodb', 'global-infrastructure'],
    stem: 'A global application needs single-digit-millisecond read and write latency for users in Europe, North America and Asia, on the same dataset. Which design meets this with the least operational effort?',
    options: [
      { id: 'A', text: 'DynamoDB Global Tables with replicas in one Region per continent.', correct: true, why: 'Global Tables give multi-Region, multi-active replication with local reads and writes and last-writer-wins conflict resolution, all managed.' },
      { id: 'B', text: 'Aurora Global Database with a primary in Europe and secondaries elsewhere.', correct: false, why: 'Secondary Regions are read-only. Writes still cross an ocean, so the write latency requirement fails.' },
      { id: 'C', text: 'A single DynamoDB table in eu-west-1 fronted by CloudFront.', correct: false, why: 'CloudFront caches HTTP responses; it cannot make a write to a distant Region fast.' },
      { id: 'D', text: 'RDS for PostgreSQL with cross-Region read replicas in each continent.', correct: false, why: 'Same problem as Aurora Global Database, with slower replication and manual promotion.' },
    ],
    explanation:
      'Multi-active *writes* in several Regions is the discriminator. Global Tables are multi-active; Aurora Global Database and read replicas are read-only outside the primary.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html',
  },
  {
    id: 'saa-d2-020',
    certs: ['SAA-C03'],
    taskId: 'saa-2.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['kinesis-data-streams', 'sqs'],
    stem: 'Clickstream events arrive at 20,000 records per second. Three separate teams must each process the full stream independently, and it must be possible to reprocess the last 48 hours after fixing a bug. What should be used?',
    options: [
      { id: 'A', text: 'Amazon Kinesis Data Streams with retention extended to 48 hours or more.', correct: true, why: 'A stream retains records for the configured window and lets independent consumers each track their own position, so all three teams read everything and can replay.' },
      { id: 'B', text: 'An SQS queue that all three teams poll.', correct: false, why: 'A message is deleted once processed, so consumers compete rather than each seeing everything, and there is nothing to replay.' },
      { id: 'C', text: 'An SNS topic with three subscribed SQS queues.', correct: false, why: 'It solves fan-out but not replay: once a queue message is consumed it is gone, and SQS retention maxes out at 14 days without re-reading.' },
      { id: 'D', text: 'Amazon Data Firehose delivering to three S3 prefixes.', correct: false, why: 'Firehose has no replay and no independent consumer positions — it is a delivery pipe, not a log.' },
    ],
    explanation:
      'Replay plus multiple independent consumers plus ordering is the Kinesis signature. Without those three, SQS is simpler and cheaper.',
    source: 'https://docs.aws.amazon.com/streams/latest/dev/introduction.html',
  },
]
