import type { Question } from '../schema'

/** Design Cost-Optimized Architectures — 20% of SAA-C03. The same services, judged on price. */
export const saaD4Questions: Question[] = [
  {
    id: 'saa-d4-001',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 's3-glacier'],
    stem: 'Log files are read heavily for 30 days, occasionally for the next 60 days, then almost never — but must be retrievable within 12 hours for seven years. What lifecycle configuration is most cost-effective?',
    options: [
      { id: 'A', text: 'Standard for 30 days, then Standard-IA, then Glacier Deep Archive at day 90, expiring after seven years.', correct: true, why: 'Each tier matches the described access pattern, and Deep Archive Standard retrieval is about 12 hours — exactly the stated requirement, at the lowest storage price AWS offers.' },
      { id: 'B', text: 'Standard for 30 days, then Glacier Flexible Retrieval at day 30, expiring after seven years.', correct: false, why: 'It skips the occasional-access period: retrieval fees during days 30–90 would exceed the storage saving.' },
      { id: 'C', text: 'Intelligent-Tiering from day zero, expiring after seven years.', correct: false, why: 'Intelligent-Tiering is for *unknown* patterns. Here the pattern is known precisely, so the monitoring fee is pure overhead.' },
      { id: 'D', text: 'Standard for 90 days, then Glacier Instant Retrieval, expiring after seven years.', correct: false, why: 'Instant Retrieval costs far more than Deep Archive, and a 12-hour window does not require instant access.' },
    ],
    explanation:
      'Match the retrieval window to the class exactly. "Within 12 hours" is Deep Archive Standard; "within minutes" would force Flexible Expedited.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html',
  },
  {
    id: 'saa-d4-002',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['savings-plans', 'spot', 'ec2'],
    stem: 'A workload needs a guaranteed baseline of 20 instances at all times, plus up to 60 more during unpredictable peaks. Peak capacity can tolerate interruption. What is the most cost-effective purchasing strategy?',
    options: [
      { id: 'A', text: 'A Compute Savings Plan covering the 20-instance baseline, with the peak served by Spot in a mixed-instances Auto Scaling group.', correct: true, why: 'Commit only to the predictable floor and buy the volatile peak at Spot prices. This is the canonical cost-optimised elastic architecture.' },
      { id: 'B', text: 'Reserved Instances for all 80 instances.', correct: false, why: 'You would pay for 60 instances that are usually idle, and be locked in for one to three years.' },
      { id: 'C', text: 'All 80 instances on Spot.', correct: false, why: 'The baseline of 20 must be guaranteed, and Spot offers no guarantee.' },
      { id: 'D', text: 'All 80 On-Demand with target tracking scaling.', correct: false, why: 'It meets the functional need but is the most expensive option, forgoing both commitment discounts and Spot.' },
    ],
    explanation:
      'Commit to the floor, Spot the peak, On-Demand for the rest. A mixed-instances policy with an On-Demand base capacity expresses this directly.',
    source: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-mixed-instances-groups.html',
  },
  {
    id: 'saa-d4-003',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['nat-gateway', 'privatelink'],
    stem: 'An architect reviews a bill and finds the largest single line is NAT gateway data processing. Investigation shows 80% of that traffic is instances reading from S3 and writing to DynamoDB. What is the correct optimisation?',
    options: [
      { id: 'A', text: 'Add gateway VPC endpoints for S3 and DynamoDB and route that traffic through them.', correct: true, why: 'Gateway endpoints for S3 and DynamoDB are free and eliminate the NAT per-GB charge for exactly this traffic.' },
      { id: 'B', text: 'Add interface VPC endpoints for S3 and DynamoDB in every Availability Zone.', correct: false, why: 'Interface endpoints charge per endpoint-hour per AZ plus per GB. For these two services the gateway endpoint is the free option.' },
      { id: 'C', text: 'Consolidate to one NAT gateway to reduce the hourly charge.', correct: false, why: 'The problem is data processing, not the hourly fee. This adds cross-AZ transfer cost and a single point of failure.' },
      { id: 'D', text: 'Replace the NAT gateway with NAT instances on t3.micro.', correct: false, why: 'It shifts cost to instances you must patch, size and make highly available, and it still routes the traffic over the internet path.' },
    ],
    explanation:
      'S3 and DynamoDB through NAT is always a gateway-endpoint question. Remember which services get the free gateway kind.',
    source: 'https://docs.aws.amazon.com/vpc/latest/privalink/gateway-endpoints.html',
  },
  {
    id: 'saa-d4-004',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['aurora-serverless', 'rds'],
    stem: 'Six development databases are used sporadically — heavily for two hours some afternoons, untouched for days at a time. They currently run on constantly-provisioned db.r6g.large instances. What reduces cost most?',
    options: [
      { id: 'A', text: 'Move them to Aurora Serverless v2 with a low minimum capacity.', correct: true, why: 'Capacity scales with actual load and is billed per ACU-second, so idle days cost a fraction of a running instance.' },
      { id: 'B', text: 'Purchase three-year Reserved Instances for the six instances.', correct: false, why: 'A commitment is the wrong instrument for sporadic use — you would lock in payment for capacity that is mostly idle.' },
      { id: 'C', text: 'Downsize to db.t4g.micro instances.', correct: false, why: 'Cheaper, but still billed continuously, and burstable instances would throttle during the heavy two-hour bursts.' },
      { id: 'D', text: 'Consolidate all six into one larger instance with separate schemas.', correct: false, why: 'It reduces instance count but still runs continuously, and couples six teams onto one database.' },
    ],
    explanation:
      '"Intermittent", "sporadic" or "unpredictable" load on a relational database is Aurora Serverless v2. Steady load points back to provisioned plus a commitment.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.html',
  },
  {
    id: 'saa-d4-005',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['budgets', 'cost-explorer'],
    stem: 'A finance team must be notified before monthly spend exceeds $50,000, and non-production instances should be stopped automatically if it does. What should be configured?',
    options: [
      { id: 'A', text: 'An AWS Budget with a forecast-based alert and a Budget Action that stops tagged EC2 and RDS instances.', correct: true, why: 'Forecast alerts fire before the money is spent, and Budget Actions can stop instances or apply a restrictive policy rather than only notifying.' },
      { id: 'B', text: 'Cost Explorer with a monthly report emailed to the finance team.', correct: false, why: 'Cost Explorer analyses and forecasts but does not alert on a threshold or take any action.' },
      { id: 'C', text: 'A CloudWatch alarm on the EstimatedCharges metric with an SNS notification.', correct: false, why: 'It can notify but reacts to actual spend rather than forecast, and cannot stop resources.' },
      { id: 'D', text: 'A Cost and Usage Report delivered daily to S3 and queried with Athena.', correct: false, why: 'That is detailed analysis, with no alerting or enforcement.' },
    ],
    explanation:
      'Cost Explorer analyses, Budgets alerts and acts. "Notify before" means a forecast-based budget; "stop it happening" means a Budget Action.',
    source: 'https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-controls.html',
  },
  {
    id: 'saa-d4-006',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3'],
    stem: 'A research institute publishes a 500 TB open dataset in S3. Thousands of external researchers download from it, and the egress bill has become unsustainable. The data must stay publicly available. What should be configured?',
    options: [
      { id: 'A', text: 'Enable Requester Pays on the bucket so downloaders are billed for requests and data transfer.', correct: true, why: 'Requester Pays shifts request and transfer charges to the caller, keeping the data available while removing the publisher\'s egress bill.' },
      { id: 'B', text: 'Move the data to Glacier Deep Archive to reduce cost.', correct: false, why: 'It cuts storage cost but adds retrieval fees and a 12-hour wait, breaking public availability.' },
      { id: 'C', text: 'Put CloudFront in front of the bucket to reduce transfer cost.', correct: false, why: 'CloudFront lowers the per-GB rate but the publisher still pays. At 500 TB of genuinely distinct downloads the caching benefit is limited.' },
      { id: 'D', text: 'Enable S3 Intelligent-Tiering.', correct: false, why: 'That addresses storage cost, not egress, which is the stated problem.' },
    ],
    explanation:
      'Requester Pays is the specific answer to "we publish a large dataset and cannot afford the egress". Note that requesters must be authenticated AWS principals.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysBuckets.html',
  },
  {
    id: 'saa-d4-007',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda', 'ec2', 'fargate'],
    stem: 'An API receives about 200 requests per day, each taking roughly 300 ms. It currently runs on two t3.small instances behind an ALB for availability. What is the most cost-effective architecture?',
    options: [
      { id: 'A', text: 'API Gateway with a Lambda function, removing the instances and the load balancer.', correct: true, why: 'Per-request pricing suits 200 invocations a day, and you also stop paying about $16 a month for a load balancer that is almost always idle.' },
      { id: 'B', text: 'One t3.micro instance with an Elastic IP instead of the ALB.', correct: false, why: 'Cheaper than today but still billed continuously, and it gives up the availability the two instances provided.' },
      { id: 'C', text: 'ECS on Fargate with a minimum of one task behind the existing ALB.', correct: false, why: 'A continuously running task plus the ALB hourly charge, for traffic that is idle 99.9% of the time.' },
      { id: 'D', text: 'Keep the instances but purchase three-year Reserved Instances.', correct: false, why: 'Committing for three years to capacity that is idle almost always is the wrong instrument entirely.' },
    ],
    explanation:
      'Very low, spiky traffic is where serverless wins outright. Note the load balancer\'s hourly charge — an idle ALB is a commonly missed cost.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/welcome.html',
  },
  {
    id: 'saa-d4-008',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['cloudfront', 's3', 'nat-gateway'],
    stem: 'Which TWO changes reduce data-transfer cost without reducing availability?',
    options: [
      { id: 'A', text: 'Serve static assets through CloudFront instead of directly from S3.', correct: true, why: 'Origin fetches from S3 to CloudFront are free and CloudFront egress rates are lower than S3-to-internet, so both latency and cost improve.' },
      { id: 'B', text: 'Add gateway VPC endpoints so S3 and DynamoDB traffic bypasses the NAT gateway.', correct: true, why: 'Removes the NAT per-GB processing charge for that traffic at no cost, and improves the security posture too.' },
      { id: 'C', text: 'Consolidate three per-AZ NAT gateways into one shared NAT gateway.', correct: false, why: 'It cuts the hourly fee but adds cross-AZ transfer charges and makes one AZ failure remove egress for all — availability is reduced.' },
      { id: 'D', text: 'Move all instances into a single Availability Zone to eliminate cross-AZ transfer.', correct: false, why: 'It does remove cross-AZ charges, and it destroys AZ resilience, which the question forbids.' },
      { id: 'E', text: 'Disable cross-zone load balancing on the Application Load Balancer.', correct: false, why: 'ALB cross-zone cannot be disabled per-target-group in the way this implies, and uneven distribution would harm availability.' },
    ],
    explanation:
      'Data transfer is where the AWS bill hides. The trap in cost questions is the option that saves money by removing redundancy.',
    source: 'https://aws.amazon.com/blogs/architecture/overview-of-data-transfer-costs-for-common-architectures/',
  },
  {
    id: 'saa-d4-009',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['s3'],
    stem: 'A bucket holds user uploads whose access pattern is impossible to predict — some objects are read constantly for years, others never again after a week. What storage configuration is most appropriate?',
    options: [
      { id: 'A', text: 'S3 Intelligent-Tiering.', correct: true, why: 'Intelligent-Tiering moves each object between access tiers based on its own observed pattern, which is exactly the case where a fixed lifecycle rule cannot work.' },
      { id: 'B', text: 'S3 Standard with a lifecycle rule to Standard-IA after 30 days.', correct: false, why: 'It penalises the objects that stay hot, incurring retrieval fees on frequently read data.' },
      { id: 'C', text: 'S3 One Zone-IA to minimise storage cost.', correct: false, why: 'Cheaper, but the data exists in one AZ only — unacceptable for user uploads — and IA retrieval fees hurt the hot objects.' },
      { id: 'D', text: 'S3 Standard for everything, with no lifecycle rule.', correct: false, why: 'Simple and safe, but pays Standard prices for objects never read again.' },
    ],
    explanation:
      '"Unknown", "unpredictable" or "changing" access patterns means Intelligent-Tiering. If the pattern *is* known, name the class directly and avoid the monitoring fee.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html',
  },
  {
    id: 'saa-d4-010',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['spot', 'batch', 'emr'],
    stem: 'A nightly genomics pipeline processes 8,000 independent jobs on an EMR cluster. Each job checkpoints, and the pipeline must finish by 06:00 but can start any time after 22:00. How should the cluster be configured for lowest cost?',
    options: [
      { id: 'A', text: 'A transient cluster with On-Demand core nodes and Spot task nodes, terminating when the step completes.', correct: true, why: 'Task nodes hold no HDFS data so losing one to reclamation is safe, core nodes stay On-Demand to protect HDFS, and a transient cluster stops billing when the work is done.' },
      { id: 'B', text: 'A long-running cluster with all nodes on Spot.', correct: false, why: 'Spot core nodes risk losing HDFS blocks, and a long-running cluster bills through the idle daytime.' },
      { id: 'C', text: 'A long-running cluster with all nodes On-Demand and Reserved Instances.', correct: false, why: 'It pays for a cluster that is idle 16 hours a day, and forgoes Spot on the interruptible portion.' },
      { id: 'D', text: 'A transient cluster with all nodes on Spot.', correct: false, why: 'Transient is right, but Spot core nodes still risk HDFS data loss mid-run.' },
    ],
    explanation:
      'Spot goes on task nodes, never core nodes. Combine that with a transient cluster and you have the standard cost-optimised EMR answer.',
    source: 'https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-instance-purchasing-options.html',
  },
  {
    id: 'saa-d4-011',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A DynamoDB table serves a steady, well-understood 400 reads and 120 writes per second, around the clock, with little variation. It currently uses on-demand capacity. What reduces cost?',
    options: [
      { id: 'A', text: 'Switch to provisioned capacity with auto scaling, sized to the known load.', correct: true, why: 'On-demand carries a premium per request for the convenience of not forecasting. When the load *is* forecastable, provisioned is materially cheaper.' },
      { id: 'B', text: 'Stay on on-demand and add DAX to reduce read units.', correct: false, why: 'DAX helps repeated reads but adds cluster cost, and does not address the pricing-model mismatch.' },
      { id: 'C', text: 'Switch to provisioned capacity without auto scaling and over-provision by 50%.', correct: false, why: 'Better than on-demand, but paying for 50% headroom on a steady load is avoidable waste.' },
      { id: 'D', text: 'Enable Global Tables to spread the load across Regions.', correct: false, why: 'That multiplies cost — it is a latency and resilience feature, not a cost optimisation.' },
    ],
    explanation:
      'On-demand for unknown or spiky traffic, provisioned with auto scaling for steady forecastable traffic. Questions describing steady load are testing the switch back.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html',
  },
  {
    id: 'saa-d4-012',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['savings-plans'],
    stem: 'A company runs steady workloads on EC2, Fargate and Lambda, and expects to change instance families and Regions over the next year. Which purchase commitment gives savings with the most flexibility?',
    options: [
      { id: 'A', text: 'A Compute Savings Plan.', correct: true, why: 'Compute Savings Plans apply across instance family, size, Region, OS and tenancy, and uniquely also cover Fargate and Lambda.' },
      { id: 'B', text: 'An EC2 Instance Savings Plan.', correct: false, why: 'A larger discount, but locked to one instance family in one Region, and it does not cover Fargate or Lambda.' },
      { id: 'C', text: 'Standard Reserved Instances.', correct: false, why: 'The deepest discount and the least flexibility — fixed attributes and EC2 only.' },
      { id: 'D', text: 'Convertible Reserved Instances.', correct: false, why: 'More flexible than Standard RIs, but still EC2 only and requires an exchange process to change.' },
    ],
    explanation:
      'Compute Savings Plans covering Fargate and Lambda is the commonly missed fact. Flexibility in the question means Compute; a fixed family means EC2 Instance.',
    source: 'https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html',
  },
  {
    id: 'saa-d4-013',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['efs', 'ebs'],
    stem: 'An EFS file system holds 8 TB, of which about 400 GB is accessed regularly. The rest has not been read in months. The workload does not require multi-AZ resilience. What reduces cost most?',
    options: [
      { id: 'A', text: 'Enable EFS lifecycle management to move idle files to Infrequent Access, and use the One Zone storage class.', correct: true, why: 'Lifecycle management tiers the 7.6 TB of cold data automatically, and One Zone is roughly 47% cheaper — acceptable because the requirement waives multi-AZ.' },
      { id: 'B', text: 'Migrate the file system to EBS volumes attached to each instance.', correct: false, why: 'EBS is not shared across instances and cannot cross an AZ, so it does not replace a shared file system.' },
      { id: 'C', text: 'Copy everything to S3 Glacier and mount it as a file system.', correct: false, why: 'Glacier cannot be mounted as a POSIX file system.' },
      { id: 'D', text: 'Switch the throughput mode from Elastic to Provisioned.', correct: false, why: 'Provisioned throughput generally increases cost unless you have a specific sustained-throughput need.' },
    ],
    explanation:
      'EFS lifecycle policies plus One Zone is the standard "cut our EFS bill" answer. Only choose One Zone when the question explicitly waives AZ resilience.',
    source: 'https://docs.aws.amazon.com/efs/latest/ug/lifecycle-management-efs.html',
  },
  {
    id: 'saa-d4-014',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['direct-connect', 'site-to-site-vpn'],
    stem: 'A company transfers about 90 TB per month from on premises to AWS over the internet and pays significant egress charges in the return direction. Latency is inconsistent and the finance team wants predictable networking cost. What should be implemented?',
    options: [
      { id: 'A', text: 'AWS Direct Connect, which offers lower per-GB data-transfer-out rates and consistent latency, with a Site-to-Site VPN as backup.', correct: true, why: 'At this sustained volume the reduced DX egress rate offsets the port fee, latency becomes predictable, and a VPN backup covers the single-circuit risk.' },
      { id: 'B', text: 'A Site-to-Site VPN alone, which is cheaper than Direct Connect.', correct: false, why: 'A VPN still traverses the internet, so latency stays inconsistent and egress rates are unchanged.' },
      { id: 'C', text: 'AWS Snowball devices shipped monthly.', correct: false, why: 'Snow is for one-off bulk migration, not a recurring monthly data flow, and it adds latency measured in days.' },
      { id: 'D', text: 'S3 Transfer Acceleration for all transfers.', correct: false, why: 'It adds a premium on top of standard rates and does nothing for latency consistency on non-S3 traffic.' },
    ],
    explanation:
      'Direct Connect wins on sustained high volume because of the reduced egress rate, plus predictable latency. Always pair it with a VPN so one circuit is not a single point of failure.',
    source: 'https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html',
  },
  {
    id: 'saa-d4-015',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['compute-optimizer', 'trusted-advisor', 'cost-explorer'],
    stem: 'An architect must identify which specific EC2 instance types the fleet should move to, based on actual utilisation, with projected savings and performance risk. Which service should be used?',
    options: [
      { id: 'A', text: 'AWS Compute Optimizer', correct: true, why: 'It analyses CloudWatch utilisation data with machine learning and recommends specific instance types, with projected savings and a performance-risk rating.' },
      { id: 'B', text: 'AWS Trusted Advisor', correct: false, why: 'Trusted Advisor flags idle and underutilised resources but does not recommend a specific replacement instance type.' },
      { id: 'C', text: 'AWS Cost Explorer', correct: false, why: 'Cost Explorer recommends Savings Plans and Reserved Instance purchases, not which instance type to run.' },
      { id: 'D', text: 'AWS Well-Architected Tool', correct: false, why: 'That is a guided self-assessment questionnaire, not an automated analysis of utilisation.' },
    ],
    explanation:
      'Which instance type → Compute Optimizer. Should we commit → Cost Explorer. Broad best-practice checks → Trusted Advisor.',
    source: 'https://docs.aws.amazon.com/compute-optimizer/latest/ug/what-is-compute-optimizer.html',
  },
  {
    id: 'saa-d4-016',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['rds', 'backup'],
    stem: 'A team deletes an RDS instance from a development environment each Friday and recreates it each Monday, but the monthly bill barely falls. What is the most likely explanation?',
    options: [
      { id: 'A', text: 'Manual snapshots and retained automated backups continue to incur storage charges after the instance is deleted.', correct: true, why: 'Backup storage is billed independently of the instance. A final snapshot on every deletion accumulates and is easy to overlook.' },
      { id: 'B', text: 'RDS bills a full month regardless of how long the instance runs.', correct: false, why: 'RDS bills per instance-hour. There is no monthly minimum.' },
      { id: 'C', text: 'The Multi-AZ standby continues running after the primary is deleted.', correct: false, why: 'Deleting the instance removes the standby with it.' },
      { id: 'D', text: 'Reserved Instance charges continue whether or not an instance runs.', correct: false, why: 'True of an RI in general, but the question describes on-demand development databases.' },
    ],
    explanation:
      'Deleted resources often leave billable remnants: RDS snapshots, orphaned EBS volumes, unattached Elastic IPs. Teardown means checking for those, not only the obvious resource.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html',
  },
  {
    id: 'saa-d4-017',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['datasync', 'storage-gateway', 'snow-family'],
    stem: 'An on-premises application must continue writing to a local SMB share, but the data should be stored in S3 and only recently used files kept locally. What should be deployed?',
    options: [
      { id: 'A', text: 'AWS Storage Gateway in S3 File Gateway mode.', correct: true, why: 'It presents an SMB or NFS share locally, stores objects in S3, and keeps a local cache of recently used data — exactly the described behaviour, with no application change.' },
      { id: 'B', text: 'AWS DataSync on an hourly schedule.', correct: false, why: 'DataSync copies data; it does not present a share the application can keep writing to, and there is no local cache.' },
      { id: 'C', text: 'AWS Snowball Edge left permanently on site.', correct: false, why: 'Snow is for one-off bulk transfer, not ongoing hybrid access.' },
      { id: 'D', text: 'Mount the S3 bucket directly using a third-party FUSE driver.', correct: false, why: 'Unsupported, fragile under load, and with no managed caching or integrity guarantees.' },
    ],
    explanation:
      'Ongoing local protocol access with a cache is Storage Gateway. Moving data on a schedule is DataSync. Shipping it once is Snow.',
    source: 'https://docs.aws.amazon.com/filegateway/latest/files3/what-is-file-s3.html',
  },
  {
    id: 'saa-d4-018',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ec2', 'elb'],
    stem: 'A cost review finds four Application Load Balancers in a development account, each with no registered healthy targets and no traffic for 60 days. What is the impact and the correct action?',
    options: [
      { id: 'A', text: 'Each costs roughly $16 a month in hourly charges regardless of traffic — delete them.', correct: true, why: 'Load balancers are billed per hour whether or not a request ever arrives. Four idle ALBs are around $64 a month for nothing.' },
      { id: 'B', text: 'They cost nothing when idle, since ALB pricing is purely per-request.', correct: false, why: 'There is an hourly charge as well as capacity units. This is one of the most common forgotten costs in a learning account.' },
      { id: 'C', text: 'They cost nothing but should be deleted for security hygiene.', correct: false, why: 'The hygiene point is fair, but the premise that they are free is wrong.' },
      { id: 'D', text: 'Convert them to Network Load Balancers, which have no hourly charge.', correct: false, why: 'NLBs are also billed hourly. There is no free load balancer.' },
    ],
    explanation:
      'Hourly-billed resources with no usage are the classic waste: load balancers, NAT gateways, EKS control planes, unattached Elastic IPs.',
    source: 'https://aws.amazon.com/elasticloadbalancing/pricing/',
  },
  {
    id: 'saa-d4-019',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dms', 'rds', 'aurora'],
    stem: 'A company pays substantial Oracle licence fees for a database on RDS and wants to move to an open-source engine while minimising downtime. What approach should be used?',
    options: [
      { id: 'A', text: 'AWS Schema Conversion Tool to convert the schema, then AWS DMS with full load plus change data capture to migrate to Aurora PostgreSQL.', correct: true, why: 'The engine changes, so this is a heterogeneous migration: SCT handles schema and procedural code, and DMS with CDC keeps downtime to a short cutover.' },
      { id: 'B', text: 'AWS DMS alone with full load plus CDC.', correct: false, why: 'DMS moves data but not schemas, views or stored procedures across different engines. SCT is required for a heterogeneous move.' },
      { id: 'C', text: 'Take a final snapshot and restore it into Aurora PostgreSQL.', correct: false, why: 'Snapshots cannot be restored across engine types, and it would mean downtime for the whole restore.' },
      { id: 'D', text: 'Set up an Aurora PostgreSQL read replica of the Oracle instance and promote it.', correct: false, why: 'Cross-engine read replicas of that kind do not exist.' },
    ],
    explanation:
      'Same engine means DMS alone. Different engine means DMS plus SCT. CDC is what makes "minimal downtime" possible in either case.',
    source: 'https://docs.aws.amazon.com/dms/latest/userguide/Welcome.html',
  },
  {
    id: 'saa-d4-020',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['api-gateway'],
    stem: 'A public API is being abused by a handful of clients making tens of thousands of requests an hour, driving up backend cost. Paying customers must keep their agreed rate limits. What should be configured?',
    options: [
      { id: 'A', text: 'API Gateway usage plans with API keys, giving each client its own throttle and quota.', correct: true, why: 'Usage plans tie a rate limit and quota to an identified caller, so abusive clients are constrained while paying tiers keep their agreed limits.' },
      { id: 'B', text: 'Account-level API Gateway throttling at a lower requests-per-second value.', correct: false, why: 'It throttles everyone equally, including the paying customers whose limits must be preserved.' },
      { id: 'C', text: 'An AWS WAF rate-based rule blocking IPs above a request threshold.', correct: false, why: 'Useful against a flood from a single IP, but it cannot distinguish a paying customer from an abusive one, and clients behind NAT share addresses.' },
      { id: 'D', text: 'A CloudFront distribution in front of the API with caching enabled.', correct: false, why: 'It helps for cacheable responses, but does nothing about per-client entitlement.' },
    ],
    explanation:
      'Per-client rate limits mean usage plans plus API keys. Account-level throttling and WAF rate rules are the plausible distractors that cannot tell callers apart.',
    source: 'https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html',
  },
  {
    id: 'saa-d4-021',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'multi',
    difficulty: 2,
    serviceSlugs: ['s3'],
    stem: 'A bucket bill is higher than the visible object volume suggests. Versioning is enabled and large uploads are frequently interrupted. Which TWO lifecycle configurations reduce the invisible storage being paid for? (Choose two.)',
    options: [
      { id: 'A', text: 'A rule to abort incomplete multipart uploads after a number of days.', correct: true, why: 'Parts of an upload that never completed are stored and billed but are not listed as objects, so they accumulate silently.' },
      { id: 'B', text: 'A rule to expire noncurrent object versions after a retention period.', correct: true, why: 'With versioning on, every overwrite keeps the old version and is billed for it until a rule removes it.' },
      { id: 'C', text: 'A rule to transition current objects to S3 Glacier Deep Archive after one day.', correct: false, why: 'It would cut cost for cold data and says nothing about the hidden storage, and would break access to hot objects.' },
      { id: 'D', text: 'Suspending versioning on the bucket.', correct: false, why: 'It stops new versions accruing and leaves every existing noncurrent version in place and billed.' },
      { id: 'E', text: 'Enabling Requester Pays on the bucket.', correct: false, why: 'That shifts request and transfer costs to downloaders. Storage cost stays with the bucket owner.' },
    ],
    explanation:
      'Every versioned bucket should carry two hygiene rules — expire noncurrent versions and abort incomplete multipart uploads. They are the two most common sources of a bill nobody can account for.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html',
  },
  {
    id: 'saa-d4-022',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['privatelink', 'vpc', 's3', 'dynamodb'],
    stem: 'A team is adding VPC endpoints to keep traffic off the NAT gateway. They need S3, DynamoDB and Secrets Manager. Which statement about the cost structure is correct?',
    options: [
      { id: 'A', text: 'S3 and DynamoDB can use gateway endpoints, which carry no hourly or data-processing charge; Secrets Manager needs an interface endpoint, which is billed per hour per AZ plus per GB.', correct: true, why: 'Only S3 and DynamoDB offer gateway endpoints, and they are free. Every other service uses interface endpoints, which are PrivateLink and priced accordingly.' },
      { id: 'B', text: 'All three are interface endpoints and billed identically.', correct: false, why: 'S3 and DynamoDB are the two exceptions with a free gateway endpoint option.' },
      { id: 'C', text: 'All three are gateway endpoints, so none of them cost anything.', correct: false, why: 'There is no gateway endpoint for Secrets Manager.' },
      { id: 'D', text: 'Endpoints are free but the traffic through them still incurs NAT data-processing charges.', correct: false, why: 'Traffic over an endpoint bypasses the NAT gateway entirely, which is the saving being sought.' },
    ],
    explanation:
      'Gateway endpoints: S3 and DynamoDB only, route-table based, free. Interface endpoints: everything else, an ENI per subnet, hourly plus per-GB. Knowing which is which decides both cost and network questions.',
    source: 'https://docs.aws.amazon.com/vpc/latest/privatelink/gateway-endpoints.html',
  },
  {
    id: 'saa-d4-023',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['fargate', 'spot', 'ecs'],
    stem: 'A nightly container batch job on ECS runs for about three hours, checkpoints its progress and can be restarted from the last checkpoint. Cost must be as low as possible.',
    options: [
      { id: 'A', text: 'Run the tasks on Fargate Spot.', correct: true, why: 'Fargate Spot gives a large discount for interruption-tolerant work, and a checkpointing, restartable job is precisely the profile it is meant for.' },
      { id: 'B', text: 'Run the tasks on Fargate on-demand with a Compute Savings Plan.', correct: false, why: 'It saves less than Spot and commits you for one or three years for a job that runs three hours a night.' },
      { id: 'C', text: 'Run the tasks on an EC2 capacity provider with Reserved Instances.', correct: false, why: 'Reservations pay for capacity around the clock, most of which this workload does not use.' },
      { id: 'D', text: 'Run the tasks on Fargate on-demand and reduce the task size.', correct: false, why: 'Undersizing makes the job take longer for a smaller unit price, often with no net saving.' },
    ],
    explanation:
      'Interruptible plus restartable equals Spot, whether on EC2 or Fargate. Savings Plans and Reserved Instances are for steady baseline load you will run for a year or more.',
    source: 'https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-capacity-providers.html',
  },
  {
    id: 'saa-d4-024',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['aurora'],
    stem: 'An Aurora cluster bill shows I/O charges at roughly 30% of the total. The workload is write-heavy and its I/O volume is stable. What should be evaluated first?',
    options: [
      { id: 'A', text: 'Switching the cluster to the Aurora I/O-Optimized configuration, where I/O is not billed separately.', correct: true, why: 'I/O-Optimized charges a higher instance and storage rate with no per-request I/O charge, and AWS guidance is that it becomes advantageous once I/O exceeds about 25% of the Aurora spend.' },
      { id: 'B', text: 'Moving to Aurora Serverless v2.', correct: false, why: 'Serverless addresses variable capacity, not the I/O line, and the workload here is described as stable.' },
      { id: 'C', text: 'Adding read replicas to spread the I/O.', correct: false, why: 'Replicas add cost and the workload is write-heavy, so the write I/O remains.' },
      { id: 'D', text: 'Enabling the Aurora query plan cache.', correct: false, why: 'Query-level tuning can reduce I/O but is not the configuration change that removes the charge model.' },
    ],
    explanation:
      'Aurora Standard bills I/O per request — good for low-to-moderate I/O. Aurora I/O-Optimized bundles it into a higher fixed rate — good above roughly 25% I/O spend. The 25% figure is the exam-relevant threshold.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-storage-configurations.html',
  },
  {
    id: 'saa-d4-025',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ebs', 'backup'],
    stem: 'Hundreds of EBS snapshots have accumulated across several accounts with no retention policy, and snapshot storage is now a material cost. The team wants scheduled snapshots with automatic expiry and no code to maintain.',
    options: [
      { id: 'A', text: 'Amazon Data Lifecycle Manager policies for EBS snapshots, or AWS Backup plans with a retention rule.', correct: true, why: 'Both create snapshots on a schedule and delete them when retention lapses, with no custom automation to own.' },
      { id: 'B', text: 'A Lambda function on an EventBridge schedule that deletes snapshots older than 30 days.', correct: false, why: 'It works and is exactly the code the requirement rules out, with the failure modes of any home-grown deleter.' },
      { id: 'C', text: 'Moving the snapshots to the EBS Snapshots Archive tier.', correct: false, why: 'Archiving cuts the rate for snapshots kept 90 days or more, and does nothing about ones nobody needs at all.' },
      { id: 'D', text: 'Deleting the volumes the snapshots were taken from.', correct: false, why: 'Snapshots are independent of their source volume, so this deletes production data and saves nothing.' },
    ],
    explanation:
      'Snapshots are incremental but never expire on their own. DLM or AWS Backup for lifecycle, and Snapshot Archive for the ones that genuinely must be kept for years.',
    source: 'https://docs.aws.amazon.com/ebs/latest/userguide/snapshot-lifecycle.html',
  },
  {
    id: 'saa-d4-026',
    certs: ['SAA-C03'],
    taskId: 'saa-4.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['elb', 'ec2', 'vpc'],
    stem: 'A chatty microservice mesh spread across three Availability Zones shows a large inter-AZ data-transfer charge. Availability requirements must not be weakened.',
    options: [
      { id: 'A', text: 'Deploy a full set of the interdependent services in each AZ and prefer same-AZ routing, keeping every AZ able to serve on its own.', correct: true, why: 'Cross-AZ transfer is billed in both directions. Making each AZ self-sufficient keeps the redundancy while removing the chatter that crosses zones.' },
      { id: 'B', text: 'Consolidate all services into a single Availability Zone.', correct: false, why: 'It removes the charge by removing the resilience the requirement protects.' },
      { id: 'C', text: 'Put the services behind a Network Load Balancer with cross-zone load balancing enabled.', correct: false, why: 'Enabling cross-zone balancing distributes more traffic across AZs, increasing the charge.' },
      { id: 'D', text: 'Use a NAT gateway per AZ.', correct: false, why: 'A NAT gateway per AZ is good practice that avoids cross-AZ NAT charges for internet-bound traffic, but internal service-to-service traffic does not pass through NAT.' },
    ],
    explanation:
      'Cross-AZ data transfer is charged in both directions, and a chatty mesh multiplies it. The architectural answer is zonal self-sufficiency, never fewer AZs.',
    source: 'https://docs.aws.amazon.com/whitepapers/latest/aws-privatelink/data-transfer-costs.html',
  },
  {
    id: 'saa-d4-027',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ec2', 'compute-optimizer'],
    stem: 'A steady-state Linux fleet runs an open-source application stack compiled from source, on x86 instances. Management asks for a substantial price-performance improvement without changing architecture patterns.',
    options: [
      { id: 'A', text: 'Move to Graviton-based instances after rebuilding the application for arm64 and load testing it.', correct: true, why: 'Graviton offers materially better price-performance for most Linux workloads, and the only real work is an arm64 build plus verification.' },
      { id: 'B', text: 'Purchase Reserved Instances for the existing instance types.', correct: false, why: 'A genuine saving on the same hardware, but it is a commitment discount rather than a price-performance improvement, and it locks in the current family.' },
      { id: 'C', text: 'Move the fleet to Spot Instances.', correct: false, why: 'Spot is inappropriate for steady-state serving capacity that cannot absorb interruption.' },
      { id: 'D', text: 'Enable burstable T-family instances across the fleet.', correct: false, why: 'Burstable instances suit spiky low-average workloads and throttle under sustained load.' },
    ],
    explanation:
      'Two independent cost levers: the hardware you run on (Graviton, newer families, right-sizing with Compute Optimizer) and how you buy it (On-Demand, Savings Plans, Reserved, Spot). Good answers usually pull both.',
    source: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html',
  },
  {
    id: 'saa-d4-028',
    certs: ['SAA-C03'],
    taskId: 'saa-4.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb', 's3', 'athena'],
    stem: 'A DynamoDB table has grown to 6 TB, but only the last 90 days of items are ever queried by the application. Older items must remain available for occasional analytical queries at the lowest cost.',
    options: [
      { id: 'A', text: 'Enable TTL to remove items after 90 days, and stream expiring items to S3 for querying with Athena.', correct: true, why: 'TTL deletes at no write cost and keeps the table small, while S3 with Athena is the cheap home for data that is queried rarely.' },
      { id: 'B', text: 'Move the table to on-demand capacity mode.', correct: false, why: 'That changes how throughput is billed. Storage cost for 6 TB is unchanged.' },
      { id: 'C', text: 'Add a GSI on the date attribute so old items can be excluded from queries.', correct: false, why: 'An index adds storage and cost rather than removing any.' },
      { id: 'D', text: 'Export the table to S3 monthly and keep everything in DynamoDB as well.', correct: false, why: 'It creates the analytical copy and pays twice, because nothing ever leaves the table.' },
    ],
    explanation:
      'TTL plus a stream to S3 is the standard DynamoDB tiering pattern: keep the operational table small and hot, and let S3 and Athena serve the long tail.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html',
  },
  {
    id: 'saa-d4-029',
    certs: ['SAA-C03'],
    taskId: 'saa-4.1',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['s3', 's3-glacier'],
    stem: 'A team moved 20 TB of freshly written logs straight to S3 Glacier Deep Archive, then had to retrieve some of them a week later. The bill was far higher than the storage rate implied. Why?',
    options: [
      { id: 'A', text: 'Deep Archive has a 180-day minimum storage duration charge and per-GB retrieval fees, so objects deleted or read early are billed as if stored for the full period.', correct: true, why: 'Minimum duration charges — 30 days for Standard-IA and One Zone-IA, 90 for Glacier Flexible Retrieval, 180 for Deep Archive — plus retrieval fees are what make early access expensive.' },
      { id: 'B', text: 'Deep Archive charges a higher per-GB storage rate for the first 30 days.', correct: false, why: 'The storage rate is flat; it is the minimum duration and retrieval charges that apply.' },
      { id: 'C', text: 'Retrievals from Deep Archive are billed as internet data transfer out.', correct: false, why: 'Egress is billed separately and only if the data leaves AWS. The retrieval fee is a distinct charge.' },
      { id: 'D', text: 'Objects under 128 KB are not eligible for Deep Archive and were billed at Standard rates.', correct: false, why: 'Small objects do carry a 40 KB metadata overhead per object, but that is not the main effect here.' },
    ],
    explanation:
      'Archive tiers are cheap to hold and expensive to touch. Memorise the minimum durations — 30, 30, 90, 180 days — and only transition data whose access pattern you actually know.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html',
  },
  {
    id: 'saa-d4-030',
    certs: ['SAA-C03'],
    taskId: 'saa-4.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['organizations', 'savings-plans', 'cost-explorer'],
    stem: 'An organisation has 30 accounts under consolidated billing. Several teams have unused Reserved Instance and Savings Plans coverage while others pay On-Demand rates. What explains this and what should be checked?',
    options: [
      { id: 'A', text: 'Discount sharing may be turned off — with sharing enabled in the management account, unused reservation and Savings Plans benefit is applied across accounts automatically.', correct: true, why: 'Consolidated billing shares reservation and Savings Plans benefit across the organisation by default, and it can be disabled per account, which produces exactly this pattern.' },
      { id: 'B', text: 'Reservations are account-specific and cannot be shared, so each team must buy its own.', correct: false, why: 'That is only true of zonal Reserved Instances with a specific AZ, or where sharing has been switched off.' },
      { id: 'C', text: 'Savings Plans only apply to the account that purchased them.', correct: false, why: 'Savings Plans benefit is shared across the organisation when discount sharing is enabled.' },
      { id: 'D', text: 'The accounts need to be in the same OU for discounts to apply.', correct: false, why: 'OU structure governs policy, not billing benefit distribution.' },
    ],
    explanation:
      'Consolidated billing gives you two things worth remembering: volume-tier aggregation, and reservation and Savings Plans sharing across accounts — both controlled from the management account.',
    source: 'https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/ri-turn-off.html',
  },
]
