import type { Question } from '../schema'

/** Design High-Performing Architectures — 24% of SAA-C03. Right tool per layer. */
export const saaD3Questions: Question[] = [
  {
    id: 'saa-d3-001',
    certs: ['SAA-C03'],
    taskId: 'saa-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['s3', 'ebs', 'efs', 'fsx'],
    stem: 'A machine-learning training job on 40 GPU instances must read a 20 TB dataset held in S3 at hundreds of gigabytes per second, using standard POSIX file access. What storage should be placed in front of it?',
    options: [
      { id: 'A', text: 'Amazon FSx for Lustre, linked to the S3 bucket.', correct: true, why: 'Lustre is built for parallel HPC throughput and links natively to S3, lazily loading objects as files so the bucket stays the source of truth.' },
      { id: 'B', text: 'Amazon EFS with Max I/O performance mode.', correct: false, why: 'EFS scales well but does not reach the hundreds-of-GB/s parallel throughput HPC and ML training workloads describe.' },
      { id: 'C', text: 'An io2 Block Express EBS volume attached to each instance.', correct: false, why: 'EBS is not shared across instances in this way, and each instance would need its own copy of 20 TB.' },
      { id: 'D', text: 'S3 accessed directly through the AWS SDK.', correct: false, why: 'The requirement specifies POSIX file access, which S3 does not provide.' },
    ],
    explanation:
      'HPC or ML training plus extreme throughput over data in S3 means FSx for Lustre. Ordinary Linux NFS means EFS.',
    source: 'https://docs.aws.amazon.com/fsx/latest/LustreGuide/what-is.html',
  },
  {
    id: 'saa-d3-002',
    certs: ['SAA-C03'],
    taskId: 'saa-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'A DynamoDB table stores events with partition key eventDate (one value per day) and sort key eventId. Writes are throttled during business hours despite provisioned capacity being far above the table average. What is wrong?',
    options: [
      { id: 'A', text: 'The partition key has very low cardinality, so all of a day\'s writes hit one partition and exceed its 1,000 WCU ceiling.', correct: true, why: 'Capacity is spread across partitions but a single partition is capped. A key with one value per day concentrates the entire day\'s traffic onto one partition.' },
      { id: 'B', text: 'The table needs a local secondary index to spread writes.', correct: false, why: 'An LSI shares the same partition key, so it inherits exactly the same hot partition.' },
      { id: 'C', text: 'Provisioned capacity should be replaced with a larger instance type.', correct: false, why: 'DynamoDB has no instance types — that concept does not apply.' },
      { id: 'D', text: 'Writes should use eventually consistent mode to reduce cost.', correct: false, why: 'Consistency is a read concept. It has no effect on write throttling.' },
    ],
    explanation:
      'Per-partition limits are 3,000 RCU and 1,000 WCU. A high-cardinality partition key — or a write-sharding suffix — is the fix, not more capacity.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html',
  },
  {
    id: 'saa-d3-003',
    certs: ['SAA-C03'],
    taskId: 'saa-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['cloudfront', 'global-accelerator', 's3'],
    stem: 'A media company serves large video files to viewers worldwide from S3. Users far from the bucket report slow downloads, and the S3 data-transfer bill is high. What should be added?',
    options: [
      { id: 'A', text: 'Amazon CloudFront in front of the bucket, with Origin Access Control restricting direct bucket access.', correct: true, why: 'Caching at the edge cuts latency, origin fetches from S3 to CloudFront are free, and CloudFront egress rates are lower than S3-to-internet — so it improves speed and cost together.' },
      { id: 'B', text: 'AWS Global Accelerator pointed at the S3 bucket.', correct: false, why: 'Global Accelerator does not cache and is aimed at TCP/UDP endpoints. For cacheable HTTP content CloudFront is the right tool.' },
      { id: 'C', text: 'S3 Transfer Acceleration on the bucket.', correct: false, why: 'Transfer Acceleration is optimised for long-distance *uploads* and adds cost. It does not cache downloads.' },
      { id: 'D', text: 'Cross-Region Replication into buckets on every continent, with Route 53 latency routing.', correct: false, why: 'It would work but multiplies storage cost and operational complexity for something a CDN does natively.' },
    ],
    explanation:
      'Cacheable HTTP content to a global audience is always CloudFront. Global Accelerator is for non-HTTP protocols, static IPs and fast regional failover.',
    source: 'https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html',
  },
  {
    id: 'saa-d3-004',
    certs: ['SAA-C03'],
    taskId: 'saa-3.5',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['athena', 'glue', 's3'],
    stem: 'An analytics team runs occasional ad-hoc SQL over 15 TB of JSON application logs in S3. Query costs are far higher than expected. What change reduces cost the most?',
    options: [
      { id: 'A', text: 'Convert the logs to Parquet with compression and partition them by date, then query the partitioned table.', correct: true, why: 'Athena bills per terabyte scanned. A columnar format reads only the needed columns, compression shrinks the bytes, and partitioning lets the engine skip whole days.' },
      { id: 'B', text: 'Move the data into Amazon Redshift and query it there.', correct: false, why: 'A provisioned warehouse for occasional queries adds fixed cost, and the question describes ad-hoc exploratory use.' },
      { id: 'C', text: 'Enable Athena result caching and query the results repeatedly.', correct: false, why: 'It helps for identical repeated queries but does nothing for ad-hoc ones, which is what was described.' },
      { id: 'D', text: 'Move the logs to S3 Intelligent-Tiering.', correct: false, why: 'That reduces storage cost, not query cost. Athena charges for bytes scanned regardless of storage class.' },
    ],
    explanation:
      'Athena cost is bytes scanned. Parquet plus compression plus partitioning is the canonical answer and typically cuts cost by an order of magnitude.',
    source: 'https://docs.aws.amazon.com/athena/latest/ug/performance-tuning-data-optimization-techniques.html',
  },
  {
    id: 'saa-d3-005',
    certs: ['SAA-C03'],
    taskId: 'saa-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['elasticache', 'rds', 'dynamodb'],
    stem: 'A product catalogue page runs the same expensive join on every request. The RDS instance is at 90% CPU. The application can be modified. What is the highest-leverage change?',
    options: [
      { id: 'A', text: 'Add ElastiCache for Redis and cache the rendered query result with a TTL.', correct: true, why: 'A repeated identical read is the textbook cache case — a hit removes the query entirely rather than making the database faster at doing it.' },
      { id: 'B', text: 'Add read replicas and send catalogue queries to them.', correct: false, why: 'It distributes the expensive join rather than eliminating it, so you pay for more instances to do redundant work.' },
      { id: 'C', text: 'Migrate the catalogue to DynamoDB.', correct: false, why: 'A large rewrite, and joins are exactly what DynamoDB does not do. It may be right long-term but it is not the highest-leverage change.' },
      { id: 'D', text: 'Increase the RDS instance class to one with more vCPUs.', correct: false, why: 'It buys headroom linearly with cost, requires a restart, and does nothing about the redundancy of the work.' },
    ],
    explanation:
      'When the same read repeats, cache first and replicate second. Caching removes work; replicas only spread it.',
    source: 'https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/Strategies.html',
  },
  {
    id: 'saa-d3-006',
    certs: ['SAA-C03'],
    taskId: 'saa-3.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ec2'],
    stem: 'A t3.medium instance running a batch job performs well for 20 minutes, then slows dramatically and stays slow. CPU utilisation is pinned at a low ceiling. What explains this?',
    options: [
      { id: 'A', text: 'The instance has exhausted its CPU credits and is throttled to its baseline performance.', correct: true, why: 'Burstable T-family instances accrue credits and spend them above baseline. Once exhausted, performance drops to the baseline percentage until credits rebuild.' },
      { id: 'B', text: 'The EBS volume has exhausted its burst balance.', correct: false, why: 'Plausible in general, but the symptom described is a CPU ceiling, not I/O latency.' },
      { id: 'C', text: 'The instance is being live-migrated to another host.', correct: false, why: 'AWS does not degrade performance for 20-minute periods this way, and it would not present as a stable CPU ceiling.' },
      { id: 'D', text: 'The security group is rate-limiting the instance.', correct: false, why: 'Security groups filter traffic; they have no bearing on CPU.' },
    ],
    explanation:
      'A steady job on a burstable instance is a mismatch. Enable unlimited mode for a fee, or move to M or C family — the proper fix for sustained load.',
    source: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances.html',
  },
  {
    id: 'saa-d3-007',
    certs: ['SAA-C03'],
    taskId: 'saa-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ebs'],
    stem: 'A self-managed database on EC2 needs 12,000 IOPS on a 200 GB volume. It currently runs on a gp2 volume and is not meeting the requirement. What is the most cost-effective change?',
    options: [
      { id: 'A', text: 'Switch to gp3 and provision 12,000 IOPS independently of volume size.', correct: true, why: 'gp3 decouples IOPS from capacity and is cheaper per GB than gp2, so you buy the IOPS you need without paying for terabytes you do not.' },
      { id: 'B', text: 'Grow the gp2 volume to 4,000 GB to reach 12,000 IOPS.', correct: false, why: 'gp2 gives 3 IOPS per GB, so this works — but you pay for 3.8 TB of unused capacity. This is exactly what gp3 was introduced to fix.' },
      { id: 'C', text: 'Switch to io2 Block Express and provision 12,000 IOPS.', correct: false, why: 'It meets the requirement but costs more than gp3, which reaches 16,000 IOPS. Reserve io2 for higher IOPS or the 99.999% durability guarantee.' },
      { id: 'D', text: 'Switch to st1, which is throughput-optimised.', correct: false, why: 'st1 is HDD for large sequential reads, has far lower IOPS, and cannot be a boot volume.' },
    ],
    explanation:
      '"More IOPS but not more space" is always gp3. Growing a gp2 volume for IOPS is the legacy workaround the exam wants you to reject.',
    source: 'https://docs.aws.amazon.com/ebs/latest/userguide/general-purpose.html',
  },
  {
    id: 'saa-d3-008',
    certs: ['SAA-C03'],
    taskId: 'saa-3.5',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['data-firehose', 'kinesis-data-streams', 's3'],
    stem: 'IoT devices send telemetry that must land in S3 as Parquet for later analysis. The team wants no consumer code and no shard management, and a delay of a minute or two is acceptable. What should be used?',
    options: [
      { id: 'A', text: 'Amazon Data Firehose with record format conversion to Parquet, delivering to S3.', correct: true, why: 'Firehose buffers, converts JSON to Parquet natively, and delivers with no consumer application and no shards to size.' },
      { id: 'B', text: 'Kinesis Data Streams with a Lambda consumer writing Parquet to S3.', correct: false, why: 'It works, but you now own the consumer code and the shard maths — precisely what the requirement excludes.' },
      { id: 'C', text: 'Amazon MSK with a Kafka Connect S3 sink.', correct: false, why: 'The heaviest option operationally, and there is no Kafka requirement.' },
      { id: 'D', text: 'An SQS queue with a Lambda function writing to S3.', correct: false, why: 'No native format conversion, no batching by size or time, and you write and operate the consumer.' },
    ],
    explanation:
      '"Near real-time, into S3, no code" is Firehose. Add replay, ordering or multiple independent consumers and it becomes Data Streams.',
    source: 'https://docs.aws.amazon.com/firehose/latest/dev/what-is-this-service.html',
  },
  {
    id: 'saa-d3-009',
    certs: ['SAA-C03'],
    taskId: 'saa-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['dynamodb'],
    stem: 'An application must query orders by customerId, and separately list all orders with status "pending" across every customer. The table\'s partition key is customerId and sort key is orderId. What should be added?',
    options: [
      { id: 'A', text: 'A global secondary index with status as the partition key.', correct: true, why: 'A GSI can use a completely different partition key, which is what makes a query on a non-key attribute possible without scanning.' },
      { id: 'B', text: 'A local secondary index with status as the sort key.', correct: false, why: 'An LSI keeps the same partition key, so you could only find pending orders within one customer — not across all of them.' },
      { id: 'C', text: 'A Scan with a FilterExpression on status.', correct: false, why: 'A filter is applied after the read, so you pay to read the whole table every time. This is the pattern the GSI exists to replace.' },
      { id: 'D', text: 'A second table holding only pending orders, kept in sync by the application.', correct: false, why: 'A GSI does exactly this, maintained by DynamoDB, without dual-write consistency bugs.' },
    ],
    explanation:
      'GSI = different partition key, eventually consistent, addable any time. LSI = same partition key, can be strongly consistent, only at table creation.',
    source: 'https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html',
  },
  {
    id: 'saa-d3-010',
    certs: ['SAA-C03'],
    taskId: 'saa-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['transit-gateway', 'vpc-peering'],
    stem: 'A company has 22 VPCs across three accounts that must all communicate, plus a Direct Connect link that should be shared by all of them. They currently maintain VPC peering connections. What should they move to?',
    options: [
      { id: 'A', text: 'AWS Transit Gateway, with each VPC and the Direct Connect gateway attached once.', correct: true, why: 'Transit Gateway is transitive and turns an n² peering mesh into n attachments, and it is the only way to share one Direct Connect link across many VPCs.' },
      { id: 'B', text: 'A full mesh of VPC peering connections between all 22 VPCs.', correct: false, why: '231 connections, none of them transitive, and peering explicitly does not support edge-to-edge routing so the Direct Connect link cannot be shared.' },
      { id: 'C', text: 'AWS PrivateLink endpoints between every pair of VPCs.', correct: false, why: 'PrivateLink exposes a single service one-directionally. It is not general network routing.' },
      { id: 'D', text: 'A VPN mesh using Site-to-Site VPN between VPCs.', correct: false, why: 'Enormous operational overhead and lower throughput, for something Transit Gateway does natively.' },
    ],
    explanation:
      'Many VPCs, hub-and-spoke, or sharing a hybrid link — all point at Transit Gateway. Peering is for two or three VPCs and is never transitive.',
    source: 'https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html',
  },
  {
    id: 'saa-d3-011',
    certs: ['SAA-C03'],
    taskId: 'saa-3.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['ec2-auto-scaling', 'cloudwatch'],
    stem: 'Traffic to a web application triples every weekday at 09:00 and falls again at 18:00. Metric-based scaling reacts too slowly and users see errors for the first ten minutes. What should be configured?',
    options: [
      { id: 'A', text: 'Scheduled scaling to raise the desired capacity shortly before 09:00.', correct: true, why: 'The pattern is known by the clock, so capacity can be added before the load arrives rather than in reaction to it.' },
      { id: 'B', text: 'Target tracking on CPU with a lower target value.', correct: false, why: 'Still reactive: the metric must rise, the alarm must breach, and instances must boot — which is the ten minutes being complained about.' },
      { id: 'C', text: 'Step scaling with more aggressive steps.', correct: false, why: 'Also reactive, and more aggressive steps risk over-provisioning on ordinary fluctuations.' },
      { id: 'D', text: 'A shorter health check grace period so instances join faster.', correct: false, why: 'That governs health evaluation, not launch speed, and shortening it risks killing instances mid-boot.' },
    ],
    explanation:
      'Predictable by the clock means scheduled scaling. Predictable from history but not fixed to a clock means predictive scaling. Unpredictable means target tracking.',
    source: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-scheduled-scaling.html',
  },
  {
    id: 'saa-d3-012',
    certs: ['SAA-C03'],
    taskId: 'saa-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['aurora', 'rds'],
    stem: 'A PostgreSQL workload needs up to 15 read replicas with replica lag under 100 ms, and failover in under 30 seconds. Which option meets this?',
    options: [
      { id: 'A', text: 'Amazon Aurora PostgreSQL with Aurora Replicas behind the reader endpoint.', correct: true, why: 'Aurora replicas read the same shared storage volume rather than replaying a log, which is what gives millisecond lag, up to 15 replicas and sub-30-second failover.' },
      { id: 'B', text: 'RDS for PostgreSQL with 15 read replicas.', correct: false, why: 'RDS replication is asynchronous log shipping, so lag is typically higher and promotion is a manual, slower operation.' },
      { id: 'C', text: 'RDS for PostgreSQL Multi-AZ with the standby serving reads.', correct: false, why: 'The classic Multi-AZ standby serves no reads at all.' },
      { id: 'D', text: 'DynamoDB with a global secondary index for read scale.', correct: false, why: 'A different data model entirely — no SQL and no joins — so it does not meet a PostgreSQL requirement.' },
    ],
    explanation:
      'Aurora\'s shared storage layer is why it beats RDS on replica count, lag and failover time. Those three numbers together are the Aurora signature.',
    source: 'https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Replication.html',
  },
  {
    id: 'saa-d3-013',
    certs: ['SAA-C03'],
    taskId: 'saa-3.1',
    type: 'single',
    difficulty: 1,
    serviceSlugs: ['s3'],
    stem: 'A team uploads 4 GB video files to S3 over an unreliable connection. Uploads frequently fail near the end and must restart from the beginning. What should they use?',
    options: [
      { id: 'A', text: 'Multipart upload, so only the failed parts are retried.', correct: true, why: 'Multipart splits the object into independently retryable parts, uploads them in parallel, and is required above 5 GB and recommended above 100 MB.' },
      { id: 'B', text: 'S3 Transfer Acceleration.', correct: false, why: 'It speeds long-distance transfer over the CloudFront edge network but does not make a failed upload resumable.' },
      { id: 'C', text: 'A presigned URL with a longer expiry.', correct: false, why: 'Expiry is unrelated to resumability, and the failure is network interruption rather than authorisation.' },
      { id: 'D', text: 'AWS DataSync.', correct: false, why: 'Suited to bulk or scheduled transfer from a file system, not individual interactive uploads from a client.' },
    ],
    explanation:
      'Multipart solves reliability and throughput for large objects; Transfer Acceleration solves distance. They address different problems and are often offered together.',
    source: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html',
  },
  {
    id: 'saa-d3-014',
    certs: ['SAA-C03'],
    taskId: 'saa-3.4',
    type: 'single',
    difficulty: 3,
    serviceSlugs: ['vpc'],
    stem: 'A VPC uses 10.0.0.0/16. An architect must create a subnet supporting at least 500 usable IP addresses. What is the smallest suitable subnet CIDR?',
    options: [
      { id: 'A', text: '10.0.0.0/23 — 512 addresses, 507 usable.', correct: true, why: 'A /23 gives 512 addresses; AWS reserves five per subnet, leaving 507 — the smallest size that clears 500.' },
      { id: 'B', text: '10.0.0.0/24 — 256 addresses, 251 usable.', correct: false, why: '251 usable is short of the 500 required.' },
      { id: 'C', text: '10.0.0.0/22 — 1,024 addresses, 1,019 usable.', correct: false, why: 'It works but wastes half the range, and the question asks for the smallest suitable subnet.' },
      { id: 'D', text: '10.0.0.0/25 — 128 addresses, 123 usable.', correct: false, why: 'Far short of the requirement.' },
    ],
    explanation:
      'AWS reserves five addresses in every subnet: network, VPC router, DNS, future use and broadcast. Always subtract five before comparing against a requirement.',
    source: 'https://docs.aws.amazon.com/vpc/latest/userguide/subnet-sizing.html',
  },
  {
    id: 'saa-d3-015',
    certs: ['SAA-C03'],
    taskId: 'saa-3.5',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['snow-family', 'datasync', 'direct-connect'],
    stem: 'A company must move 300 TB from an on-premises NAS into S3. The internet link is 200 Mbps and is also used by the business. The migration must complete within three weeks. What should be used?',
    options: [
      { id: 'A', text: 'AWS Snowball Edge devices shipped to the data centre.', correct: true, why: 'At 200 Mbps, 300 TB takes roughly 140 days of saturated link — and the link is shared. Shipping devices is both faster and less disruptive.' },
      { id: 'B', text: 'AWS DataSync over the existing internet connection with bandwidth throttling.', correct: false, why: 'Throttling makes the arithmetic worse. DataSync cannot beat the physics of the link.' },
      { id: 'C', text: 'AWS Direct Connect with a 1 Gbps port.', correct: false, why: 'Provisioning takes weeks to months — longer than the migration window — and even 1 Gbps would need about a month.' },
      { id: 'D', text: 'S3 Transfer Acceleration with parallel multipart uploads.', correct: false, why: 'It improves efficiency over a long distance but is still bounded by the same 200 Mbps.' },
    ],
    explanation:
      'Always do the arithmetic the question gives you. Divide the dataset by the link speed: if the answer exceeds about a week, ship the data.',
    source: 'https://docs.aws.amazon.com/snowball/latest/developer-guide/whatisedge.html',
  },
  {
    id: 'saa-d3-016',
    certs: ['SAA-C03'],
    taskId: 'saa-3.2',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['lambda'],
    stem: 'A Lambda function that transforms images has a 128 MB memory setting and takes 9 seconds per invocation. Raising memory to 1024 MB reduces it to 1.1 seconds. What is the cost effect?',
    options: [
      { id: 'A', text: 'Cost is roughly unchanged or slightly lower, because Lambda bills GB-seconds and the duration fell by more than memory rose.', correct: true, why: 'Billing is memory × duration. Eight times the memory for one eighth of the duration is roughly cost-neutral — and often cheaper once request overhead is included.' },
      { id: 'B', text: 'Cost rises about eightfold, because memory rose eightfold.', correct: false, why: 'That ignores duration, which is the other half of the GB-second calculation.' },
      { id: 'C', text: 'Cost falls about eightfold, because duration fell eightfold.', correct: false, why: 'Same error in the other direction — the memory increase offsets the duration saving.' },
      { id: 'D', text: 'Cost is unaffected, because Lambda bills per invocation only.', correct: false, why: 'There is a per-request charge, but the dominant term is GB-seconds.' },
    ],
    explanation:
      'CPU scales with memory, so more memory often makes a function both faster and no more expensive. Under-provisioning memory is a common and invisible waste.',
    source: 'https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html',
  },
  {
    id: 'saa-d3-017',
    certs: ['SAA-C03'],
    taskId: 'saa-3.1',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['fsx', 'efs', 'directory-service'],
    stem: 'A Windows application requires an SMB file share with Windows ACLs, joined to Active Directory, accessible from EC2 Windows instances in two Availability Zones. What should be used?',
    options: [
      { id: 'A', text: 'Amazon FSx for Windows File Server in a Multi-AZ deployment.', correct: true, why: 'FSx for Windows is a genuine Windows file system with SMB, NTFS ACLs and AD integration, and supports Multi-AZ.' },
      { id: 'B', text: 'Amazon EFS with the instances mounting it over NFS.', correct: false, why: 'EFS is NFS and Linux-only. Any mention of Windows or SMB rules it out.' },
      { id: 'C', text: 'S3 File Gateway presenting an SMB share.', correct: false, why: 'That is for on-premises access to S3, not a native file system inside AWS for EC2.' },
      { id: 'D', text: 'An EBS Multi-Attach volume shared between the instances.', correct: false, why: 'Single-AZ, and it requires a cluster-aware file system — NTFS would corrupt.' },
    ],
    explanation:
      'Windows, SMB or Active Directory in a storage question means FSx for Windows File Server. It is the single most common FSx question.',
    source: 'https://docs.aws.amazon.com/fsx/latest/WindowsGuide/what-is.html',
  },
  {
    id: 'saa-d3-018',
    certs: ['SAA-C03'],
    taskId: 'saa-3.3',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['redshift', 'athena'],
    stem: 'A BI team of 40 analysts runs complex multi-table joins over 8 TB of structured data throughout the working day, with dashboards refreshing every few minutes. Query latency must be consistently low. What is most appropriate?',
    options: [
      { id: 'A', text: 'Amazon Redshift with RA3 nodes and Concurrency Scaling enabled.', correct: true, why: 'Repeated, complex, latency-sensitive queries from many users is exactly what a warehouse is for, and Concurrency Scaling absorbs bursts of dashboard refreshes.' },
      { id: 'B', text: 'Amazon Athena over Parquet files in S3.', correct: false, why: 'Athena suits occasional ad-hoc queries. With 40 concurrent users refreshing dashboards all day, per-query pricing and variable latency both work against you.' },
      { id: 'C', text: 'Amazon RDS for PostgreSQL on a memory-optimised instance.', correct: false, why: 'Row-oriented OLTP storage is the wrong shape for analytical scans over 8 TB.' },
      { id: 'D', text: 'Amazon EMR with Spark SQL and a persistent cluster.', correct: false, why: 'Far more operational overhead, and Spark SQL is not tuned for interactive dashboard latency.' },
    ],
    explanation:
      'Athena versus Redshift comes down to frequency and concurrency. Occasional and serverless means Athena; a BI team all day means Redshift.',
    source: 'https://docs.aws.amazon.com/redshift/latest/dg/concurrency-scaling.html',
  },
  {
    id: 'saa-d3-019',
    certs: ['SAA-C03'],
    taskId: 'saa-3.4',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['elb', 'global-accelerator'],
    stem: 'A multiplayer game server uses a custom UDP protocol. Clients on strict corporate firewalls must allowlist a small set of fixed IP addresses, and players should reach the nearest healthy Region. What should front the servers?',
    options: [
      { id: 'A', text: 'AWS Global Accelerator with Network Load Balancers as endpoints in each Region.', correct: true, why: 'Global Accelerator provides two static anycast IPs, carries UDP, routes to the nearest healthy Region over the AWS backbone, and fails over in seconds.' },
      { id: 'B', text: 'Amazon CloudFront with the game servers as custom origins.', correct: false, why: 'CloudFront serves HTTP/HTTPS only and cannot carry a custom UDP protocol.' },
      { id: 'C', text: 'An Application Load Balancer per Region with Route 53 latency routing.', correct: false, why: 'An ALB is HTTP-only, and DNS gives no static IPs to allowlist.' },
      { id: 'D', text: 'A Network Load Balancer per Region with Route 53 latency routing.', correct: false, why: 'NLB handles UDP and gives static IPs per Region, but the client would need every Region\'s IPs allowlisted and failover would depend on DNS caching.' },
    ],
    explanation:
      'Static anycast IPs plus non-HTTP plus fast regional failover is the Global Accelerator signature, and all three appear in this stem.',
    source: 'https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html',
  },
  {
    id: 'saa-d3-020',
    certs: ['SAA-C03'],
    taskId: 'saa-3.5',
    type: 'single',
    difficulty: 2,
    serviceSlugs: ['opensearch', 'cloudwatch', 'athena'],
    stem: 'A support team needs to search application logs interactively with typo tolerance and relevance ranking, and visualise error trends on dashboards. Logs are currently in CloudWatch Logs. What should be added?',
    options: [
      { id: 'A', text: 'Stream the logs to Amazon OpenSearch Service with a CloudWatch Logs subscription filter, and use OpenSearch Dashboards.', correct: true, why: 'OpenSearch provides full-text search with relevance and fuzzy matching plus dashboards, which CloudWatch Logs Insights does not.' },
      { id: 'B', text: 'Use CloudWatch Logs Insights queries with a saved dashboard.', correct: false, why: 'Insights is a good query language over logs, but it has no relevance ranking or typo tolerance — the specific requirements here.' },
      { id: 'C', text: 'Export logs to S3 and query them with Athena.', correct: false, why: 'Fine for occasional SQL analysis, but not interactive search with ranking, and not dashboards for a support team.' },
      { id: 'D', text: 'Use Amazon Kendra to index the log group.', correct: false, why: 'Kendra is natural-language enterprise document search, not high-volume operational log analytics.' },
    ],
    explanation:
      'The words "search", "relevance" or "typo tolerance" mean OpenSearch. Plain log querying is CloudWatch Logs Insights; archived SQL analysis is Athena.',
    source: 'https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html',
  },
]
